// THE GOLDEN TABLE'S READER AND THE PORT'S ANSWER, IN A FILE THAT COMPILES
// WITHOUT UNREAL.
//
// WHAT THE GOLDEN TABLE IS. ledger/PerceptionGolden/Program.cs runs the REAL
// Ledger.Core as shipped and writes ue-probe/perception-golden.txt: one row
// per case, `fn|args...|expected`. The C++ transliteration under LedgerCore
// reads the same file and must agree. A table generated by the original and
// consumed by the port has ONE source of truth and no second implementation
// of the expectations, which is why it exists instead of a ported test
// suite: porting 130 NUnit methods would prove the port agrees with a SECOND
// transliteration rather than with the original.
//
// WHY THE DISPATCH LIVES HERE AND NOT IN LedgerProbe.cpp. The standing rule
// from 25 August: measurement arithmetic and formatting live where the tests
// run. LedgerProbe.cpp compiles only on Jafar's PC, so a dispatcher written
// there ships UNRUN and the first thing that finds out whether it works is a
// 25-minute round trip. Everything that can be wrong about READING a row and
// ANSWERING it is therefore in this header, and
// ue-probe/tests/core-port-test.cpp compiles it with g++ and runs it against
// the REAL committed table before anything is dispatched. The module
// supplies the file's bytes and nothing else.
//
// NO VALUE IN THE TABLE CONTAINS A SPACE, A NEWLINE OR A PIPE, and that is
// this project's own rule rather than a convenience: every reader here
// splits on a delimiter and truncates silently when one appears. Strings
// travel escaped, space as ~, newline as ^, pipe as !, and both engines use
// the same three substitutions. A fixture carrying one of the three
// substitute characters would round-trip wrongly, so neither side is allowed
// to build one, and Escape says so where it happens.
//
// THE SCENARIOS ARE THE FIXTURE WRITTEN TWICE, and that is a real cost named
// rather than hidden. A stateful thing (a memory that prunes, a mill that
// ticks) cannot be described by one row of arguments, so each scenario is
// built by both engines and its READINGS are compared. If the two builders
// ever drift apart the readings disagree and the test goes red; the failure
// mode this cannot have is a silent pass, because a silent pass would need
// both builders to be wrong in the same way at the same time.
#pragma once

#include "GameTime.h"
#include "Gossip.h"
#include "MemoryStore.h"
#include "Observation.h"
#include "Perception.h"
#include "Suspicion.h"

#include <cstdio>
#include <cstdlib>
#include <string>
#include <vector>

namespace LedgerCore
{
namespace Golden
{
	// ---- the table's small vocabulary -------------------------------

	inline std::string Escape(const std::string& S)
	{
		std::string Out;
		Out.reserve(S.size());
		for (std::string::size_type I = 0; I < S.size(); ++I)
		{
			const char C = S[I];
			if      (C == ' ')  Out += '~';
			else if (C == '\n') Out += '^';
			else if (C == '\r') { /* dropped: a line ending is a platform fact */ }
			else if (C == '|')  Out += '!';
			else                Out += C;
		}
		return Out;
	}

	inline std::string Unescape(const std::string& S)
	{
		std::string Out;
		Out.reserve(S.size());
		for (std::string::size_type I = 0; I < S.size(); ++I)
		{
			const char C = S[I];
			if      (C == '~') Out += ' ';
			else if (C == '^') Out += '\n';
			else if (C == '!') Out += '|';
			else               Out += C;
		}
		return Out;
	}

	inline std::string FromBool(bool B) { return B ? "1" : "0"; }

	inline std::string FromInt(long long V)
	{
		char Buf[32];
		std::snprintf(Buf, sizeof(Buf), "%lld", V);
		return std::string(Buf);
	}

	// The shortest decimal that reads back as this double, which is what
	// C#'s "R" writes into the table.
	inline std::string FromDouble(double V) { return ShortestRoundTrip(V); }

	inline double D(const std::string& S) { return std::strtod(S.c_str(), 0); }
	inline bool   B(const std::string& S) { return S == "1"; }
	inline int    I(const std::string& S) { return (int)std::strtol(S.c_str(), 0, 10); }

	inline bool IsNumber(const std::string& S)
	{
		if (S.empty()) return false;
		char* End = 0;
		std::strtod(S.c_str(), &End);
		return End != 0 && *End == '\0';
	}

	// TWO NUMBERS COMPARE NUMERICALLY, EVERYTHING ELSE COMPARES EXACTLY.
	// A string answer with one character wrong is a failure however close it
	// looks, and a double is never asked to be bit-identical across two
	// runtimes' libm.
	inline bool Agrees(const std::string& Got, const std::string& Want, double Tol)
	{
		if (IsNumber(Got) && IsNumber(Want))
		{
			const double A = D(Got), Bv = D(Want);
			const double Diff = A > Bv ? A - Bv : Bv - A;
			return Diff <= Tol;
		}
		return Got == Want;
	}

	inline std::vector<std::string> SplitPipe(const std::string& Line)
	{
		std::vector<std::string> Out;
		std::string Cur;
		for (std::string::size_type P = 0; P < Line.size(); ++P)
		{
			if (Line[P] == '|') { Out.push_back(Cur); Cur.clear(); }
			else                { Cur += Line[P]; }
		}
		Out.push_back(Cur);
		return Out;
	}

	// ---- the scenarios ----------------------------------------------
	//
	// Each one builds a world, then reads it. The keys are the contract with
	// ledger/PerceptionGolden/Program.cs, which builds the same world in C#
	// and writes the same keys with the C#'s answers.

	typedef std::vector<std::pair<std::string, std::string> > Readings;

	inline void Put(Readings& R, const std::string& Key, const std::string& Value)
	{
		R.push_back(std::make_pair(Key, Value));
	}

	inline std::string LineOf(const MemoryStore& S, int Index)
	{
		if (Index < 0 || Index >= (int)S.Events.size()) return "NO-SUCH-LINE";
		return Escape(S.Events[(std::vector<MemoryEvent>::size_type)Index].ToLine());
	}

	inline bool AlwaysTogether(const std::string&, const std::string&) { return true; }
	inline bool NeverTogether(const std::string&, const std::string&)  { return false; }

	inline void ScenarioMemBasic(Readings& R)
	{
		MemoryStore S("w1");
		S.Append(MemoryEvent(GameTime(1, 12, 0), "observation", 0.6,
		                     "a window on the Parade went in"));
		S.Append(MemoryEvent(GameTime(1, 12, 5), "heard", 0.36096,
		                     "I heard from the shopkeeper that a window went in"));
		// A newline inside the text and space either end of it: the
		// constructor replaces the one and trims the other, and this is the
		// only case that proves it did.
		S.Append(MemoryEvent(GameTime(2, 9, 0), "reflection", 0.125,
		                     "  two lines\nbecome one  "));
		Put(R, "count", FromInt((long long)S.Events.size()));
		Put(R, "day1", FromInt((long long)S.EventsOnDay(1).size()));
		Put(R, "day2", FromInt((long long)S.EventsOnDay(2).size()));
		Put(R, "day3", FromInt((long long)S.EventsOnDay(3).size()));
		Put(R, "line0", LineOf(S, 0));
		Put(R, "line1", LineOf(S, 1));
		Put(R, "line2", LineOf(S, 2));
		Put(R, "markdown", Escape(S.ToMarkdown()));
	}

	inline void ScenarioMemPrune(Readings& R)
	{
		// IMPORTANCES ARE ALL DISTINCT ON PURPOSE. C#'s List.Sort and
		// std::sort are both unstable introsorts, so which of two EQUAL
		// importances gets dropped is engine-defined; with distinct values
		// the answer is a fact about the model rather than about a sort.
		MemoryStore S("w1");
		// 601 appends: the 601st crosses MaxEvents and prunes back to
		// PruneTo, so the count after it is what pins PruneTo. C#'s PruneTo
		// is a PRIVATE const, so the generator on the other side cannot read
		// the number directly and this reading is how the two engines compare
		// it at all.
		for (int Idx = 0; Idx <= 600; ++Idx)
		{
			S.Append(MemoryEvent(GameTime(1, Idx / 60, Idx % 60), "observation",
			                     Idx / 1000.0, "e" + FromInt(Idx)));
		}
		Put(R, "countAfter601", FromInt((long long)S.Events.size()));
		Put(R, "firstImportanceAfter601", FromDouble(S.Events[0].Importance));
		Put(R, "firstTextAfter601", Escape(S.Events[0].Text));
		Put(R, "lastImportanceAfter601", FromDouble(S.Events[S.Events.size() - 1].Importance));
		for (int Idx = 601; Idx <= 700; ++Idx)
		{
			S.Append(MemoryEvent(GameTime(1, Idx / 60, Idx % 60), "observation",
			                     Idx / 1000.0, "e" + FromInt(Idx)));
		}
		Put(R, "countAfter701", FromInt((long long)S.Events.size()));
		Put(R, "firstImportanceAfter701", FromDouble(S.Events[0].Importance));
		Put(R, "lastTextAfter701", Escape(S.Events[S.Events.size() - 1].Text));
		Put(R, "maxEvents", FromInt((long long)(int)MemoryStore::MaxEvents));
	}

	// The crime run's own scenario, built from the ruling's numbers: two
	// strangers on a tie of 0.60, one 0.94 sighting, then a round where they
	// are not together and a round where they are.
	inline void ScenarioGossipCrime(Readings& R)
	{
		std::shared_ptr<SocialGraph> G = std::make_shared<SocialGraph>();
		G->Link("w1", "n2", 0.6);
		GossipMill Mill(G);
		Mill.Add(std::make_shared<Gossiper>("w1", "the shopkeeper",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Mill.Add(std::make_shared<Gossiper>("n2", "the lad in the yard",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));

		const Fact Content("player", "broke_window_d1", "east_parade_glass0");
		const std::string Summary = "a window on the Parade went in, and I would know the face again";
		Mill.Witness("w1", Content, Summary, false, GameTime(1, 12, 0), 0.94);

		Put(R, "tie", FromDouble(Mill.Tie("w1", "n2")));
		Put(R, "offered", FromInt(Mill.WitnessesOffered()));
		Put(R, "dropped", FromInt(Mill.WitnessesDropped()));
		GossiperPtr W1 = Mill.Get("w1");
		GossiperPtr N2 = Mill.Get("n2");
		Put(R, "w1Rumors", FromInt((long long)W1->Rumors.size()));
		Put(R, "w1Conf", FromDouble(W1->Rumors[0]->Confidence));
		Put(R, "w1Hops", FromInt(W1->Rumors[0]->Hops));
		Put(R, "w1Topic", Escape(W1->Rumors[0]->TopicKey()));
		Put(R, "w1Knowledge", FromInt((long long)W1->Knowledge->Facts.size()));
		Put(R, "w1MemCount", FromInt((long long)W1->Memory->Events.size()));
		Put(R, "w1MemLine0", LineOf(*W1->Memory, 0));
		Put(R, "saysPlayer", FromInt(Mill.SummariesSaying("player")));

		const std::vector<GossipEvent> R1 = Mill.Tick(GameTime(1, 12, 1), NeverTogether);
		Put(R, "r1Events", FromInt((long long)R1.size()));
		Put(R, "r1N2Rumors", FromInt((long long)N2->Rumors.size()));

		const std::vector<GossipEvent> R2 = Mill.Tick(GameTime(1, 12, 2), AlwaysTogether);
		Put(R, "r2Events", FromInt((long long)R2.size()));
		Put(R, "r2From", Escape(R2.empty() ? std::string("none") : R2[0].FromId));
		Put(R, "r2To", Escape(R2.empty() ? std::string("none") : R2[0].ToId));
		Put(R, "r2Conf", R2.empty() ? std::string("none") : FromDouble(R2[0].RumorRef->Confidence));
		Put(R, "r2Hops", R2.empty() ? std::string("none") : FromInt(R2[0].RumorRef->Hops));
		Put(R, "r2Contradiction", R2.empty() ? std::string("none") : FromBool(R2[0].Contradiction));
		Put(R, "r2Exposure", R2.empty() ? std::string("none") : FromBool(R2[0].Exposure));
		Put(R, "r2N2Rumors", FromInt((long long)N2->Rumors.size()));
		Put(R, "r2N2MemCount", FromInt((long long)N2->Memory->Events.size()));
		Put(R, "r2N2MemLine0", LineOf(*N2->Memory, 0));
		Put(R, "r2N2Knowledge", FromInt((long long)N2->Knowledge->Facts.size()));

		// The re-tell guard, from both ends: w1 has nothing stronger to add
		// and n2's copy is not worth passing back.
		const std::vector<GossipEvent> R3 = Mill.Tick(GameTime(1, 12, 3), AlwaysTogether);
		Put(R, "r3Events", FromInt((long long)R3.size()));
		Put(R, "r3N2Rumors", FromInt((long long)N2->Rumors.size()));
		Put(R, "r3W1Rumors", FromInt((long long)W1->Rumors.size()));
		Put(R, "r3N2MemCount", FromInt((long long)N2->Memory->Events.size()));

		// Gossiper::Holds and Gossiper::Best, which the mill's own ported
		// lines never call and which are inside the range the ruling named.
		// Holds asks about THIS version of the story, so the second reading
		// names the other window and must be 0.
		Put(R, "n2Holds", FromBool(N2->Holds("player.broke_window_d1", "east_parade_glass0")));
		Put(R, "n2HoldsOther", FromBool(N2->Holds("player.broke_window_d1", "east_parade_glass1")));
		Put(R, "w1BestConf", FromDouble(W1->Best("player.broke_window_d1")->Confidence));
		Put(R, "n2BestConf", FromDouble(N2->Best("player.broke_window_d1")->Confidence));
	}

	inline void ScenarioGossipDropped(Readings& R)
	{
		GossipMill Mill(std::make_shared<SocialGraph>());
		Mill.Witness("ghost", Fact("player", "broke_window_d1", "east_parade_glass0"),
		             "a window went in", false, GameTime(1, 12, 0), 1.0);
		Put(R, "offered", FromInt(Mill.WitnessesOffered()));
		Put(R, "dropped", FromInt(Mill.WitnessesDropped()));
		Put(R, "agents", FromInt((long long)Mill.Agents().size()));
	}

	inline void ScenarioGossipContradiction(Readings& R)
	{
		std::shared_ptr<SocialGraph> G = std::make_shared<SocialGraph>();
		G->Link("w1", "n2", 0.6);
		GossipMill Mill(G);
		Mill.Add(std::make_shared<Gossiper>("w1", "the shopkeeper",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Mill.Add(std::make_shared<Gossiper>("n2", "the lad in the yard",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		// What the player told n2 to his face.
		Mill.Get("n2")->Knowledge->Learn(Fact("player", "location_d2_evening", "home"));
		Mill.Witness("w1", Fact("player", "location_d2_evening", "warehouse"),
		             "he was down at the warehouse", false, GameTime(1, 12, 0), 1.0);
		const std::vector<GossipEvent> Ev = Mill.Tick(GameTime(1, 12, 2), AlwaysTogether);
		Put(R, "events", FromInt((long long)Ev.size()));
		Put(R, "contradiction", Ev.empty() ? std::string("none") : FromBool(Ev[0].Contradiction));
		Put(R, "exposure", Ev.empty() ? std::string("none") : FromBool(Ev[0].Exposure));
		Put(R, "passed", Ev.empty() ? std::string("none") : FromDouble(Ev[0].RumorRef->Confidence));
		GossiperPtr N2 = Mill.Get("n2");
		Put(R, "n2MemCount", FromInt((long long)N2->Memory->Events.size()));
		Put(R, "n2MemLine0", LineOf(*N2->Memory, 0));
		Put(R, "n2MemLine1", LineOf(*N2->Memory, 1));
	}

	inline void ScenarioGossipExposure(Readings& R)
	{
		std::shared_ptr<SocialGraph> G = std::make_shared<SocialGraph>();
		G->Link("w1", "n2", 0.6);
		GossipMill Mill(G);
		Mill.Add(std::make_shared<Gossiper>("w1", "the fence",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "night"));
		Mill.Add(std::make_shared<Gossiper>("n2", "the shopkeeper",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Mill.Witness("w1", Fact("player", "night_business_d1", "the docks"),
		             "he was down the docks after midnight", true, GameTime(1, 12, 0), 1.0);
		const std::vector<GossipEvent> Ev = Mill.Tick(GameTime(1, 12, 2), AlwaysTogether);
		Put(R, "events", FromInt((long long)Ev.size()));
		Put(R, "contradiction", Ev.empty() ? std::string("none") : FromBool(Ev[0].Contradiction));
		Put(R, "exposure", Ev.empty() ? std::string("none") : FromBool(Ev[0].Exposure));
	}

	inline void ScenarioGossipSuppressed(Readings& R)
	{
		std::shared_ptr<SocialGraph> G = std::make_shared<SocialGraph>();
		G->Link("w1", "n2", 0.6);
		GossipMill Mill(G);
		Mill.Add(std::make_shared<Gossiper>("w1", "the shopkeeper",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Mill.Add(std::make_shared<Gossiper>("n2", "the lad in the yard",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Mill.Witness("w1", Fact("player", "broke_window_d1", "east_parade_glass0"),
		             "a window on the Parade went in", false, GameTime(1, 12, 0), 0.94);
		Mill.Get("w1")->Suppressed.push_back("player.broke_window_d1");
		const std::vector<GossipEvent> Ev = Mill.Tick(GameTime(1, 12, 2), AlwaysTogether);
		Put(R, "events", FromInt((long long)Ev.size()));
		Put(R, "n2Rumors", FromInt((long long)Mill.Get("n2")->Rumors.size()));
	}

	inline void ScenarioGossipLeashed(Readings& R)
	{
		// A leash holds everything ABOUT THE PLAYER and nothing else, so the
		// same speaker in the same round passes one rumour and not the other.
		std::shared_ptr<SocialGraph> G = std::make_shared<SocialGraph>();
		G->Link("w1", "n2", 0.6);
		GossipMill Mill(G);
		Mill.Add(std::make_shared<Gossiper>("w1", "the shopkeeper",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Mill.Add(std::make_shared<Gossiper>("n2", "the lad in the yard",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Mill.Witness("w1", Fact("player", "broke_window_d1", "east_parade_glass0"),
		             "a window on the Parade went in", false, GameTime(1, 12, 0), 0.94);
		Mill.Witness("w1", Fact("novak", "owes_money_d1", "forty pounds"),
		             "Novak is into somebody for forty", false, GameTime(1, 12, 0), 0.94);
		Mill.Get("w1")->Leashed = true;
		const std::vector<GossipEvent> Ev = Mill.Tick(GameTime(1, 12, 2), AlwaysTogether);
		Put(R, "events", FromInt((long long)Ev.size()));
		Put(R, "passedSubject", Ev.empty() ? std::string("none") : Escape(Ev[0].RumorRef->Content.Subject));
	}

	inline void ScenarioGossipIndelible(Readings& R)
	{
		// A body arrives at the far end of the street exactly as true as it
		// left, so a tie of 0.1 that would kill any story passes this one.
		std::shared_ptr<SocialGraph> G = std::make_shared<SocialGraph>();
		G->Link("w1", "n2", 0.1);
		GossipMill Mill(G);
		Mill.Add(std::make_shared<Gossiper>("w1", "the shopkeeper",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Mill.Add(std::make_shared<Gossiper>("n2", "the lad in the yard",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Mill.Witness("w1", Fact("player", "killed_d1", "the docker"),
		             "he put the docker down and walked off", false,
		             GameTime(1, 12, 0), 1.0, true);
		const std::vector<GossipEvent> Ev = Mill.Tick(GameTime(1, 12, 2), AlwaysTogether);
		Put(R, "events", FromInt((long long)Ev.size()));
		Put(R, "passed", Ev.empty() ? std::string("none") : FromDouble(Ev[0].RumorRef->Confidence));
		Put(R, "hops", Ev.empty() ? std::string("none") : FromInt(Ev[0].RumorRef->Hops));
		Put(R, "n2Knowledge", FromInt((long long)Mill.Get("n2")->Knowledge->Facts.size()));
	}

	inline void ScenarioGossipIndelibleFloor(Readings& R)
	{
		// THE SUBTLE ONE. An indelible rumour skips the first floor test and
		// then meets the second: passed is its own confidence, and 0.1 is
		// still under MinConfidenceToShare, so a corpse nobody is sure about
		// does not travel either.
		std::shared_ptr<SocialGraph> G = std::make_shared<SocialGraph>();
		G->Link("w1", "n2", 0.9);
		GossipMill Mill(G);
		Mill.Add(std::make_shared<Gossiper>("w1", "the shopkeeper",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Mill.Add(std::make_shared<Gossiper>("n2", "the lad in the yard",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Mill.Witness("w1", Fact("player", "killed_d1", "the docker"),
		             "somebody put the docker down", false, GameTime(1, 12, 0), 0.1, true);
		const std::vector<GossipEvent> Ev = Mill.Tick(GameTime(1, 12, 2), AlwaysTogether);
		Put(R, "events", FromInt((long long)Ev.size()));
		Put(R, "w1Conf", FromDouble(Mill.Get("w1")->Rumors[0]->Confidence));
		Put(R, "w1Indelible", FromBool(Mill.Get("w1")->Rumors[0]->Indelible));
	}

	inline void ScenarioWitnessUpgrade(Readings& R)
	{
		// All four branches of Witness, in order, on one rumour: new, no
		// change, stronger, and the indelible upgrade in place. The memory
		// line is written on every one of the four.
		GossipMill Mill(std::make_shared<SocialGraph>());
		Mill.Add(std::make_shared<Gossiper>("w1", "the shopkeeper",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		const Fact F("player", "broke_window_d1", "east_parade_glass0");
		Mill.Witness("w1", F, "s1", false, GameTime(1, 12, 0), 0.5);
		Mill.Witness("w1", F, "s2", false, GameTime(1, 12, 1), 0.3);
		Mill.Witness("w1", F, "s3", false, GameTime(1, 12, 2), 0.9);
		Mill.Witness("w1", F, "s4", false, GameTime(1, 12, 3), 0.4, true);
		GossiperPtr W1 = Mill.Get("w1");
		Put(R, "rumors", FromInt((long long)W1->Rumors.size()));
		Put(R, "conf", FromDouble(W1->Rumors[0]->Confidence));
		Put(R, "hops", FromInt(W1->Rumors[0]->Hops));
		Put(R, "indelible", FromBool(W1->Rumors[0]->Indelible));
		Put(R, "summary", Escape(W1->Rumors[0]->Summary));
		Put(R, "knowledge", FromInt((long long)W1->Knowledge->Facts.size()));
		Put(R, "memCount", FromInt((long long)W1->Memory->Events.size()));
		// THE DOUBTFUL LINE, which is the string the crime run commits and
		// the one whose em-dash was corrected to a comma in both engines.
		Put(R, "memLine3", LineOf(*W1->Memory, 3));
		Mill.Witness("w1", Fact("player", "seen_d1", "the parade"), "s5",
		             false, GameTime(1, 12, 4), 1.0);
		Put(R, "memLine4", LineOf(*W1->Memory, 4));
		Put(R, "knowledgeAfterCertain", FromInt((long long)W1->Knowledge->Facts.size()));

		// BEST'S ONE SUBTLETY, GIVEN ITS OWN CASE. Two versions of one topic
		// at EQUAL confidence: C#'s OrderByDescending is a stable sort, so
		// the first added wins, and the port's strict > claims to reproduce
		// that without sorting. A port using >= would answer glass1 here.
		Mill.Witness("w1", Fact("player", "tie_d1", "glass0"), "t0", false,
		             GameTime(1, 12, 5), 0.5);
		Mill.Witness("w1", Fact("player", "tie_d1", "glass1"), "t1", false,
		             GameTime(1, 12, 6), 0.5);
		Put(R, "bestValueTie", Escape(W1->Best("player.tie_d1")->Content.Value));
		Put(R, "bestConfTie", FromDouble(W1->Best("player.tie_d1")->Confidence));
	}

	// THE NAMED FIXTURE, CoreTests/Program.cs 16019 to 16103, which the crime
	// ruling names as this port's own proof (section 8 item 3) and which the
	// director's review found no Resolve row reached. Its first claim is that
	// four positions produce FOUR DISTINCT slot sets, and the case it exists
	// for is "act, no actor": the victim falls in the market light at 9 m
	// while the shooter stands in a doorway at 24 m under 0.08 light. That is
	// the reason Sight was split off Vantage at all (Observation.cs 114 to
	// 126), and no other case in the table reaches it.
	//
	// THREE OF THE FIXTURE'S CONSTANTS ARE NOT IN THIS PORT'S SCOPE. The C#
	// deed reads Perception.LoudSuppressed22 (62), the market floor is
	// AmbientMarketNoon (58) and the loud weapon is LoudSnub38 (100); the
	// crime ruling's list ports none of the three, so the values travel as
	// literals here while the generator on the other side reads the real C#
	// constants. If one of them ever moves, these rows go red, which is the
	// right outcome for a number two engines are supposed to share.
	inline Vantage FourAt(const std::string& Id, double M, double Light, double Fam,
	                      bool bOcc = false, bool bMark = false, bool bFace = true,
	                      double Ambient = Perception::AmbientDaytimeStreet,
	                      double Watched = 3.0, bool bLater = false)
	{
		Vantage V = Vantage::Both(Id, M, Light, Fam, Ambient);
		V.ToActor.Occluded = bOcc; V.ToVictim.Occluded = bOcc;
		V.ActorHasMark = bMark; V.FaceToward = bFace;
		V.SecondsWatching = Watched; V.ArrivedLater = bLater;
		return V;
	}

	inline void PutObservation(Readings& R, const std::string& Prefix, const Observation& O)
	{
		Put(R, Prefix + "Slots", FromInt((long long)(int)O.Slots));
		Put(R, Prefix + "Rung", FromInt(O.Rung));
		Put(R, Prefix + "Certainty", FromDouble(O.Certainty));
		Put(R, Prefix + "Label", Escape(O.Label()));
		Put(R, Prefix + "Accused", Escape(O.AccusedId.empty() ? std::string("none") : O.AccusedId));
		Put(R, Prefix + "NamesSomebody", FromBool(O.NamesSomebody()));
	}

	inline void ScenarioObservationFour(Readings& R)
	{
		Deed Dd;
		Dd.EventId = "e1"; Dd.ActorId = "player"; Dd.VictimId = "tony";
		Dd.Loudness = 62.0;            // Perception.LoudSuppressed22, not ported
		Dd.VictimCriesOut = false; Dd.WeaponDrawn = true; Dd.ActorFled = true;
		Dd.LeavesBody = true; Dd.HadPrecursor = true;

		const Observation Close  = Observe::Resolve(Dd, FourAt("close", 4, 1.0, 0.9));
		const Observation Wall   = Observe::Resolve(Dd, FourAt("wall", 6, 1.0, 0.9, true));
		const Observation Later  = Observe::Resolve(Dd, FourAt("later", 1, 1.0, 0.9,
		                                                       false, false, true,
		                                                       Perception::AmbientDaytimeStreet,
		                                                       3.0, true));

		// THE SUPPRESSED-PISTOL CASE. One sightline for "the event" made this
		// unreachable, and a test asserting four different slot sets got
		// three.
		Vantage Across;
		Across.WitnessId = "across";
		Across.ToVictim = Sight::At(9, 1.0);      // he falls, right there, lit
		Across.ToActor  = Sight::At(24, 0.08);    // the shooter, in a doorway
		Across.Familiarity = 0.9;                 // even a friend cannot help here
		Across.AmbientFloor = 58.0;               // Perception.AmbientMarketNoon, not ported
		Across.FaceToward = true; Across.SecondsWatching = 3.0;
		const Observation Far = Observe::Resolve(Dd, Across);

		// The same witness, same relationship, with the shooter under a lamp
		// instead of in a doorway. Light is the whole difference.
		Vantage Lit = Across; Lit.ToActor = Sight::At(24, 1.0);
		const Observation Seen = Observe::Resolve(Dd, Lit);

		// A LOUD weapon through the same wall is a different story, and
		// hearing gives the act without the actor.
		Deed Loud = Dd; Loud.Loudness = 100.0;    // Perception.LoudSnub38, not ported
		const Observation WallLoud = Observe::Resolve(Loud, FourAt("wall", 6, 1.0, 0.9, true));

		// Sight::Blind(), the eye that does not exist (Witnesses.cs 86), which
		// is the shape the crime probe feeds for an out-of-world target.
		Vantage BlindV = FourAt("blindVictim", 4, 1.0, 0.9);
		BlindV.ToVictim = Sight::Blind();
		const Observation BlindObs = Observe::Resolve(Dd, BlindV);

		PutObservation(R, "close", Close);
		PutObservation(R, "wall", Wall);
		PutObservation(R, "later", Later);
		PutObservation(R, "across", Far);
		PutObservation(R, "litShooter", Seen);
		PutObservation(R, "wallLoud", WallLoud);
		PutObservation(R, "blindVictim", BlindObs);

		// CLAIM 1, and the whole reason the fixture exists: four witnesses,
		// four different slot sets. Counted over close, across, wall, later,
		// in that order, exactly as the C# counts it.
		int Sets[4];
		Sets[0] = (int)Close.Slots; Sets[1] = (int)Far.Slots;
		Sets[2] = (int)Wall.Slots;  Sets[3] = (int)Later.Slots;
		int Distinct = 0;
		for (int A = 0; A < 4; ++A)
		{
			bool bSeen = false;
			for (int Bx = 0; Bx < A; ++Bx) { if (Sets[Bx] == Sets[A]) bSeen = true; }
			if (!bSeen) ++Distinct;
		}
		Put(R, "distinctSets", FromInt(Distinct));

		const Sight Blind = Sight::Blind();
		Put(R, "blindMetres", FromDouble(Blind.Metres));
		Put(R, "blindLight", FromDouble(Blind.LightLevel));
		Put(R, "blindOccluded", FromBool(Blind.Occluded));
	}

	inline void ScenarioKnowledge(Readings& R)
	{
		KnowledgeBase K;
		const Fact Home("player", "location_d2_evening", "home");
		const Fact Ware("player", "location_d2_evening", "warehouse");
		Put(R, "empty", FromInt((long long)K.CheckClaim(Home)));
		K.Learn(Home);
		Put(R, "consistent", FromInt((long long)K.CheckClaim(Home)));
		Put(R, "contradiction", FromInt((long long)K.CheckClaim(Ware)));
		K.Learn(Ware);
		Put(R, "countAfterRelearn", FromInt((long long)K.Facts.size()));
		Put(R, "consistentAfterRelearn", FromInt((long long)K.CheckClaim(Ware)));
		K.Learn(Fact("player", "owes_d1", "forty"));
		Put(R, "countAfterSecondTopic", FromInt((long long)K.Facts.size()));
		Put(R, "toString", Escape(Fact("PLAYER", "Location_D2_Evening", "WAREHOUSE").ToString()));
		Put(R, "sameTopic", FromBool(Home.SameTopic(Ware)));
		Put(R, "sameTopicOther", FromBool(Home.SameTopic(Fact("player", "owes_d1", "forty"))));
	}

	inline void ScenarioSummaries(Readings& R)
	{
		// THE LEAK GUARD ON A REAL MILL. Three rumours, and only the two that
		// SAY the word out loud count; the possessive is a leak and the
		// plural is a different word.
		GossipMill Mill(std::make_shared<SocialGraph>());
		Mill.Add(std::make_shared<Gossiper>("w1", "the shopkeeper",
			std::shared_ptr<MemoryStore>(), std::shared_ptr<KnowledgeBase>(), "day"));
		Mill.Witness("w1", Fact("player", "a_d1", "x"),
		             "Mitch says it was player, and came to say so", false, GameTime(1, 12, 0), 1.0);
		Mill.Witness("w1", Fact("player", "b_d1", "x"),
		             "two players were there", false, GameTime(1, 12, 0), 1.0);
		Mill.Witness("w1", Fact("player", "c_d1", "x"),
		             "it was the player's coat", false, GameTime(1, 12, 0), 1.0);
		Put(R, "sayingPlayer", FromInt(Mill.SummariesSaying("player")));
		Put(R, "sayingNovak", FromInt(Mill.SummariesSaying("novak")));
		Put(R, "sayingEmpty", FromInt(Mill.SummariesSaying("")));
		Put(R, "rumors", FromInt((long long)Mill.Get("w1")->Rumors.size()));
	}

	inline Readings Scenario(const std::string& Name)
	{
		Readings R;
		if      (Name == "mem_basic")             ScenarioMemBasic(R);
		else if (Name == "mem_prune")             ScenarioMemPrune(R);
		else if (Name == "gossip_crime")          ScenarioGossipCrime(R);
		else if (Name == "gossip_dropped")        ScenarioGossipDropped(R);
		else if (Name == "gossip_contradiction")  ScenarioGossipContradiction(R);
		else if (Name == "gossip_exposure")       ScenarioGossipExposure(R);
		else if (Name == "gossip_suppressed")     ScenarioGossipSuppressed(R);
		else if (Name == "gossip_leashed")        ScenarioGossipLeashed(R);
		else if (Name == "gossip_indelible")      ScenarioGossipIndelible(R);
		else if (Name == "gossip_indelible_floor")ScenarioGossipIndelibleFloor(R);
		else if (Name == "witness_upgrade")       ScenarioWitnessUpgrade(R);
		else if (Name == "observation_four")      ScenarioObservationFour(R);
		else if (Name == "knowledge")             ScenarioKnowledge(R);
		else if (Name == "summaries")             ScenarioSummaries(R);
		return R;
	}

	inline const char* ScenarioNames(int Index)
	{
		static const char* Names[] = {
			"mem_basic", "mem_prune", "gossip_crime", "gossip_dropped",
			"gossip_contradiction", "gossip_exposure", "gossip_suppressed",
			"gossip_leashed", "gossip_indelible", "gossip_indelible_floor",
			"witness_upgrade", "observation_four", "knowledge", "summaries", 0
		};
		return Names[Index];
	}

	// ---- one row in, one answer out ---------------------------------

	struct Answer
	{
		bool        Known;   // false means this build implements no such row
		std::string Got;     // the port's answer, escaped exactly as the table is
		Answer() : Known(false) {}
	};

	// THE PERCEPTION CONSTANTS, ANSWERED BY NAME. A constant that drifted
	// would otherwise only show up through whichever function happens to
	// read it, and "the radius is wrong" is a much worse bug report than
	// "AudibleDivisor is 8.5 here and 8.0 there".
	inline Answer PerceptionConst(const std::string& Name)
	{
		Answer A;
		A.Known = true;
		if      (Name == "NoticeSeconds")        A.Got = FromDouble(Perception::NoticeSeconds);
		else if (Name == "AmbientNight3am")      A.Got = FromDouble(Perception::AmbientNight3am);
		else if (Name == "AmbientDaytimeStreet") A.Got = FromDouble(Perception::AmbientDaytimeStreet);
		else if (Name == "LoudShout")            A.Got = FromDouble(Perception::LoudShout);
		else if (Name == "LoudBottleSmash")      A.Got = FromDouble(Perception::LoudBottleSmash);
		else if (Name == "WallAttenuation")      A.Got = FromDouble(Perception::WallAttenuation);
		else if (Name == "LoudRemark")           A.Got = FromDouble(Perception::LoudRemark);
		else if (Name == "AudibleBaseMetres")    A.Got = FromDouble(Perception::AudibleBaseMetres);
		else if (Name == "AudibleDivisor")       A.Got = FromDouble(Perception::AudibleDivisor);
		else if (Name == "AudibleCapMetres")     A.Got = FromDouble(Perception::AudibleCapMetres);
		else if (Name == "AlertFloorDrop")       A.Got = FromDouble(Perception::AlertFloorDrop);
		else A.Known = false;
		return A;
	}

	// Resolve's arguments, in the order the table writes them. Named once
	// here and once in Program.cs, and the two lists are the contract.
	//   1 loudness        2 criesOut       3 weaponDrawn   4 actorFled
	//   5 leavesBody      6 hadPrecursor   7 isAccident
	//   8 actorMetres     9 actorOffAxis  10 actorLight   11 actorOccluded
	//  12 victimMetres   13 victimOffAxis 14 victimLight  15 victimOccluded
	//  16 familiarity    17 actorHasMark  18 faceToward   19 ambientFloor
	//  20 alertness      21 secondsWatching  22 rungFloor 23 arrivedLater
	//  24 field          25 expected
	inline Answer ResolveRow(const std::vector<std::string>& F)
	{
		Answer A;
		if (F.size() < 26) return A;
		Deed Dd;
		Dd.EventId = "e1"; Dd.ActorId = "a1"; Dd.VictimId = "v1";
		Dd.Loudness = D(F[1]); Dd.VictimCriesOut = B(F[2]); Dd.WeaponDrawn = B(F[3]);
		Dd.ActorFled = B(F[4]); Dd.LeavesBody = B(F[5]); Dd.HadPrecursor = B(F[6]);
		Dd.IsAccident = B(F[7]);
		Vantage V;
		V.WitnessId = "w1";
		V.ToActor  = Sight::At(D(F[8]),  D(F[10]), D(F[9]),  B(F[11]));
		V.ToVictim = Sight::At(D(F[12]), D(F[14]), D(F[13]), B(F[15]));
		V.Familiarity = D(F[16]); V.ActorHasMark = B(F[17]); V.FaceToward = B(F[18]);
		V.AmbientFloor = D(F[19]); V.Alertness = D(F[20]); V.SecondsWatching = D(F[21]);
		V.RungFloor = I(F[22]); V.ArrivedLater = B(F[23]);

		const Observation O = Observe::Resolve(Dd, V);
		const std::string& Field = F[24];
		A.Known = true;
		if      (Field == "slots")         A.Got = FromInt((long long)(int)O.Slots);
		else if (Field == "rung")          A.Got = FromInt(O.Rung);
		else if (Field == "certainty")     A.Got = FromDouble(O.Certainty);
		else if (Field == "willingness")   A.Got = FromDouble(O.Willingness);
		else if (Field == "label")         A.Got = Escape(O.Label());
		else if (Field == "accused")       A.Got = Escape(O.AccusedId.empty() ? std::string("none") : O.AccusedId);
		else if (Field == "namesSomebody") A.Got = FromBool(O.NamesSomebody());
		// The two fields Resolve never writes, pinned at their defaults so a
		// constructor that stopped setting them would go red. The C# field is
		// Observation.Awareness; see the rename note in Observation.h.
		else if (Field == "awareness")     A.Got = FromInt((long long)O.AwarenessState);
		else if (Field == "retellings")    A.Got = FromInt(O.Retellings);
		else if (Field == "empty")         A.Got = FromBool(O.Empty());
		else if (Field == "witnessId")     A.Got = Escape(O.WitnessId);
		else if (Field == "eventId")       A.Got = Escape(O.EventId);
		else A.Known = false;
		return A;
	}

	inline Answer Evaluate(const std::vector<std::string>& F)
	{
		Answer A;
		if (F.size() < 3) return A;
		const std::string& Fn = F[0];

		// The vision half, ported first and answered here so that ONE
		// dispatcher covers the whole table.
		if (Fn == "MotionFactor" && F.size() >= 3)
		{
			A.Known = true; A.Got = FromDouble(Perception::MotionFactor(D(F[1])));
		}
		else if (Fn == "ConeWeight" && F.size() >= 3)
		{
			A.Known = true; A.Got = FromDouble(Perception::ConeWeight(D(F[1])));
		}
		else if (Fn == "LightFactor" && F.size() >= 3)
		{
			A.Known = true; A.Got = FromDouble(Perception::LightFactor(D(F[1])));
		}
		else if (Fn == "FacingIsReadable" && F.size() >= 4)
		{
			A.Known = true; A.Got = FromBool(Perception::FacingIsReadable(D(F[1]), D(F[2])));
		}
		else if (Fn == "InSight" && F.size() >= 7)
		{
			A.Known = true;
			A.Got = FromBool(Perception::InSight(D(F[1]), D(F[2]), D(F[3]), B(F[4]), D(F[5])));
		}
		else if (Fn == "IdRung" && F.size() >= 7)
		{
			A.Known = true;
			A.Got = FromInt(Perception::IdRung(D(F[1]), D(F[2]), D(F[3]), B(F[4]), B(F[5])));
		}
		else if (Fn == "SymmetryPredictsSeen" && F.size() >= 7)
		{
			A.Known = true;
			A.Got = FromBool(Perception::SymmetryPredictsSeen(D(F[1]), D(F[2]), D(F[3]), D(F[4]), B(F[5])));
		}
		// The hearing half.
		else if (Fn == "PerceptionConst" && F.size() >= 3)
		{
			A = PerceptionConst(F[1]);
		}
		else if (Fn == "AudibleRadius" && F.size() >= 5)
		{
			A.Known = true;
			A.Got = FromDouble(Perception::AudibleRadius(D(F[1]), D(F[2]), B(F[3])));
		}
		else if (Fn == "EffectiveFloor" && F.size() >= 4)
		{
			A.Known = true;
			A.Got = FromDouble(Perception::EffectiveFloor(D(F[1]), D(F[2])));
		}
		else if (Fn == "Heard" && F.size() >= 7)
		{
			A.Known = true;
			A.Got = FromBool(Perception::Heard(D(F[1]), D(F[2]), D(F[3]), B(F[4]), D(F[5])));
		}
		// Observation.
		else if (Fn == "Label" && F.size() >= 3)
		{
			Observation O;
			O.Slots = (Slot)I(F[1]);
			A.Known = true; A.Got = Escape(O.Label());
		}
		else if (Fn == "CertaintyFor" && F.size() >= 6)
		{
			A.Known = true;
			A.Got = FromDouble(Observe::CertaintyFor((Slot)I(F[1]), I(F[2]), B(F[3]), B(F[4])));
		}
		else if (Fn == "Resolve")
		{
			A = ResolveRow(F);
		}
		// GameTime.
		else if (Fn == "GameTime" && F.size() >= 6)
		{
			const GameTime T(I(F[1]), I(F[2]), I(F[3]));
			A.Known = true;
			if      (F[4] == "toString")     A.Got = Escape(T.ToString());
			else if (F[4] == "totalMinutes") A.Got = FromInt(T.TotalMinutes());
			else A.Known = false;
		}
		// MemoryEvent.
		else if (Fn == "MemoryLine" && F.size() >= 8)
		{
			const MemoryEvent E(GameTime(I(F[1]), I(F[2]), I(F[3])), Unescape(F[4]),
			                    D(F[5]), Unescape(F[6]));
			A.Known = true;
			A.Got = Escape(E.ToLine());
		}
		else if (Fn == "TwoDecimals" && F.size() >= 3)
		{
			A.Known = true; A.Got = Escape(FormatTwoDecimals(D(F[1])));
		}
		// Suspicion.
		else if (Fn == "FactNull" && F.size() >= 3)
		{
#if !LEDGER_CORE_EXCEPTIONS
			// COMPILED OUT, NOT SILENTLY PASSED. Provoking the refusal needs
			// a catch, and this module was built without exceptions
			// (Suspicion.h says why and how it got switched on). The four
			// rows then report UNKNOWN, which the done line counts, and the
			// verdict names the reason so an unanswered row cannot read as an
			// answered one. The container build always has exceptions, so the
			// four rows are proved there either way.
			A.Known = false;
			return A;
#else
			// THE REFUSAL, PROVOKED. The C# throws ArgumentNullException with
			// the argument's name; this throws std::invalid_argument with the
			// same name, and the row compares the NAME rather than the type,
			// because the name is the part that was worth keeping.
			const char* S = F[1] == "subject"   ? 0 : "player";
			const char* P = F[1] == "predicate" ? 0 : "broke_window_d1";
			const char* V = F[1] == "value"     ? 0 : "east_parade_glass0";
			A.Known = true;
			try
			{
				const Fact Made(S, P, V);
				A.Got = Escape(Made.ToString());
			}
			catch (const std::invalid_argument& E)
			{
				A.Got = std::string("threw/") + E.what();
			}
#endif
		}
		else if (Fn == "SaysWord" && F.size() >= 4)
		{
			A.Known = true;
			A.Got = FromBool(GossipMill::SaysWord(Unescape(F[1]), Unescape(F[2])));
		}
		else if (Fn == "IsWordChar" && F.size() >= 3)
		{
			const std::string C = Unescape(F[1]);
			A.Known = true;
			A.Got = FromBool(!C.empty() && GossipMill::IsWordChar(C[0]));
		}
		// The stateful ones.
		else if (Fn == "Scenario" && F.size() >= 4)
		{
			const Readings Rd = Scenario(F[1]);
			for (Readings::size_type Ix = 0; Ix < Rd.size(); ++Ix)
			{
				if (Rd[Ix].first == F[2]) { A.Known = true; A.Got = Rd[Ix].second; return A; }
			}
			// A key the scenario does not produce is UNKNOWN rather than
			// wrong: the two answers have different fixes, and a missing key
			// counted as a mismatch would read as a broken model.
			A.Known = false;
		}
		return A;
	}
}
}
