using System;
using System.Globalization;
using System.Text;
using Ledger.Core;

namespace Ledger.PerceptionGolden
{
    /// THE GOLDEN TABLE for the D1 engine probe.
    ///
    /// It emits, from the REAL Core as shipped, the answer this project's C#
    /// gives for a spread of perception inputs. The UE C++ transliteration
    /// reads the same file and must agree to 1e-9.
    ///
    /// WHY A TABLE RATHER THAN PORTING THE TESTS. The C# suite is 130 methods
    /// of NUnit-shaped assertions; porting them would be porting a test
    /// framework, and it would prove the port agrees with a SECOND
    /// transliteration rather than with the original. A table generated by
    /// the original and consumed by the port has one source of truth and no
    /// second implementation of the expectations.
    ///
    /// THE INPUTS ARE CHOSEN TO STRADDLE EVERY BRANCH, not to be tidy: each
    /// threshold in Perception appears with a value just below it, just above
    /// it, and on it, because a transliteration that got a comparison
    /// backwards passes any test that only samples the middle of a range.
    public static class Program
    {
        static readonly CultureInfo Inv = CultureInfo.InvariantCulture;
        static string D(double v) => v.ToString("R", Inv);

        /// WRITES TO A FILE, NOT TO STDOUT, and that is a correction rather
        /// than a preference. The first version printed the table and the
        /// caller redirected stdout, which put a compiler warning from the
        /// BUILD on line 1 of the golden file: an output channel shared with
        /// the toolchain is an output channel the toolchain can pollute. The
        /// consumer would have read `warning CS0414...` as a table row.
        public static int Main(string[] args)
        {
            string path = args != null && args.Length > 0 ? args[0] : "perception-golden.txt";
            var sb = new StringBuilder();
            sb.Append("# perception golden table, emitted from Ledger.Core as shipped\n");
            sb.Append("# fn|args...|expected   -- consumed by ue-probe, agreement to 1e-9\n");

            double[] speeds = { 0.0, 0.05, 0.06, 0.34, 0.35, 1.0, 3.99, 4.0, 4.01, 6.99, 7.0, 9.0 };
            foreach (var s in speeds)
                sb.Append("MotionFactor|").Append(D(s)).Append('|').Append(D(Perception.MotionFactor(s))).Append('\n');

            double[] angles = { 0, 29.9, 30.0, 30.1, 59.9, 60.0, 60.1, 120.0, -45.0, -70.0 };
            foreach (var a in angles)
                sb.Append("ConeWeight|").Append(D(a)).Append('|').Append(D(Perception.ConeWeight(a))).Append('\n');

            double[] lights = { -1.0, 0.0, 0.05, 0.25, 0.5, 0.75, 1.0, 2.0 };
            foreach (var l in lights)
                sb.Append("LightFactor|").Append(D(l)).Append('|').Append(D(Perception.LightFactor(l))).Append('\n');

            foreach (var m in new double[] { 1, 5, 20, 39, 40, 41 })
                foreach (var a in new double[] { 0, 45, 70 })
                    foreach (var l in new double[] { 0.0, 0.5, 1.0 })
                        foreach (var occ in new[] { false, true })
                            foreach (var sp in new double[] { 0.0, 0.34, 4.0 })
                                sb.Append("InSight|").Append(D(m)).Append('|').Append(D(a)).Append('|')
                                  .Append(D(l)).Append('|').Append(occ ? "1" : "0").Append('|').Append(D(sp))
                                  .Append('|').Append(Perception.InSight(m, a, l, occ, sp) ? "1" : "0").Append('\n');

            foreach (var m in new double[] { 1, 7.9, 8, 8.1, 17.9, 18, 24.9, 25, 34.9, 35, 36 })
                foreach (var l in new double[] { 0.0, 0.5, 1.0 })
                    foreach (var f in new double[] { 0.0, 0.34, 0.35, 0.9 })
                        foreach (var mark in new[] { false, true })
                            foreach (var face in new[] { false, true })
                                sb.Append("IdRung|").Append(D(m)).Append('|').Append(D(l)).Append('|').Append(D(f))
                                  .Append('|').Append(mark ? "1" : "0").Append('|').Append(face ? "1" : "0")
                                  .Append('|').Append(Perception.IdRung(m, l, f, mark, face).ToString(Inv)).Append('\n');

            foreach (var m in new double[] { 1, 17.9, 18, 18.1, 30 })
                foreach (var l in new double[] { 0.0, 0.5, 1.0 })
                    sb.Append("FacingIsReadable|").Append(D(m)).Append('|').Append(D(l))
                      .Append('|').Append(Perception.FacingIsReadable(m, l) ? "1" : "0").Append('\n');

            foreach (var m in new double[] { 1, 10, 17.9, 18, 25, 41 })
                foreach (var a in new double[] { 0, 45, 70 })
                    foreach (var ly in new double[] { 0.0, 0.5, 1.0 })
                        foreach (var lt in new double[] { 0.0, 0.5, 1.0 })
                            foreach (var occ in new[] { false, true })
                                sb.Append("SymmetryPredictsSeen|").Append(D(m)).Append('|').Append(D(a)).Append('|')
                                  .Append(D(ly)).Append('|').Append(D(lt)).Append('|').Append(occ ? "1" : "0")
                                  .Append('|').Append(Perception.SymmetryPredictsSeen(m, a, ly, lt, occ) ? "1" : "0").Append('\n');

            var text = sb.ToString();
            System.IO.File.WriteAllText(path, text);
            // The COUNT with its denominator, on stderr so it cannot pollute
            // the table: a golden file that silently emitted nothing would
            // otherwise make the C++ side pass by having nothing to check.
            int rows = 0;
            foreach (var ch in text) if (ch == '\n') rows++;
            Console.Error.WriteLine($"golden rows emitted: {rows - 2} -> {path}");
            return 0;
        }
    }
}
