#!/usr/bin/env python3
"""Every directory of third-party content is named in THIRD-PARTY.md.

WHY THIS EXISTS. The completeness audit on 2026-07-31 found no `LICENSE`, no
credits screen and no attribution file anywhere in the project — while 19 cast
voices are derived from a corpus licensed CC BY 4.0, which REQUIRES attribution.
That is a licence breach waiting on a release, and it survived because nothing
in the plan owned it and nothing in CI looked for it.

A file somebody has to remember to update is a file that goes stale — the same
argument as the reach ledger, and this project has already watched a roadmap's
"STILL OPEN" list rot four days while reading as current. So the check is
mechanical: an asset directory with no entry fails the build.

    python3 tools/attribution-check.py
    python3 tools/attribution-check.py --selftest
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOC = ROOT / "THIRD-PARTY.md"

# Directories that hold content this project did not author, and the token that
# must appear in THIRD-PARTY.md for each. Adding a new one here without adding
# the row is what the check is for.
WATCHED = {
    "ledger/Assets/Characters": "Mixamo",
    "game-design/picked-clips": "VCTK",
    "voice-candidates": "VCTK",
    # THE SYNTHESISED BARKS, AND THEY BELONG HERE RATHER THAN IN `OURS`.
    #
    # We generated them, which makes "ours" the tempting answer and the wrong
    # one: every clip is a voice CLONE of a VCTK speaker, so each is a
    # derivative of a CC BY 4.0 work and carries its parent's obligation.
    # THIRD-PARTY.md said so in advance — "synthesis does not launder the
    # obligation" — and this row is that sentence made mechanical.
    #
    # The distinction `OURS` draws is authorship, not who ran the command. The
    # app icons are ours because nothing outside this repo went into them; the
    # sim stills are ours because the game drew them. A cloned voice fails
    # that test no matter whose GPU produced it.
    "ledger/Assets/Resources/voice/barks": "VCTK",
    "ledger/Assets/StreamingAssets/CityPack": "CityPack",
    # A single file, not a directory — the shipped face sits in `Resources`
    # beside code and prefabs, so there is no folder to name that would not
    # also swallow half the project. The token is the licence, because that is
    # the obligation: the OFL is what THIRD-PARTY.md has to say out loud.
    "ledger/Assets/Resources/LedgerSans.ttf": "SIL Open Font License",
}

# ASSETS THIS PROJECT MADE ITSELF, which need no attribution and must not be
# reported as unaccounted for. The distinction matters: a check that cannot tell
# "third-party, needs a licence row" from "ours, needs nothing" either nags
# about our own files or goes quiet about somebody else's, and both make it
# useless. Anything here is ours; everything else is somebody's.
OURS = {
    "ledger/Assets/Resources/AppIcon": "generated by tools/make-icon.py from the game's own palette",
    # The build's own screenshots of the game's own street. Rendered by the
    # Windows job and committed every run, so they arrive faster than any
    # other asset in the project and are the likeliest thing to trip a check
    # that assumes a new JPEG came from outside.
    "game-design/sim-shots": "rendered by the sim itself and committed by CI every build",
}

# File types that are content rather than code. A directory holding only text
# or json is a manifest, not an asset drop.
ASSET_SUFFIXES = {".fbx", ".png", ".jpg", ".jpeg", ".tga", ".psd", ".wav",
                  ".mp3", ".ogg", ".ttf", ".otf", ".bundle", ".obj", ".blend"}

_fails = []


def check(ok, what, got=""):
    print(("  ok   " if ok else "  FAIL ") + what + ("" if ok else f" — {got}"))
    if not ok:
        _fails.append(what)


def audit(root=None, doc=None):
    root = root or ROOT
    doc = doc if doc is not None else DOC
    text = doc.read_text(encoding="utf-8") if doc.exists() else ""
    check(bool(text), "THIRD-PARTY.md exists", "missing")
    if not text:
        return

    for rel, token in sorted(WATCHED.items()):
        d = root / rel
        if not d.exists():
            # Not yet populated. Not a failure — CityPack does not exist until
            # M17.6 lands — but the row still has to be there waiting for it,
            # so the obligation is recorded before the asset arrives rather
            # than after somebody notices.
            check(token in text,
                  f"{rel} — attribution recorded ahead of the assets", f"no '{token}' in THIRD-PARTY.md")
            continue
        # A WATCHED ENTRY MAY BE A SINGLE FILE, and until 5 August one would
        # have been skipped in silence.
        #
        # `rglob` on a file yields nothing, so `assets` came back empty and the
        # loop moved on WITHOUT checking the token — the entry would sit in the
        # table looking enforced while enforcing nothing. That is the same shape
        # as the check itself never being wired into `verify.py`, one level in.
        #
        # The shipped font is the real case: one `.ttf` in `Resources`, beside
        # code and prefabs, so there is no directory to point at that would not
        # also swallow half the project.
        if d.is_file():
            check(token in text, f"{rel} — the shipped file is attributed",
                  f"no '{token}' in THIRD-PARTY.md")
            continue
        assets = [p for p in d.rglob("*") if p.suffix.lower() in ASSET_SUFFIXES]
        if not assets:
            continue
        check(token in text,
              f"{rel} — {len(assets)} asset file(s) attributed",
              f"no '{token}' in THIRD-PARTY.md")

    # A CC BY corpus needs its exact required wording present, not a paraphrase:
    # "we mention VCTK somewhere" is not what the licence asks for.
    check("CC BY 4.0" in text, "the CC BY licence is named exactly")
    check("Centre for Speech Technology Research" in text,
          "and the attribution text the licence requires is written out")

    # UNTRACKED ASSET DIRECTORIES. The check above only knows what it was told
    # about, which would make it useless the day somebody adds a folder — so
    # this sweeps for asset files anywhere outside a watched directory.
    watched_paths = [root / r for r in WATCHED] + [root / r for r in OURS]
    stray = []
    for p in root.rglob("*"):
        if p.suffix.lower() not in ASSET_SUFFIXES:
            continue
        s = str(p)
        if "/.git/" in s or "/node_modules/" in s or "/.venv" in s:
            continue
        if "/obj/" in s or "/bin/" in s or "/Library/" in s:
            continue
        if any(str(w) in s for w in watched_paths):
            continue
        stray.append(p.relative_to(root))
    check(not stray, "no asset files live outside a directory this file knows about",
          ", ".join(str(x) for x in stray[:5]))

    # And what we made ourselves is recorded as ours, so "no attribution row"
    # is a decision on the record rather than an omission nobody noticed.
    for rel, why in sorted(OURS.items()):
        d = root / rel
        if not d.exists():
            continue
        n = len([p for p in d.rglob("*") if p.suffix.lower() in ASSET_SUFFIXES])
        print(f"  ours  {rel} — {n} file(s), {why}")


def selftest():
    """The check, watched failing. An attribution gate that cannot go red is
    worse than none, because it reads as compliance."""
    import shutil
    import tempfile
    global _fails
    passed = failed = 0

    def expect(name, fn):
        global _fails
        nonlocal passed, failed
        _fails = []
        fn()
        if _fails:
            passed += 1
            print(f"  ok   {name}")
        else:
            failed += 1
            print(f"  FAIL {name} — passed on broken input")

    print("attribution-check selftest\n")
    with tempfile.TemporaryDirectory() as tmp:
        tmp = pathlib.Path(tmp)
        (tmp / "game-design/picked-clips").mkdir(parents=True)
        (tmp / "game-design/picked-clips/lena.p228.mp3").write_bytes(b"x")

        # 1. no attribution file at all
        expect("a missing THIRD-PARTY.md is caught",
               lambda: audit(tmp, tmp / "THIRD-PARTY.md"))

        # 2. a file that does not name the corpus behind assets that are present
        (tmp / "THIRD-PARTY.md").write_text("# nothing in particular\n", encoding="utf-8")
        expect("assets with no attribution row are caught",
               lambda: audit(tmp, tmp / "THIRD-PARTY.md"))

        # 3. names the corpus but not the licence the corpus requires
        (tmp / "THIRD-PARTY.md").write_text(
            "VCTK Mixamo CityPack\n", encoding="utf-8")
        expect("naming the corpus without its licence is caught",
               lambda: audit(tmp, tmp / "THIRD-PARTY.md"))

        # 4. an asset file in a directory nothing knows about
        (tmp / "THIRD-PARTY.md").write_text(
            "VCTK Mixamo CityPack CC BY 4.0 Centre for Speech Technology Research\n",
            encoding="utf-8")
        (tmp / "stray").mkdir()
        (tmp / "stray/mystery.png").write_bytes(b"x")
        expect("an asset in an unknown directory is caught",
               lambda: audit(tmp, tmp / "THIRD-PARTY.md"))

    _fails = []
    print(f"\n{passed}/{passed + failed} checks go red on broken input")
    return 1 if failed else 0


def main():
    if "--selftest" in sys.argv:
        return selftest()
    print("attribution-check — every third-party asset is accounted for\n")
    audit()
    print()
    print("attribution ok" if not _fails else f"{len(_fails)} problem(s)")
    return 1 if _fails else 0


if __name__ == "__main__":
    sys.exit(main())
