#!/usr/bin/env python3
"""THE GLANCE: one phone screen, five things, everything else one tap down.

    python3 tools/glance.py                       # write glance.html at the root
    python3 tools/glance.py --selftest            # accepting case first
    python3 tools/glance.py --now 2026-09-06T09:00Z   # generate at another clock
    python3 tools/glance.py --root <dir> --out <f>    # against a planted tree

WHAT IT IS, AND WHAT IT IS NOT. Jafar, 2026-09-05: "The glance page,
phone-first: overall state as a colour and one dated sentence; needs-you count
and top item; next visible thing and when; the latest image; the budget bar on
both meters. Everything else one tap down." That is the whole specification and
this file holds exactly it. `dashboard.html` and `STATUS.md` keep every
derivation and denominator and are the audit level, one tap down, which is
right for the surfaces agents read. THIS IS NOT A SECOND DASHBOARD. A sixth
block belongs on the audit level; the reason this page can be read in five
seconds is that there are five things on it.

SELF-CONTAINED ON PURPOSE, because queue 097 publishes it to GitHub Pages: one
file, no server, no build step, no remote script, stylesheet, font or image.
The latest frame is embedded as a data URI rather than linked, so the page that
lands on his phone cannot show a broken image or leak a request to anywhere.

THE REPO IS PUBLIC and Jafar ruled that knowingly (decision-queue, RULED
2026-09-05 BY JAFAR: A. Publish as designed). Nothing here reads
`tools/runner/config.local` or any other secret, and the selftest asserts the
generated bytes carry neither that path nor a token-shaped string.

EVERY MISSING READING PRINTS THE WORDS "nothing measured". Never a zero, never
yesterday's value, and the overall colour goes GREY rather than green when any
one of them is missing, because a console that reports green while blind is the
exact fault this page exists to end.
"""
import argparse
import base64
import datetime
import html
import importlib.util
import io
import re
import subprocess
import sys
from pathlib import Path

TOOL = "tools/glance.py"
ROOT = Path(__file__).resolve().parent.parent
OUT_NAME = "glance.html"

# THE FIVE SOURCES, NAMED ONCE. Every number on the page carries the path it
# came from, so this table is what the page quotes rather than a second copy.
SENTENCE_DIR = "production/outbox"       # blocks 1 and 3, one named path
DECISIONS = "production/decision-queue.md"  # block 2
IMAGE_DIRS = ("production/frames", "game-design/sim-shots")  # block 4
BUDGET = "production/budget.md"          # block 5
AUDIT = ()  # dashboard.html and STATUS.md are NOT on the published site yet; a tap into a 404 is withheld, not shipped (ruling 2026-09-05 section 3)

# THE SIBLING PAGE, one tap SIDEWAYS rather than one tap down. Jafar,
# 2026-09-05, verbatim: "It sits beside the glance, not inside it: the glance
# is today, the map is the whole." So it is a LINK and never a sixth block:
# five blocks is the whole specification of this page and the reason it reads
# in five seconds. tools/map.py has linked back here since it was written
# (its SIBLING constant); this is the same link from the other side, and
# without it the map is published and unreachable from the page he opens.
SIBLING = ("map.html", "the map: the whole")

# RULED IN production/queue/096: the sentence goes GREY after 24 hours
# unrefreshed, "because a stale judgement that still looks current is the fault
# this console exists to end". Not a measured threshold and not one to measure:
# it is Jafar's ruling, and it is cited rather than chosen.
STALE_HOURS = 24

# PAGE WEIGHT CAP, DERIVED RATHER THAN PICKED. He opens this on a phone while
# doing something else, so it has to arrive over a weak mobile link in about
# two seconds. A weak but usable link is about 1 Mbit/s, which is 125 000 bytes
# per second, so two seconds is 250 000 bytes. The image is the whole budget in
# practice, so its encode quality is chosen BY this cap below rather than
# guessed. Every run prints the measured weight against it.
PAGE_BYTE_CAP = 250000

# 390 CSS pixels is the logical width of the phones in use (iPhone 12 through
# 15 are all 390 or 393), and queue 096 allows nothing fixed or minimum wider
# than 360. So this file declares NO px width at all: every width is a
# percentage or is left to the flow. The guard below is still exercised on a
# synthetic stylesheet that violates it, because a check that cannot fail is a
# ratchet.
MAX_DECLARED_WIDTH_PX = 360

# The frame is embedded at twice the logical phone width, because these screens
# are 2x or 3x device pixel ratio and a 390-pixel image on a 2x screen is
# visibly soft. 780 is the 2x figure; 3x is not worth the weight on a link
# chosen at 1 Mbit/s.
IMAGE_WIDTH_PX = 780
IMAGE_QUALITIES = (82, 74, 66, 58, 50)


def load_dashboard():
    """The decision queue is parsed by the dashboard's parser, not a second one.

    "What is waiting on Jafar" is one question, and two implementations of it
    would drift the day a section heading changes in that file: the one nobody
    looks at is the one that keeps counting a settled card. So this imports
    `queue_sections` and `card_class` from tools/dashboard/build-dashboard.py,
    which owns the rule that WAITING is the needs-you section and nothing else
    is. The import is by path because the file name carries a hyphen.

    It loads from THIS tool's own repository, never from --root: the parser is
    code shipped beside this file, and a planted fixture tree supplies the data
    being read and not the rules for reading it.
    """
    p = ROOT / "tools" / "dashboard" / "build-dashboard.py"
    spec = importlib.util.spec_from_file_location("build_dashboard", p)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


class Look:
    """One reading and where it came from. There are two states and no third.

    MEASURED carries its fields plus the derivation naming the file it was read
    from. MISSING carries the reason, renders the words "nothing measured", and
    drags the overall colour to GREY. A Look never renders a zero it did not
    measure and never renders a value it read on an earlier run.
    """

    def __init__(self, ok, source, note, **fields):
        self.ok = ok
        self.source = source
        self.note = note
        self.fields = fields

    @classmethod
    def measured(cls, source, note, **fields):
        return cls(True, source, note, **fields)

    @classmethod
    def missing(cls, source, why):
        return cls(False, source, why)

    def get(self, key, default=None):
        return self.fields.get(key, default)


def read_text(path):
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None


def parse_now(s):
    """--now takes ISO 8601 with a Z or an offset; bare text is UTC."""
    t = s.strip().replace("Z", "+00:00")
    d = datetime.datetime.fromisoformat(t)
    if d.tzinfo is None:
        d = d.replace(tzinfo=datetime.timezone.utc)
    return d.astimezone(datetime.timezone.utc)


MD_LINK = re.compile(r"\[([^\]]+)\]\([^)]*\)")


def plain_sentence(s):
    """A Producer headline verbatim, minus its markdown link syntax.

    The outbox format puts the evidence link inside the headline. The link text
    is the sentence and the URL is the evidence, and the evidence lives one tap
    down rather than in the sentence, so the URL is dropped: a remote href in a
    page whose whole claim is zero external references is a fault waiting for a
    reader with no signal. Nothing else about the sentence is edited. It is a
    judgement and it is quoted, including when it says worse than yesterday.
    """
    return MD_LINK.sub(r"\1", s).strip()


DATED_NAME = re.compile(r"^(\d{4})-(\d{2})-(\d{2})-")


def newest_producer_message(root):
    """THE ONE NAMED PATH for the dated sentence: the newest dated file under
    production/outbox, walked recursively.

    WHY THIS PATH AND NOT A NEW ONE. The outbox is already the Producer's
    written record (its README: one file per message the Producer has written),
    it is already gated by tools/producer-check.py before anything is sent, and
    its name already carries the date. A fresh file that only this page reads
    would be a ritual nobody performs, and a sentence nobody writes renders as
    "nothing measured" for ever, which is honest and useless.

    THE DATE IS THE FILENAME'S, READ AT 00:00Z. The file carries no clock, so
    the age computed here is at least the real age and never less: the message
    was written at or after midnight of its own date. A staleness guard whose
    error can only make a sentence look STALER is the right direction of error,
    and it is stated here because the next reader will otherwise assume minutes.
    """
    d = root / SENTENCE_DIR
    if not d.is_dir():
        return None, 0, 0
    files, skipped = [], 0
    for p in sorted(d.rglob("*.md")):
        if p.name == "README.md":
            continue
        m = DATED_NAME.match(p.name)
        if not m:
            skipped += 1
            continue
        files.append((m.group(0)[:-1], p))
    if not files:
        return None, 0, skipped
    files.sort(key=lambda t: (t[0], t[1].name))
    return files[-1], len(files), skipped


FIELD = re.compile(r"^([A-Z][A-Z ]+):\s*(.*)$")


def message_fields(text):
    """The outbox shape is `FIELD: value` at the head of a line, one per
    paragraph. Returns the first occurrence of each field, which is the one the
    Producer wrote; a repeated field in a later paragraph is a quote, not a
    second reading."""
    out = {}
    for line in (text or "").splitlines():
        m = FIELD.match(line.strip())
        if m and m.group(1) not in out:
            out[m.group(1)] = m.group(2).strip()
    return out


def read_sentence(root, now):
    """BLOCK 1: the Producer's dated sentence, and the colour that derives from
    its age. The sentence itself is never derived: it is quoted."""
    hit, total, skipped = newest_producer_message(root)
    denom = "%d dated message(s) under %s, %d undated file(s) skipped" % (
        total, SENTENCE_DIR, skipped)
    if hit is None:
        return Look.missing(SENTENCE_DIR, "no file there carries a "
                            "YYYY-MM-DD name prefix, so no message has a date "
                            "to be judged stale by; %s" % denom)
    date, path = hit
    fields = message_fields(read_text(path))
    head = fields.get("HEADLINE")
    rel = path.relative_to(root).as_posix()
    if not head:
        return Look.missing(rel, "%s carries no HEADLINE line, so the Producer "
                            "has written no sentence to quote (%s)" % (rel, denom))
    written = parse_now(date + "T00:00:00Z")
    age_h = (now - written).total_seconds() / 3600.0
    return Look.measured(
        rel, "the HEADLINE of the newest dated file under %s, dated by its own "
             "filename and read at 00:00Z, so the age is at least this and "
             "never less; %s" % (SENTENCE_DIR, denom),
        sentence=plain_sentence(head), date=date, age_h=age_h,
        stale=age_h > STALE_HOURS, next_line=fields.get("NEXT VISIBLE THING"))


def read_needs_you(root, dash):
    """BLOCK 2: the needs-you count and the top item, from the WAITING section
    of the decision queue. Top means FIRST IN FILE ORDER and the page says so:
    ranking them by class would be this tool making a judgement about what he
    should look at first, which is the Producer's job and not a parser's."""
    path = root / DECISIONS
    text = read_text(path)
    if text is None:
        return Look.missing(DECISIONS, "%s does not exist" % DECISIONS)
    sections = dash.queue_sections(text)
    waiting = sections.get("WAITING", [])
    total = sum(len(c) for c in sections.values())
    classes = [dash.card_class(c) for c in waiting]
    unclassified = sum(1 for k in classes if k is None)
    blocking = sum(1 for k in classes if k == "BLOCKING")
    return Look.measured(
        DECISIONS, "'### ' cards under '## WAITING' in %s, one per card; the "
                   "top item is the first in file order, not a ranking; of %d "
                   "card(s) in the whole file across %d section(s)"
                   % (DECISIONS, total, len(sections)),
        count=len(waiting), examined=total,
        top=dash.plain(waiting[0]["title"]) if waiting else None,
        top_class=classes[0] if waiting else None,
        blocking=blocking, unclassified=unclassified)


WHEN_TOKEN = re.compile(r"\b(\d{4}-\d{2}-\d{2}(?:[T ]\d{2}:\d{2}Z?)?)\b")


def read_next(root, sentence):
    """BLOCK 3: the next visible thing and when, or the word unknown.

    Same named path as block 1, the NEXT VISIBLE THING line of the newest
    Producer message. THE WHEN IS NEVER PADDED: a date is printed only if the
    Producer wrote one in that line. "Soon", "shortly" and "after the next run"
    are not times, and a guessed one is how a console starts lying quietly.
    """
    if not sentence.ok:
        return Look.missing(SENTENCE_DIR, sentence.note)
    line = sentence.get("next_line")
    if not line:
        return Look.missing(sentence.source, "%s carries no NEXT VISIBLE THING "
                            "line" % sentence.source)
    m = WHEN_TOKEN.search(line)
    return Look.measured(
        sentence.source, "the NEXT VISIBLE THING line of %s; the time is "
                         "printed only when that line names one, and is the "
                         "word unknown otherwise" % sentence.source,
        what=plain_sentence(line), when=m.group(1) if m else None)


IMAGE_SUFFIXES = (".jpg", ".jpeg", ".png")


def git(root, *args):
    try:
        p = subprocess.run(["git", "-C", str(root), *args],
                           capture_output=True, text=True, timeout=30)
    except (OSError, subprocess.SubprocessError):
        return ""
    return p.stdout.strip() if p.returncode == 0 else ""


def measuring_run(root, sha):
    """Did the run that committed this frame actually measure anything?

    The same rule tools/report-frame.py applies, and for the same incident: on
    4 August a build whose sim never ran still committed six stills under its
    own sha. The verdict for the run is the evidence; the commit subject is a
    claim. A frame from a run that measured nothing is not the latest picture
    of anything.

    THE VERDICT IS KEYED BY THE RUN, NOT BY THE COMMIT. The stills are pushed
    by a job whose commit subject is "Sim stills from <run sha>", and
    game-design/sim-shots/runs/ is keyed by that run sha, so asking about the
    commit's own sha finds nothing and would blank this block on a repository
    holding 362 verdicts. report-frame.py has carried this same stamp rule
    since it was written; it is copied here rather than shared because that
    tool is a command-line answer and this is a page, and both were read.
    """
    subject = git(root, "log", "-1", "--format=%s", sha)
    stamp = subject.split()[-1] if subject.startswith("Sim stills from") \
        else sha[:7]
    f = root / "game-design" / "sim-shots" / "runs" / ("%s.txt" % stamp[:7])
    body = read_text(f)
    if body is None:
        return False, stamp
    return "NO PLAYER LOG" not in body, stamp


# WHICH FRAME, WHEN ONE COMMIT CARRIES TWENTY, AND THE ORDER IS NOT MINE. A
# build commits every still it rendered in one commit, so "the newest commit"
# picks a date and not a picture. tools/report-frame.py already owns the
# question "which picture goes with the update": its default is day one at
# noon, its flag is the night pair, and the frames it will name at all are the
# three prefixes below. That order is reused here rather than reinvented.
#
# THIS WAS FOUND BY OPENING THE PAGE, NOT BY READING THE GATE. Sorted by path,
# the first file in the newest commit is clips.jpg, a contact sheet of 200-odd
# animation thumbnails, and it embedded cleanly at 84 per cent of the weight
# cap with every check green. On a 390 point screen it is a grey smear. A frame
# with no recognised prefix is now last, and it is offered only when the commit
# holds nothing else.
FRAME_ORDER = ("review_day1_noon", "review_day1_night")
FRAME_PREFIXES = ("review_", "hunt_", "district_")


def choose_frame(paths):
    """One frame out of the commit's set, by report-frame.py's order. Returns
    the pick and the sentence naming which rule chose it, because a tie-break
    nobody can read is a tie-break nobody can correct."""
    for want in FRAME_ORDER:
        for p in paths:
            if p.stem == want:
                return p, ("%s was chosen by tools/report-frame.py's default "
                           "order" % p.name)
    stills = sorted(p for p in paths if p.name.startswith(FRAME_PREFIXES))
    if stills:
        return stills[0], ("%s is the first of %d frame(s) carrying a "
                           "report-frame.py prefix" % (stills[0].name, len(stills)))
    first = sorted(paths)[0]
    return first, ("%s was taken by path order because no frame in that commit "
                   "carries a %s prefix" % (first.name, "/".join(FRAME_PREFIXES)))


def newest_image(root):
    """The latest image, by COMMIT time where git knows and by file time where
    it does not, and the page says which rule chose the file.

    Commit time is the right key in a checkout: every file's mtime is the time
    the clone was made, so an mtime sort would pick whatever the filesystem
    happened to write last. A tree with no git history (a planted fixture, or a
    frame rendered and not yet committed) falls back to mtime, named as such.
    """
    dirs = [d for d in IMAGE_DIRS if (root / d).is_dir()]
    if not dirs:
        return None, "none of %s exists" % ", ".join(IMAGE_DIRS), 0
    on_disk = [p for d in dirs for p in sorted((root / d).rglob("*"))
               if p.suffix.lower() in IMAGE_SUFFIXES]
    if not on_disk:
        return None, "no %s file under %s" % ("/".join(IMAGE_SUFFIXES),
                                              " or ".join(dirs)), 0
    log = git(root, "log", "--format=commit %H", "--name-only", "-60", "--", *dirs)
    commits, sha, seen = [], None, 0
    for line in log.splitlines():
        if line.startswith("commit "):
            sha = line.split()[1]
            commits.append((sha, []))
            continue
        if commits and line.strip() and Path(line).suffix.lower() in IMAGE_SUFFIXES:
            p = root / line.strip()
            seen += 1
            if p.exists():
                commits[-1][1].append(p)
    for sha, paths in commits:
        if not paths:
            continue
        ran, stamp = measuring_run(root, sha)
        if not ran:
            continue
        pick, rule = choose_frame(paths)
        return pick, ("newest committed frame under %s whose run verdict "
                      "game-design/sim-shots/runs/%s.txt says the sim measured "
                      "something; that commit carries %d frame(s) and %s; of "
                      "%d committed image path(s) walked over %d commit(s)"
                      % (" or ".join(dirs), stamp[:7], len(paths), rule, seen,
                         len(commits))), len(on_disk)
    if seen:
        return None, ("no commit among the %d touching %s came from a run "
                      "that measured anything, so no frame is offered: a "
                      "still from a build that rendered nothing is not the "
                      "latest picture of anything"
                      % (len(commits), " or ".join(dirs))), len(on_disk)
    newest = max(on_disk, key=lambda p: p.stat().st_mtime)
    return newest, ("newest file by modification time under %s, because git "
                    "has no history for those paths in this tree; of %d image "
                    "file(s) found" % (" or ".join(dirs), len(on_disk))), len(on_disk)


def encode_image(path, budget):
    """Embed the frame as a data URI, at the largest quality that fits.

    THE QUALITY IS NOT A GUESS: the loop takes the first encode whose base64
    length fits the weight left over after the page shell, so the number that
    governs is the measured byte budget above and not a taste setting. The
    encoded size is printed every run.
    """
    try:
        from PIL import Image
    except ImportError:
        raw = path.read_bytes()
        b64 = base64.b64encode(raw).decode("ascii")
        return (b64, "image/jpeg", len(b64), "Pillow is not installed, so the "
                "frame is embedded unresized", None)
    with Image.open(path) as im:
        im = im.convert("RGB")
        w, h = im.size
        if w > IMAGE_WIDTH_PX:
            im = im.resize((IMAGE_WIDTH_PX, max(1, round(h * IMAGE_WIDTH_PX / w))),
                           Image.LANCZOS)
        out, used = None, None
        for q in IMAGE_QUALITIES:
            buf = io.BytesIO()
            im.save(buf, "JPEG", quality=q, optimize=True)
            b64 = base64.b64encode(buf.getvalue()).decode("ascii")
            out, used = b64, q
            if len(b64) <= budget:
                break
    return (out, "image/jpeg", len(out),
            "%d by %d source, resized to %d wide for a 2x phone screen and "
            "encoded at JPEG quality %d, the first that fits the %d byte "
            "budget left by the page shell" % (w, h, min(w, IMAGE_WIDTH_PX),
                                               used, budget), used)


def read_image(root, budget):
    """BLOCK 4: the latest image, embedded. If there is none, the block says
    the words "nothing measured" rather than showing a broken image, which on a
    phone is indistinguishable from a page that failed to load."""
    path, why, denom = newest_image(root)
    if path is None:
        return Look.missing(" or ".join(IMAGE_DIRS), why)
    rel = path.relative_to(root).as_posix()
    try:
        b64, mime, n, how, _q = encode_image(path, budget)
    except OSError as e:
        return Look.missing(rel, "%s could not be read or decoded: %s" % (rel, e))
    return Look.measured(rel, "%s; %s" % (why, how), b64=b64, mime=mime, bytes=n,
                         examined=denom)


CEILING = re.compile(r"Ceiling for LEDGER:\s*(\d+)\s*%")
PERCENT = re.compile(r"(\d+)\s*%")
HOURS_TO_RESET = re.compile(r"([\d.]+)\s*hours to the")


def meter(cell):
    """One meter cell: a percentage, or None for not read. A cell that says
    `not read` is a true statement about what was measured and never a zero,
    and it is never filled in from the other meter: on 2026-09-01 Fable led the
    total by seven and on 2026-09-04 the total led Fable by one, so there is no
    rule of thumb to infer one from the other."""
    t = cell.strip().lower()
    if not t or "not read" in t or "no percentage" in t:
        return None
    m = PERCENT.search(t)
    return int(m.group(1)) if m else None


def read_budget(root):
    """BLOCK 5: both meters against the ceiling, the governing one marked, and
    hours to reset.

    THE NEWEST ROW IS NOT ALWAYS A READING. production/budget.md carries rows
    for limit EVENTS, which it says in its own words must never be counted as
    readings because they carry no percentage on either meter. So this takes
    the newest row that carries a percentage on at least one meter, and prints
    how many newer rows were skipped for carrying none.

    THE DASHBOARD READS THIS FILE TOO, AND DIFFERENTLY, so the two are named
    to each other rather than left to drift apart unnoticed. read_budget in
    tools/dashboard/build-dashboard.py takes the LAST table row and the TOTAL
    column alone, which is why STATUS.md today prints "weekly Claude usage:
    not read used at 2026-09-05": it is quoting the limit-event row's own
    words as a value, and it never mentions the Fable meter that the
    2026-09-03 two-meter ruling made governing. That is a queue item against
    the dashboard and not something this page quietly patches, but a reader
    comparing the two surfaces has to be told they disagree on purpose.
    """
    path = root / BUDGET
    text = read_text(path)
    if text is None:
        return Look.missing(BUDGET, "%s does not exist" % BUDGET)
    rows = []
    for line in text.splitlines():
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 5 or cells[0].lower() == "when" or set(cells[0]) <= set("-: "):
            continue
        rows.append(cells)
    reading, skipped = None, 0
    for cells in reversed(rows):
        if meter(cells[2]) is not None or meter(cells[3]) is not None:
            reading = cells
            break
        skipped += 1
    if reading is None:
        return Look.missing(BUDGET, "none of the %d table row(s) in %s carries "
                            "a percentage on either meter" % (len(rows), BUDGET))
    cap = CEILING.search(text)
    if not cap:
        return Look.missing(BUDGET, "%s carries no 'Ceiling for LEDGER: N%%' "
                            "line, so points to ceiling cannot be computed"
                            % BUDGET)
    ceiling = int(cap.group(1))
    total, fable = meter(reading[2]), meter(reading[3])
    govern = "total" if (fable is None or (total is not None and total >= fable)) \
        else "fable"
    hrs = HOURS_TO_RESET.search(reading[4])
    return Look.measured(
        BUDGET, "the newest row in %s carrying a percentage on either meter, "
                "of %d row(s) read, %d newer row(s) skipped for carrying none "
                "on either; the ceiling is that file's own '%d%%'; hours to "
                "reset is printed only when the row's note states it"
                % (BUDGET, len(rows), skipped, ceiling),
        when=reading[0], total=total, fable=fable, ceiling=ceiling,
        govern=govern, hours=float(hrs.group(1)) if hrs else None,
        rows=len(rows), skipped=skipped)


# THE COLOUR, DERIVED FROM NAMED INPUTS AND NOTHING ELSE. No threshold here was
# picked by this tool: GREY is queue 096's staleness ruling plus the standing
# rule that a missing reading is never a green one; RED is budget.md's own rule
# that LEDGER STOPS at the ceiling; AMBER is interrupt-classes.md, where
# BLOCKING means the studio has stopped or is about to do something
# irreversible, and where a card with no CLASS is reported as unclassified by
# every reader rather than routed by default.
def derive_colour(looks):
    sentence, needs, nxt, image, budget = looks
    blind = [name for name, look in
             (("state", sentence), ("needs-you", needs), ("next", nxt),
              ("image", image), ("budget", budget)) if not look.ok]
    if blind:
        return "GREY", ("%d of 5 readings could not be taken (%s), and a "
                        "console that reports green while blind is the fault "
                        "this page exists to end"
                        % (len(blind), ", ".join(blind)))
    if sentence.get("stale"):
        return "GREY", ("the sentence is %.0f hours old against the %d hour "
                        "rule in production/queue/096" %
                        (sentence.get("age_h"), STALE_HOURS))
    gov = budget.get(budget.get("govern"))
    if gov is not None and gov >= budget.get("ceiling"):
        return "RED", ("the governing %s meter is at %d%% against the %d%% "
                       "ceiling in production/budget.md, whose rule is that "
                       "LEDGER stops" % (budget.get("govern"), gov,
                                         budget.get("ceiling")))
    if needs.get("blocking"):
        return "AMBER", ("%d waiting card(s) are CLASS: BLOCKING, which "
                         "production/interrupt-classes.md defines as the "
                         "studio stopped or about to do something irreversible"
                         % needs.get("blocking"))
    if needs.get("unclassified"):
        return "AMBER", ("%d waiting card(s) carry no CLASS line and are "
                         "UNCLASSIFIED, never routed by default"
                         % needs.get("unclassified"))
    return "GREEN", ("all five readings taken, the sentence is %.0f hours old "
                     "against the %d hour rule, and the governing %s meter is "
                     "%d%% against a %d%% ceiling"
                     % (sentence.get("age_h"), STALE_HOURS,
                        budget.get("govern"), gov, budget.get("ceiling")))


BAR = {"GREY": "#6d6d6d", "GREEN": "#1c6b33", "AMBER": "#9a5b00", "RED": "#a01717"}

# The colour is printed as a WORD as well as painted, because a page whose only
# state is a hue is unreadable to a colour-blind reader and to anyone glancing
# at it in sunlight, which is the exact situation this page is for.
CSS = """
:root { color-scheme: light dark; }
* { box-sizing: border-box; }
body { margin: 0; padding: 0.9rem 0.8rem 2rem; background: #14161a; color: #e9e9ea;
  font: 17px/1.45 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }
h1 { font-size: 0.78rem; letter-spacing: 0.12em; text-transform: uppercase;
  color: #9aa0a8; margin: 0 0 0.7rem; font-weight: 600; }
.block { background: #1d2026; border-radius: 12px; padding: 0.85rem 0.9rem;
  margin: 0 0 0.7rem; }
.label { font-size: 0.72rem; letter-spacing: 0.1em; text-transform: uppercase;
  color: #9aa0a8; margin: 0 0 0.35rem; }
.state { border-left: 10px solid #6d6d6d; }
.word { font-size: 1.5rem; font-weight: 700; letter-spacing: 0.04em; margin: 0; }
.big { font-size: 1.15rem; font-weight: 600; margin: 0.25rem 0 0; }
.huge { font-size: 2.6rem; font-weight: 700; line-height: 1; margin: 0; }
.say { font-size: 1.05rem; margin: 0.3rem 0 0; }
.missing { font-size: 1.05rem; font-weight: 600; color: #c8b26a; margin: 0.2rem 0 0; }
.frame { display: block; width: 100%; height: auto; border-radius: 8px;
  margin-top: 0.4rem; }
.meter { margin-top: 0.6rem; }
.meter .top { display: flex; justify-content: space-between; font-size: 0.95rem; }
.track { position: relative; height: 16px; background: #2b2f37; border-radius: 8px;
  margin-top: 0.2rem; overflow: hidden; }
.fill { height: 100%; border-radius: 8px; }
.tick { position: absolute; top: 0; bottom: 0; width: 2px; background: #e9e9ea; }
.govern { color: #e9e9ea; font-weight: 700; }
.why { font-size: 0.78rem; color: #8b9198; margin: 0.45rem 0 0; }
.src { font-size: 0.72rem; color: #767c84; margin: 0.35rem 0 0; word-break: break-word; }
details { margin-top: 0.2rem; }
summary { font-size: 0.72rem; color: #767c84; cursor: pointer; }
.tap { margin: 1.1rem 0 0; font-size: 0.95rem; }
.tap a { color: #7fb2ff; text-decoration: none; margin-right: 1.1rem; }
.foot { font-size: 0.72rem; color: #767c84; margin-top: 1rem; }
"""


def esc(s):
    return html.escape(str(s), quote=True)


def missing_p(look):
    """The one string a missing reading is allowed to render.

    It still NAMES THE PLACE IT LOOKED, because "nothing measured" without a
    path is the same dead end as a zero: a reader cannot tell a source that is
    empty from a source this tool never opened.
    """
    return ('<p class="missing">nothing measured</p>\n'
            '<p class="src">from %s. %s</p>' % (esc(look.source), esc(look.note)))


def source_line(look):
    return '<p class="src">from %s</p>' % esc(look.source)


def why_details(text):
    """The derivation is one tap down even inside a block: constitution law 12
    puts the evidence behind the sentence for Jafar and beside it for agents,
    and a <details> is both without a second page."""
    return ('<details><summary>how this number was read</summary>'
            '<p class="why">%s</p></details>' % esc(text))


def block(n, label, body, extra=""):
    return ('<section class="block%s" data-block="%d">\n<p class="label">%s</p>\n'
            '%s\n</section>' % (extra, n, esc(label), body))


def render_state(look, colour, why):
    if not look.ok:
        body = ('<p class="word">%s</p>\n%s' % (esc(colour), missing_p(look)))
    else:
        body = ('<p class="word">%s</p>\n<p class="say">%s</p>\n'
                '<p class="src">%s, %s hours old, from %s</p>\n%s'
                % (esc(colour), esc(look.get("sentence")), esc(look.get("date")),
                   esc("%.0f" % look.get("age_h")), esc(look.source),
                   why_details(look.note)))
    body += '\n<p class="why">%s</p>' % esc(why)
    return ('<section class="block state" data-block="1" '
            'style="border-left-color: %s">\n<p class="label">%s</p>\n%s\n</section>'
            % (BAR[colour], esc("state"), body))


def render_needs(look):
    if not look.ok:
        return block(2, "needs you", missing_p(look))
    n = look.get("count")
    top = look.get("top")
    if n == 0:
        body = ('<p class="huge">0</p>\n<p class="big">nothing is waiting on '
                'you</p>\n<p class="src">of %d card(s) in %s</p>\n%s'
                % (look.get("examined"), esc(DECISIONS), why_details(look.note)))
    else:
        cls = look.get("top_class") or "UNCLASSIFIED"
        body = ('<p class="huge">%d</p>\n<p class="big">%s</p>\n'
                '<p class="src">top item, %s, of %d card(s) in %s</p>\n%s'
                % (n, esc(top), esc(cls), look.get("examined"), esc(DECISIONS),
                   why_details(look.note)))
    return block(2, "needs you", body)


def render_next(look):
    if not look.ok:
        return block(3, "next visible thing", missing_p(look))
    when = look.get("when") or "unknown"
    body = ('<p class="big">%s</p>\n<p class="say">when: %s</p>\n%s\n%s'
            % (esc(look.get("what")), esc(when), source_line(look),
               why_details(look.note)))
    return block(3, "next visible thing", body)


def render_image(look):
    if not look.ok:
        return block(4, "latest image", missing_p(look))
    body = ('<img class="frame" alt="the latest frame this studio rendered, %s" '
            'src="data:%s;base64,%s">\n<p class="src">%s, %d bytes embedded</p>'
            '\n%s' % (esc(look.source), look.get("mime"), look.get("b64"),
                      esc(look.source), look.get("bytes"),
                      why_details(look.note)))
    return block(4, "latest image", body)


def render_meter(name, value, ceiling, governs):
    """One meter bar. A meter that was not read draws NO bar: an empty track
    reads as zero at a glance, and zero is the one thing an unread meter is
    not."""
    mark = ' <span class="govern">governs</span>' if governs else ""
    if value is None:
        return ('<div class="meter"><div class="top"><span>%s</span>'
                '<span>not read</span></div></div>' % esc(name))
    left = ceiling - value
    return ('<div class="meter"><div class="top"><span>%s%s</span>'
            '<span>%d%% used, %d to the %d%% ceiling</span></div>'
            '<div class="track"><div class="fill" style="width: %d%%; '
            'background: %s"></div><div class="tick" style="left: %d%%"></div>'
            '</div></div>'
            % (esc(name), mark, value, left, ceiling, min(value, 100),
               BAR["RED"] if value >= ceiling else BAR["GREEN"], min(ceiling, 100)))


def render_budget(look):
    if not look.ok:
        return block(5, "budget", missing_p(look))
    ceiling = look.get("ceiling")
    hours = look.get("hours")
    body = (render_meter("total", look.get("total"), ceiling,
                         look.get("govern") == "total")
            + "\n" + render_meter("fable", look.get("fable"), ceiling,
                                  look.get("govern") == "fable")
            + '\n<p class="src">read %s. Hours to reset: %s</p>\n%s'
            % (esc(look.get("when")),
               esc("%.0f" % hours) if hours is not None else "unknown",
               why_details(look.note)))
    return block(5, "budget", body)


PAGE = """<!DOCTYPE html>
<html lang="en-GB">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="dark light">
<title>LEDGER: the glance</title>
<style>%s</style>
</head>
<body>
<h1>LEDGER</h1>
%s
<p class="tap">%s</p>
<p class="foot">%s</p>
</body>
</html>
"""


def build(root, now, image_budget=None):
    """The whole page, and the model behind it, from repo state."""
    dash = load_dashboard()
    sentence = read_sentence(root, now)
    needs = read_needs_you(root, dash)
    nxt = read_next(root, sentence)
    budget = read_budget(root)
    # The image is encoded last because its quality is chosen against the
    # weight the rest of the page did not use.
    shell = len(PAGE % (CSS, "", "", "")) + 4000
    image = read_image(root, image_budget if image_budget is not None
                       else PAGE_BYTE_CAP - shell)
    looks = (sentence, needs, nxt, image, budget)
    colour, why = derive_colour(looks)
    blocks = "\n".join([render_state(sentence, colour, why), render_needs(needs),
                        render_next(nxt), render_image(image),
                        render_budget(budget)])
    # The sibling first, because it is the page beside this one; the audit
    # level after it. Both are relative names in the same published directory.
    taps = " ".join(['<a href="%s">%s</a>' % (esc(SIBLING[0]), esc(SIBLING[1]))]
                    + ['<a href="%s">%s</a>' % (esc(a), esc(a)) for a in AUDIT])
    foot = ("Generated by %s at %s. Beside this page: %s, every system as a "
            "tile. The audit level, dashboard.html and STATUS.md with every "
            "derivation and denominator, is in the repository and not yet "
            "one tap down."
            % (TOOL, now.strftime("%Y-%m-%d %H:%M UTC"), SIBLING[0]))
    page = PAGE % (CSS, blocks, taps, esc(foot))
    return page, {"colour": colour, "why": why, "looks": looks}


# ---------------------------------------------------------------------------
# THE FILE CHECKS. The container has no browser, so phone-first is checked on
# the things a FILE can be asked, and then somebody opens it. Each check
# returns (name, ok, printed) and every one of them ships its denominator.
# ---------------------------------------------------------------------------

WIDTH_DECL = re.compile(r"(?:^|[^-\w])((?:min-)?width)\s*:\s*([\d.]+)px", re.I)
REMOTE = re.compile(r"""(?:src|href|action|data|poster)\s*=\s*["']?\s*
                        (https?:|//|ftp:)""", re.I | re.X)
ATTR = re.compile(r"(?:src|href|action|poster)\s*=", re.I)


def check_width(page):
    """Largest fixed or minimum width declared, in CSS px. max-width is not
    counted: it caps a line length and cannot force a horizontal scroll, which
    is the thing 360 exists to prevent."""
    hits = [(m.group(1), float(m.group(2))) for m in WIDTH_DECL.finditer(page)]
    worst = max([v for _, v in hits], default=0.0)
    return ("maxDeclaredWidthPx", worst <= MAX_DECLARED_WIDTH_PX,
            "maxDeclaredWidthPx=%g/%d cap of %d width-or-min-width px "
            "declaration(s)" % (worst, MAX_DECLARED_WIDTH_PX, len(hits)))


def check_external(page):
    hits = REMOTE.findall(page)
    attrs = len(ATTR.findall(page))
    return ("externalRefs", not hits,
            "externalRefs=%d/%d src-or-href attribute(s) examined%s"
            % (len(hits), attrs, "" if not hits else " (" + ",".join(hits) + ")"))


def check_blocks(page):
    n = len(re.findall(r'data-block="\d+"', page))
    return ("blocks", n == 5, "blocks=%d/5 ruled" % n)


def check_weight(page):
    n = len(page.encode("utf-8"))
    return ("pageBytes", n <= PAGE_BYTE_CAP,
            "pageBytes=%d/%d cap (%.0f%% of it)" % (n, PAGE_BYTE_CAP,
                                                    100.0 * n / PAGE_BYTE_CAP))


def check_viewport(page):
    ok = 'name="viewport" content="width=device-width, initial-scale=1"' in page
    return ("viewport", ok, "viewport=%s" % ("device-width" if ok else "MISSING"))


def check_formatting(page):
    """The formatting law, checked on the RENDERED bytes rather than on this
    file: the sentence is quoted from a source this tool does not own, so an
    em-dash can arrive from production/outbox without anyone editing code
    here. The page never silently rewrites a judgement, so it fails loudly
    instead and names what to fix."""
    ems = page.count("—") + page.count("–")
    ital = len(re.findall(r"<em\b|<i\b|font-style\s*:\s*italic", page, re.I))
    return ("formatting", ems == 0 and ital == 0,
            "emDashes=%d italics=%d/%d chars examined" % (ems, ital, len(page)))


def check_secrets(page):
    """The repo is public and Jafar ruled that knowingly, so this is not a
    secrecy check. It is the one line that stops a future source file from
    dragging a token onto a world-readable page."""
    bad = [w for w in ("config.local", "TELEGRAM_TOKEN", "BEGIN PRIVATE KEY")
           if w in page]
    tokenish = re.findall(r"\b\d{8,}:[A-Za-z0-9_-]{30,}\b", page)
    return ("secrets", not bad and not tokenish,
            "secretMarkers=%d/3 examined tokenShaped=%d"
            % (len(bad), len(tokenish)))


def check_map_link(page):
    """THE FORWARD LINK, COUNTED RATHER THAN ASSUMED. Exactly one href to the
    sibling, and it is a link and not an embed: a second copy of the map inside
    this page would be the sixth block the specification forbids. The count is
    printed with its denominator so a page that grew a second one, or lost the
    only one, is not read as fine."""
    n = len(re.findall(r'href="%s"' % re.escape(SIBLING[0]), page))
    return ("mapLink", n == 1, "mapLink=%d/1 href(s)-to-%s label=%s"
            % (n, SIBLING[0], SIBLING[1].replace(" ", "-")))


CHECKS = (check_blocks, check_viewport, check_width, check_external,
          check_weight, check_formatting, check_secrets, check_map_link)


def run_checks(page):
    return [f(page) for f in CHECKS]


# ---------------------------------------------------------------------------
# SELFTEST, ACCEPTING CASE FIRST. The accepting side is the one that goes
# unrun, so it is first here and it is run against the live checkout, which is
# the only fixture that can go stale under us. The rejecting fixtures are
# synthetic, so doing the work this page asks for can never break the tool.
# ---------------------------------------------------------------------------

FIXTURE_SENTENCE = """HEADLINE: The street renders and the sun reached the light.

WHAT CHANGED: Four frames landed.

NEXT VISIBLE THING: four Unreal frames, not flat grey, on 2026-09-06.

BUDGET: seven points.
"""

FIXTURE_QUEUE = """# q

## WAITING

### Should the lamps be sodium or mercury?
CLASS: DECISION
one line of body.

## RULED THIS WEEK

### RULED 2026-09-05: yes
body.
"""

FIXTURE_BUDGET = """# Budget

| when | hours into week | total used | fable used | note |
|---|---|---|---|---|
| 2026-09-04 | 53 of 136 | 77% | 76% | both meters read. |
| 2026-09-05 | new period | 7% | 8% | 60.5 hours to the Monday reset. |
| 2026-09-05 | limit event | not read | not read | NOT A READING. |

Ceiling for LEDGER: 80% of the weekly limit.
"""


def plant(tmp, sentence=True, queue=True, budget=True, image=True):
    """A fixture tree with any of the four source files withheld, so the
    missing-source half can be proven one source at a time."""
    root = Path(tmp)
    if sentence:
        d = root / SENTENCE_DIR
        d.mkdir(parents=True, exist_ok=True)
        (d / "2026-09-05-fixture.unprompted.md").write_text(FIXTURE_SENTENCE)
    if queue:
        (root / DECISIONS).parent.mkdir(parents=True, exist_ok=True)
        (root / DECISIONS).write_text(FIXTURE_QUEUE)
    if budget:
        (root / BUDGET).parent.mkdir(parents=True, exist_ok=True)
        (root / BUDGET).write_text(FIXTURE_BUDGET)
    if image:
        d = root / "game-design" / "sim-shots"
        d.mkdir(parents=True, exist_ok=True)
        from PIL import Image
        Image.new("RGB", (1600, 900), (40, 60, 80)).save(d / "fixture.jpg",
                                                         quality=85)
    return root


def selftest():
    import tempfile
    fails, ran = [], []

    def ok(name, cond, shown):
        ran.append(name)
        print("  %-4s %s | %s" % ("PASS" if cond else "FAIL", name, shown))
        if not cond:
            fails.append(name)

    print("glance selftest: ACCEPTING CASE FIRST")

    print("\n1. ACCEPTING: the live checkout, generated at its own clock.")
    now = datetime.datetime.now(datetime.timezone.utc)
    page, model = build(ROOT, now)
    for name, cond, shown in run_checks(page):
        ok(name, cond, shown)
    ok("readings", True, "colour=%s taken=%d/5 %s" % (
        model["colour"], sum(1 for l in model["looks"] if l.ok),
        " ".join("%s=%s" % (n, "read" if l.ok else "nothing-measured")
                 for n, l in zip(("state", "needsYou", "next", "image", "budget"),
                                 model["looks"]))))
    ok("sourcesNamed", all(("from " + l.source) in page or l.source in page
                           for l in model["looks"]),
       "sourcesNamed=%d/5 blocks name the file they were read from"
       % sum(1 for l in model["looks"] if l.source in page))
    # PRINTED, NOT ASSERTED. Which frame is the right one is a judgement off a
    # picture, and no string here can make it. This line exists so the next
    # reader knows which file to open before quoting the checks above.
    img = model["looks"][3]
    ok("imageChosen", True, "frame=%s embeddedBytes=%s of %s image file(s) on "
       "disk. OPEN IT: a green weight check said nothing about the contact "
       "sheet this rule used to pick"
       % (img.source, img.get("bytes"), img.get("examined")))

    print("\n2. ACCEPTING, AND THE RUN IN WHICH GREEN CAN HAPPEN: a planted "
          "tree with all five present and fresh.")
    with tempfile.TemporaryDirectory() as tmp:
        root = plant(tmp)
        page2, m2 = build(root, parse_now("2026-09-05T06:00Z"))
        ok("greenIsReachable", m2["colour"] == "GREEN",
           "colour=%s why=%s" % (m2["colour"], m2["why"]))
        ok("noFalseMissing", "nothing measured" not in page2,
           "nothingMeasuredOccurrences=%d/5 blocks"
           % page2.count("nothing measured"))
        for name, cond, shown in run_checks(page2):
            ok("fixture." + name, cond, shown)
        b = m2["looks"][4]
        ok("bothMeters", b.get("total") == 7 and b.get("fable") == 8
           and b.get("govern") == "fable",
           "total=%s fable=%s governs=%s skippedNonReadingRows=%s hoursToReset=%s"
           % (b.get("total"), b.get("fable"), b.get("govern"), b.get("skipped"),
              b.get("hours")))
        ok("whenIsRead", m2["looks"][2].get("when") == "2026-09-06",
           "when=%s" % m2["looks"][2].get("when"))

    print("\n3. REJECTING: the same tree at a clock 25 hours later.")
    with tempfile.TemporaryDirectory() as tmp:
        root = plant(tmp)
        page3, m3 = build(root, parse_now("2026-09-06T09:00Z"))
        ok("staleGoesGrey", m3["colour"] == "GREY", "colour=%s ageHours=%.0f "
           "rule=%dh" % (m3["colour"], m3["looks"][0].get("age_h"), STALE_HOURS))
        ok("staleStillQuotes", m3["looks"][0].ok and
           "street renders" in page3, "the sentence is still shown, GREY, "
           "rather than hidden")

    print("\n4. REJECTING: one source removed at a time.")
    for withheld, blockname in (("sentence", "state"), ("queue", "needs-you"),
                                ("budget", "budget"), ("image", "image")):
        with tempfile.TemporaryDirectory() as tmp:
            root = plant(tmp, **{withheld: False})
            page4, m4 = build(root, parse_now("2026-09-05T06:00Z"))
            greyed = m4["colour"] == "GREY"
            said = page4.count("nothing measured")
            zeros = "<p class=\"huge\">0</p>" in page4 and withheld == "queue"
            ok("missing." + withheld, greyed and said >= 1 and not zeros,
               "colour=%s nothingMeasured=%d block(s) falseZero=%s why=%s"
               % (m4["colour"], said, zeros, m4["why"]))

    print("\n5. REJECTING: the whole tree empty, which is every reading gone.")
    with tempfile.TemporaryDirectory() as tmp:
        page5, m5 = build(Path(tmp), parse_now("2026-09-05T06:00Z"))
        ok("allMissing", m5["colour"] == "GREY"
           and page5.count("nothing measured") == 5,
           "colour=%s nothingMeasured=%d/5 blocks" %
           (m5["colour"], page5.count("nothing measured")))
        for name, cond, shown in run_checks(page5):
            ok("empty." + name, cond, shown)

    print("\n6. REJECTING, SYNTHETIC: the file checks on bytes that violate "
          "them, so no check here is a ratchet.")
    bad_w = "<style>.x { min-width: 900px; }</style>"
    name, cond, shown = check_width(bad_w)
    ok("widthGuardBites", not cond, shown)
    bad_x = '<script src="https://cdn.example/x.js"></script><a href="a.html">'
    name, cond, shown = check_external(bad_x)
    ok("externalGuardBites", not cond, shown)
    name, cond, shown = check_blocks('<section data-block="1">')
    ok("blockGuardBites", not cond, shown)
    name, cond, shown = check_formatting("a — b <em>c</em>")
    ok("formattingGuardBites", not cond, shown)
    name, cond, shown = check_secrets("token 123456789:AAH" + "x" * 32)
    ok("secretGuardBites", not cond, shown)
    name, cond, shown = check_weight("x" * (PAGE_BYTE_CAP + 1))
    ok("weightGuardBites", not cond, shown)
    # Both outcomes of the forward link, the accepting one already run above on
    # every generated page: here the two ways it can be wrong, a page with no
    # link to the map and a page carrying two of them.
    name, cond, shown = check_map_link('<p class="tap"><a href="STATUS.md">x</a></p>')
    ok("mapLinkGuardBitesOnNone", not cond, shown)
    name, cond, shown = check_map_link('<a href="%s">a</a><a href="%s">b</a>'
                                       % (SIBLING[0], SIBLING[0]))
    ok("mapLinkGuardBitesOnTwo", not cond, shown)
    # The frame tie-break, both sides: the set that HAS a report-frame default
    # and the set that has nothing but a contact sheet.
    shots = [Path("game-design/sim-shots/clips.jpg"),
             Path("game-design/sim-shots/review_day1_noon.jpg"),
             Path("game-design/sim-shots/district_hook.jpg")]
    pick, rule = choose_frame(shots)
    ok("framePrefers", pick.name == "review_day1_noon.jpg",
       "of %d frame(s): %s" % (len(shots), rule))
    pick, rule = choose_frame([Path("game-design/sim-shots/clips.jpg")])
    ok("frameFallsBack", pick.name == "clips.jpg" and "path order" in rule,
       "of 1 frame(s): %s" % rule)

    print("\nglance selftest: %d check(s) run, %d failed%s"
          % (len(ran), len(fails), (": " + ", ".join(fails)) if fails else ""))
    return 1 if fails else 0


def main():
    ap = argparse.ArgumentParser(description="the glance page, phone-first")
    ap.add_argument("--root", default=str(ROOT), help="tree to read")
    ap.add_argument("--out", default=None, help="where to write the page")
    ap.add_argument("--now", default=None, help="ISO clock, for the 24h rule")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()
    if args.selftest:
        return selftest()
    now = parse_now(args.now) if args.now else datetime.datetime.now(
        datetime.timezone.utc)
    root = Path(args.root).resolve()
    out = Path(args.out) if args.out else root / OUT_NAME
    page, model = build(root, now)
    out.write_text(page, encoding="utf-8")
    checks = run_checks(page)
    bad = [n for n, c, _ in checks if not c]
    print("glance: wrote %s, colour=%s %s"
          % (out, model["colour"], " ".join(s for _, _, s in checks)))
    print("glance: %s" % model["why"])
    for name, look in zip(("state", "needsYou", "next", "image", "budget"),
                          model["looks"]):
        print("  %-9s %s | %s" % (name, "read" if look.ok else "NOTHING MEASURED",
                                  look.source))
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
