#!/usr/bin/env python3
"""THE MAP: every system a tile, grouped by area, coloured by status, one
screen, and the detail one tap down.

    python3 tools/map.py                      # write map.html at the root
    python3 tools/map.py --selftest           # accepting case first
    python3 tools/map.py --file <json>        # against a planted inventory
    python3 tools/map.py --out <f> --now <iso>

WHAT IT IS, AND WHERE IT SITS. Jafar, 2026-09-05, item 4: "render it as the map
view: every system a tile, grouped by area, coloured by status, one screen,
phone-first, tap a tile for status, blocker and decisions. It sits beside the
glance, not inside it: the glance is today, the map is the whole." So this is a
SECOND page. It links to glance.html and never adds a block to the five that
page is allowed. tools/glance.py is the sibling and was read rather than
edited; the house style here is its style on purpose.

THE RENDERER HOLDS NO FACTS OF ITS OWN. Every word on a tile or in a sheet
comes from production/systems-inventory.json, read THROUGH
tools/systems-inventory-check.py with --emit-json, never around it. That tool
owns the fixed sets, the coverage denominator and the refusal, and its exit
code decides what this page is: 0 draws the map, 1 draws a refusal naming the
entries, 2 prints the words "nothing measured" with the reason, 3 says the
check could not run. A map drawn from an invalid inventory is a picture of a
lie, so the grid is not drawn at all unless the check accepted the file.

THE SEVENTH FIELD IS A VALIDATOR FIELD, ruled by a director: `evidence` is
shown BEHIND THE TAP and never on a tile. A tile carries a name and a colour;
the sheet carries status, blocker, decisions, evidence and the note. The check
below proves both halves every run: evidenceOnTiles counts hits inside tile
markup against the number of references examined, and behindTap counts the same
references inside sheet markup, on the same line so a grep cannot merge them.

SELF-CONTAINED, because queue 097 publishes this beside the glance: one file,
no server, no build step, no remote script, stylesheet, font or image. The tap
is CSS :target, so opening a tile makes no network request and needs no
JavaScript; the phone's back button closes the sheet.

THE REPO IS PUBLIC and Jafar ruled that knowingly (decision-queue, RULED
2026-09-05 BY JAFAR: A. Publish as designed). Nothing here reads
tools/runner/config.local or any other secret, and the checks assert the
generated bytes carry neither that path nor a token-shaped string.
"""
import argparse
import contextlib
import datetime
import html
import importlib.util
import io
import json
import re
import sys
from pathlib import Path

TOOL = "tools/map.py"
ROOT = Path(__file__).resolve().parent.parent
OUT_NAME = "map.html"

# THE SOURCES, NAMED ONCE. The page quotes these paths rather than carrying a
# second copy of them in prose.
INVENTORY = "production/systems-inventory.json"
CHECK_TOOL = "tools/systems-inventory-check.py"
DECISION_DIR = "ledger-v2/respec/decision-register"
QUEUE_DIRS = ("production/queue", "production/queue/done")
SIBLING = "glance.html"          # the glance is today, this is the whole

# ---------------------------------------------------------------------------
# THE GEOMETRY, DERIVED RATHER THAN PICKED. 27 tiles on one phone screen is the
# whole difficulty of this page, so every number below is arithmetic and the
# result is printed against its budget every run (oneScreen check).
#
# 390 CSS px is the logical width of the phones in use (iPhone 12 through 15
# are 390 or 393) and is tools/glance.py's stated figure. Queue 096 allows
# nothing fixed or minimum wider than 360, so no layout width here is declared
# in px at all: the grid is four 1fr columns and everything else flows.
PHONE_WIDTH_PX = 390
#
# THE HEIGHT BUDGET IS A STATED ASSUMPTION AND NOT A MEASUREMENT FROM THIS
# CONTAINER, which has no browser. Safari on those phones leaves about 659 to
# 664 CSS px between its toolbars; 640 is below the smallest of them, so a
# layout that fits here fits on the phone and the error can only be in the
# direction of extra room. The computed height is printed every run, so the
# first look on glass either confirms it or corrects this one number.
ONE_SCREEN_PX = 640
#
# 44 px is Apple's minimum tap target (Human Interface Guidelines, 44 pt), and
# a tile IS the tap target here, so the tile height is that minimum and not a
# taste setting. Four columns then follow: at 390 wide a column is 90.5 px,
# which is wider than it is tall and takes the longest name in three lines.
COLUMNS = 4
TILE_PX = 44
GAP_PX = 4
TILE_PAD_PX = 4
BODY_PAD_PX = 8
BODY_PAD_BOTTOM_PX = 6
TITLE_PX = 15
LEGEND_PX = 16
AREA_HEAD_PX = 13
AREA_HEAD_GAP_PX = 3
AREA_MARGIN_PX = 4
FOOT_PX = 12
FOOT_GAP_PX = 4
LEGEND_GAP_ABOVE_PX = 4
LEGEND_GAP_BELOW_PX = 6
#
# THE NAME FIT. There is no text measurement in this container either, so the
# wrap is modelled: an average lowercase advance of half the font size is the
# usual approximation for these sans faces, and the model is greedy word
# wrapping exactly as a browser does it. IT IS AN ESTIMATE AND IT SHIPS ITS
# INSTRUMENT: every run prints the worst name, its predicted line count and the
# slack, so one look at the page can correct AVG_ADVANCE_EM rather than guess
# again. A name that does not fit in one column is given two (grid-column: span
# 2) rather than being shortened: the renderer holds no facts of its own and
# that includes a name it decided to abbreviate.
NAME_FONT_PX = 10
NAME_LINE_PX = 11
LINES_PER_TILE = 3
AVG_ADVANCE_EM = 0.5
MAX_SPAN = 2
#
# IF A 28TH SYSTEM ARRIVES the oneScreen check bites and names the number. The
# knobs, in the order they cost the least: AREA_MARGIN_PX, then COLUMNS to 5
# with NAME_FONT_PX to 9, then TILE_PX, which is last because it is the tap
# target and not free.
# ---------------------------------------------------------------------------

# THE PAGE WEIGHT CAP AND THE WIDTH BOUND ARE THE SIBLING'S NUMBERS AND ARE
# IMPORTED, not copied: see load_glance() below. tools/glance.py derives 250 000
# bytes from two seconds over a weak but usable mobile link (1 Mbit/s, 125 000
# bytes a second) and carries queue 096's 360 px bound. This page has no image
# and lands far under the weight cap, which is why the cap is not tightened
# today: a new bound needs a printed series first and this run is its first
# entry. Every run prints the measured weight and the percentage of the cap.

# The three status words, their colour and their SHAPE. The bar along the
# bottom of a tile is full, half or empty. It is a redundant encoding of the
# status word for a reader who cannot separate the hues or is in sunlight, and
# it is NOT a percentage of anything: half does not mean half done, it means
# the word partial. The legend on the page says exactly that.
STATUS_COLOUR = {"exists": "#1c6b33", "partial": "#7a4a00", "absent": "#31353d"}
STATUS_FILL = {"exists": 100, "partial": 50, "absent": 0}
STATUS_SHAPE = {"exists": "full bar", "partial": "half bar", "absent": "empty bar"}

NOTHING = "nothing measured"


def load_glance():
    """The phone-first bar is tools/glance.py's, imported rather than copied.

    Six of the checks below (viewport, declared width, external references,
    weight, formatting, secrets) are queue 096's rule and not this page's, and
    the sibling is where they are written down. Two implementations of them
    would drift the day the bound moves: the one nobody looks at is the page
    that keeps passing at 360 after the rule became 340. So the regexes, the
    two thresholds and the six functions come from there, and this file adds
    only the checks the map owns. The import is by path for symmetry with the
    others here; glance.py has no side effects at import time, and this file
    never writes to it.
    """
    p = ROOT / "tools" / "glance.py"
    spec = importlib.util.spec_from_file_location("glance", p)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


GLANCE = load_glance()
PAGE_BYTE_CAP = GLANCE.PAGE_BYTE_CAP
MAX_DECLARED_WIDTH_PX = GLANCE.MAX_DECLARED_WIDTH_PX


def load_check():
    """The inventory is parsed by tools/systems-inventory-check.py and not by a
    second parser here.

    "Is this inventory valid, and what are the fixed sets" is one question, and
    two implementations of it would drift the day an area is added: the one
    nobody looks at is the one that keeps drawing a tile for an entry the other
    refuses. That tool's own docstring says consumers import it. The import is
    by path because the file name carries hyphens, and it loads from THIS
    tool's repository rather than from --file, so a planted fixture supplies
    the data being read and never the rules for reading it.
    """
    p = ROOT / "tools" / "systems-inventory-check.py"
    spec = importlib.util.spec_from_file_location("systems_inventory_check", p)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


class Inventory:
    """What the check said, and nothing this file decided.

    `code` is the check's own exit code (0 accepted, 1 refused, 2 nothing
    measured, 3 could not run), `entries` is the validated JSON it emitted on
    stdout and is None for every non-zero code, and `report` is its report
    verbatim, which is what names the offending entry on a refusal.
    """

    def __init__(self, code, entries, report, source):
        self.code = code
        self.entries = entries
        self.report = report
        self.source = source

    @property
    def ok(self):
        return self.code == 0 and self.entries is not None

    WORD = {0: "accepted", 1: "REFUSED", 2: NOTHING, 3: "the check could not run"}

    @property
    def word(self):
        return self.WORD.get(self.code, "unknown exit %d" % self.code)


def read_inventory(check, path, names_path=None):
    """Run the check with --emit-json and keep both halves of what it says.

    The report goes to stderr and the validated entries to stdout precisely so
    that a refused inventory cannot be rendered as a page, so both streams are
    captured here and the exit code is obeyed rather than inspected for a
    usable remnant.
    """
    out, err = io.StringIO(), io.StringIO()
    with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
        code = check.run(str(path), names_path, emit=True)
    report = err.getvalue().strip()
    entries = None
    if code == 0:
        body = out.getvalue().strip()
        try:
            entries = json.loads(body) if body else None
        except ValueError as exc:
            code, report = 3, ("%s exited 0 but its emitted JSON did not parse "
                               "(%s)\n%s" % (CHECK_TOOL, exc, report))
    return Inventory(code, entries, report, check.rel(str(path)))


# ---------------------------------------------------------------------------
# THE LAYOUT MODEL. Python decides the spans and counts the rows, and the CSS
# below is generated from the same constants, so there is one set of numbers
# and not two that can drift.
# ---------------------------------------------------------------------------

def column_px():
    """One grid column at the stated phone width, in CSS px."""
    content = PHONE_WIDTH_PX - 2 * BODY_PAD_PX
    return (content - (COLUMNS - 1) * GAP_PX) / float(COLUMNS)


def chars_per_line(span):
    """How many characters fit across a tile of this span, under the stated
    average advance. Named as an estimate everywhere it is used."""
    inner = span * column_px() + (span - 1) * GAP_PX - 2 * TILE_PAD_PX
    return int(inner / (NAME_FONT_PX * AVG_ADVANCE_EM))


def wrap(name, cpl):
    """Greedy word wrapping, the way a browser does it. A single word longer
    than the line is left on its own line and overflows, which is what a
    browser does too and what the nameLines check exists to catch."""
    lines, cur = [], ""
    for word in name.split():
        joined = (cur + " " + word).strip()
        if len(joined) <= cpl or not cur:
            cur = joined
        else:
            lines.append(cur)
            cur = word
    if cur:
        lines.append(cur)
    return lines or [""]


def fit(name):
    """(span, lines) for one name: one column if it fits, otherwise two."""
    for span in range(1, MAX_SPAN + 1):
        cpl = chars_per_line(span)
        lines = wrap(name, cpl)
        if len(lines) <= LINES_PER_TILE and max(len(l) for l in lines) <= cpl:
            return span, lines
    return MAX_SPAN, wrap(name, chars_per_line(MAX_SPAN))


def layout(check, entries):
    """Group into the five areas in the check's own order and count the rows.

    The row count MIRRORS CSS GRID AUTO-PLACEMENT as the browser performs it:
    row flow, sparse, so an item that does not fit in the columns left starts a
    new row and leaves the hole behind. Modelling it any other way would make
    the height arithmetic below a different page's arithmetic.
    """
    groups, rows_total = [], 0
    placed = 0
    for area in check.AREAS:
        members = [e for e in entries if e.get("area") == area]
        col, rows = 0, 1 if members else 0
        tiles = []
        for e in members:
            span, lines = fit(str(e.get("name", "")))
            if col + span > COLUMNS:
                rows += 1
                col = 0
            col += span
            placed += 1
            tiles.append({"entry": e, "span": span, "lines": lines})
        groups.append({"area": area, "tiles": tiles, "rows": rows})
        rows_total += rows
    return {"groups": groups, "rows": rows_total, "placed": placed}


def layout_height(model):
    """The page's height at PHONE_WIDTH_PX, in CSS px, from the same constants
    the stylesheet is generated from. A sum, not a sample."""
    h = BODY_PAD_PX + TITLE_PX + LEGEND_GAP_ABOVE_PX + LEGEND_PX \
        + LEGEND_GAP_BELOW_PX
    for g in model["groups"]:
        if not g["tiles"]:
            continue
        h += AREA_HEAD_PX + AREA_HEAD_GAP_PX
        h += g["rows"] * TILE_PX + (g["rows"] - 1) * GAP_PX + AREA_MARGIN_PX
    return h + FOOT_GAP_PX + FOOT_PX + BODY_PAD_BOTTOM_PX


def worst_name(model):
    """The name closest to overflowing its tile, with its predicted lines. This
    is a peak and it is named as one: it answers "did any name ever need a
    fourth line", which is the only question the tile geometry cares about."""
    worst = None
    for g in model["groups"]:
        for t in g["tiles"]:
            n = len(t["lines"])
            if worst is None or n > worst[1]:
                worst = (str(t["entry"].get("name")), n, t["span"])
    return worst


# ---------------------------------------------------------------------------
# THE BLOCKER, RESOLVED TO A DECISION RECORD OR A QUEUE FILE. The data says
# `D1` or `queue-046` or `none`; the sheet says which file that is and what its
# heading calls it. Nothing is inferred: a blocker whose file cannot be found
# is printed as not found, with the folder that was searched.
# ---------------------------------------------------------------------------

D_NUMBER = re.compile(r"^D\d+$")
HEADING = re.compile(r"^#\s+(.*)$", re.M)


def first_heading(path):
    try:
        m = HEADING.search(path.read_text(encoding="utf-8", errors="replace"))
    except OSError:
        return None
    return m.group(1).strip() if m else None


def resolve_blocker(root, blocker):
    """(word, decision_line) for one blocker value, both from disk."""
    b = str(blocker) if blocker is not None else ""
    if not b or b == "none":
        return "none", "the inventory says none, so no decision is named"
    if D_NUMBER.match(b):
        d = root / DECISION_DIR
        hits = sorted(p for p in d.glob(b + "-*.md")) if d.is_dir() else []
        if not hits:
            return b, "no record named %s-*.md under %s" % (b, DECISION_DIR)
        title = first_heading(hits[0]) or hits[0].name
        return b, "%s (%s)" % (title, hits[0].relative_to(root).as_posix())
    if b.startswith("queue-"):
        num = b[len("queue-"):]
        for folder in QUEUE_DIRS:
            d = root / folder
            if d.is_dir():
                hits = sorted(p for p in d.glob(num + "-*.md"))
                if hits:
                    return b, "%s/%s" % (folder, hits[0].name)
        return b, "no queue file named %s-*.md under %s" % (num,
                                                            " or ".join(QUEUE_DIRS))
    return b, ("not a decision record (D<n>) or a queue item (queue-<n>), so "
               "no file was looked for")


# ---------------------------------------------------------------------------
# THE PAGE. Every px in the stylesheet is one of the constants above, so the
# height this file computes is the height the browser lays out.
# ---------------------------------------------------------------------------

CSS = """
:root { color-scheme: dark light; }
* { box-sizing: border-box; }
body { margin: 0; padding: %(pad)dpx %(pad)dpx %(padb)dpx; background: #14161a;
  color: #e9e9ea; font: 12px/1.25 -apple-system, BlinkMacSystemFont, "Segoe UI",
  Roboto, sans-serif; -webkit-text-size-adjust: 100%%; }
.head { display: flex; justify-content: space-between; align-items: baseline;
  height: %(title)dpx; line-height: %(title)dpx; }
h1 { font-size: 12px; letter-spacing: 0.12em; text-transform: uppercase;
  color: #cfd3d8; margin: 0; font-weight: 700; }
.head .n { font-size: 10px; color: #8b9198; }
.legend { display: flex; gap: 8px; align-items: center; height: %(legend)dpx;
  margin: %(lga)dpx 0 %(lgb)dpx; font-size: 10px; color: #9aa0a8; }
.legend b { font-weight: 600; color: #cfd3d8; }
.key { display: inline-flex; align-items: center; gap: 4px; }
.sw { display: inline-block; width: 14px; height: 10px; border-radius: 3px; }
.area { margin: 0 0 %(am)dpx; }
.area h2 { font-size: 10px; letter-spacing: 0.09em; text-transform: uppercase;
  color: #8b9198; margin: 0 0 %(ahg)dpx; height: %(ah)dpx; line-height: %(ah)dpx;
  font-weight: 600; }
.area h2 span { color: #6f757c; }
.grid { display: grid; grid-template-columns: repeat(%(cols)d, 1fr);
  gap: %(gap)dpx; }
.tile { position: relative; display: block; height: %(tile)dpx;
  padding: %(tp)dpx %(tp)dpx 8px; border-radius: 6px; text-decoration: none;
  color: #f2f3f4; overflow: hidden; }
.tile .n { display: block; font-size: %(font)dpx; line-height: %(line)dpx;
  font-weight: 600; overflow-wrap: anywhere; }
.bar { position: absolute; left: %(tp)dpx; right: %(tp)dpx; bottom: 3px;
  height: 3px; border-radius: 2px; background: rgba(255,255,255,0.13); }
.bar span { display: block; height: 100%%; border-radius: 2px;
  background: rgba(255,255,255,0.75); }
.exists { background: %(exists)s; }
.partial { background: %(partial)s; }
.absent { background: %(absent)s; border: 1px dashed #565c65; }
.foot { display: flex; gap: 14px; height: %(foot)dpx; line-height: %(foot)dpx;
  margin: %(fg)dpx 0 0; font-size: 10px; }
.foot a { color: #7fb2ff; text-decoration: none; }
.sheet { display: none; }
.sheet:target { display: block; position: fixed; top: 0; right: 0; bottom: 0;
  left: 0; background: #14161a; padding: 14px 12px 28px; overflow-y: auto;
  font-size: 14px; line-height: 1.4; }
.sheet h3 { font-size: 17px; margin: 0.2rem 0 0.6rem; }
.sheet dt { font-size: 10px; letter-spacing: 0.09em; text-transform: uppercase;
  color: #8b9198; margin-top: 0.7rem; }
.sheet dd { margin: 0.15rem 0 0; overflow-wrap: anywhere; }
.sheet dl { margin: 0; }
.sheet .ev { font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  font-size: 11px; color: #b9bec5; }
.sheet .note { color: #c6cbd1; }
.sheet .src { font-size: 11px; color: #767c84; margin-top: 1rem; }
.sheet pre { white-space: pre-wrap; font-size: 11px; color: #b9bec5;
  margin: 0.3rem 0 0; }
.close { display: inline-block; color: #7fb2ff; text-decoration: none;
  font-size: 13px; padding: 6px 0; }
.pill { display: inline-block; border-radius: 5px; padding: 2px 7px;
  font-size: 12px; font-weight: 600; }
.big { font-size: 22px; font-weight: 700; margin: 0.6rem 0 0.2rem; }
.why { font-size: 13px; color: #c8b26a; margin: 0.2rem 0 0.6rem; }
.report { white-space: pre-wrap; font-family: ui-monospace, SFMono-Regular,
  Menlo, monospace; font-size: 11px; color: #b9bec5; background: #1d2026;
  border-radius: 8px; padding: 8px; }
"""


def css():
    return CSS % {
        "pad": BODY_PAD_PX, "padb": BODY_PAD_BOTTOM_PX, "title": TITLE_PX,
        "legend": LEGEND_PX, "lga": LEGEND_GAP_ABOVE_PX,
        "lgb": LEGEND_GAP_BELOW_PX, "am": AREA_MARGIN_PX, "ah": AREA_HEAD_PX,
        "ahg": AREA_HEAD_GAP_PX, "cols": COLUMNS, "gap": GAP_PX,
        "tile": TILE_PX, "tp": TILE_PAD_PX, "font": NAME_FONT_PX,
        "line": NAME_LINE_PX, "foot": FOOT_PX, "fg": FOOT_GAP_PX,
        "exists": STATUS_COLOUR["exists"], "partial": STATUS_COLOUR["partial"],
        "absent": STATUS_COLOUR["absent"],
    }


PAGE = """<!DOCTYPE html>
<html lang="en-GB">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="dark light">
<title>LEDGER: the map</title>
<style>%s</style>
</head>
<body id="map">
%s
</body>
</html>
"""


def esc(s):
    return html.escape("" if s is None else str(s), quote=True)


def head(right):
    return ('<div class="head"><h1>LEDGER map</h1><span class="n">%s</span></div>'
            % esc(right))


def foot(extra=""):
    return ('<p class="foot"><a href="%s">the glance: today</a>'
            '<a href="#about">how this page was made</a>%s</p>'
            % (esc(SIBLING), extra))


def legend(tally, total):
    """The key is ON THE PAGE, with the count and its denominator beside each
    word: a colour scheme a reader has to remember is one that gets misread on
    a phone in a hurry."""
    keys = "".join(
        '<span class="key"><span class="sw %s"></span><b>%s</b> %d/%d</span>'
        % (esc(s), esc(s), tally.get(s, 0), total) for s in STATUS_COLOUR)
    return '<p class="legend">%s</p>' % keys


def tile(index, item):
    """A tile carries a NAME and a COLOUR and nothing else. The status word,
    the blocker, the decisions and the evidence are all behind the tap: the
    evidence field is a validator field and the director ruled it never appears
    on the face of a tile."""
    e = item["entry"]
    status = str(e.get("status"))
    span = ' style="grid-column: span %d"' % item["span"] if item["span"] > 1 else ""
    return ('<a class="tile %s" data-tile="%d" href="#s%d"%s>'
            '<span class="n">%s</span>'
            '<span class="bar"><span style="width: %d%%"></span></span></a>'
            % (esc(status), index, index, span, esc(e.get("name")),
               STATUS_FILL.get(status, 0)))


def area_block(check, group):
    """One area, its per-area count, and its tiles. The breakdown is per AREA
    because that is the axis the data varies on and the axis Jafar asked to be
    grouped by; a breakdown per anything else would be a different page's
    number."""
    n = len(group["tiles"])
    tiles = "".join(tile(t["index"], t) for t in group["tiles"])
    return ('<section class="area" data-area="%s"><h2>%s <span>%d of %d</span>'
            '</h2>\n<div class="grid">%s</div></section>'
            % (esc(group["area"]), esc(group["area"]), n, group["total"], tiles))


def sheet(root, index, entry):
    """The tap: status, blocker, decisions, evidence, and the note, every one
    of them quoted from the inventory. An empty evidence list prints the words
    "nothing measured" rather than an empty area, because a blank list cannot
    tell an absent system from a field nobody filled in."""
    status = str(entry.get("status"))
    word, decision = resolve_blocker(root, entry.get("blocker"))
    ev = entry.get("evidence") or []
    if ev:
        ev_html = "".join('<dd class="ev">%s</dd>' % esc(r) for r in ev)
    else:
        ev_html = ('<dd>%s. status=%s carries no evidence in %s</dd>'
                   % (NOTHING, esc(status), esc(INVENTORY)))
    note = entry.get("note")
    return ('<section class="sheet" id="s%d" data-sheet="%d">'
            '<a class="close" href="#map">close</a>'
            '<h3>%s</h3>'
            '<p><span class="pill %s">%s</span> %s</p>'
            '<dl>'
            '<dt>area</dt><dd>%s</dd>'
            '<dt>class</dt><dd>%s</dd>'
            '<dt>phase</dt><dd>%s</dd>'
            '<dt>blocker</dt><dd>%s</dd>'
            '<dt>decisions</dt><dd>%s</dd>'
            '<dt>evidence, %d reference(s)</dt>%s'
            '<dt>note</dt><dd class="note">%s</dd>'
            '</dl>'
            '<p class="src">Every line above is a field of this entry in %s, '
            'read through %s. Nothing on this page is filled in by the '
            'renderer.</p>'
            '<a class="close" href="#map">close</a></section>'
            % (index, index, esc(entry.get("name")), esc(status), esc(status),
               esc(STATUS_SHAPE.get(status, "")), esc(entry.get("area")),
               esc(entry.get("class")), esc(entry.get("phase")), esc(word),
               esc(decision), len(ev), ev_html,
               esc(note if note else "none in the data"),
               esc(INVENTORY), esc(CHECK_TOOL)))


def about_sheet(inv, model, now, extra_lines):
    """The provenance, the counts and the check's whole report, one tap down.
    The map itself stays one screen because every denominator lives here."""
    lines = "\n".join(extra_lines)
    return ('<section class="sheet" id="about" data-sheet="about">'
            '<a class="close" href="#map">close</a>'
            '<h3>how this page was made</h3>'
            '<p>Generated by %s at %s from %s, read through %s with '
            '--emit-json: the report is on stderr and the validated entries on '
            'stdout, so a refused inventory cannot be drawn as a map. The '
            'check said: %s.</p>'
            '<dl><dt>the layout, computed at %d CSS px wide</dt>'
            '<dd><pre>%s</pre></dd>'
            '<dt>the check, verbatim</dt>'
            '<dd><pre>%s</pre></dd></dl>'
            '<a class="close" href="#map">close</a></section>'
            % (esc(TOOL), esc(now.strftime("%Y-%m-%d %H:%M UTC")),
               esc(INVENTORY), esc(CHECK_TOOL), esc(inv.word),
               PHONE_WIDTH_PX, esc(lines), esc(inv.report or NOTHING)))


def refusal_page(inv, now):
    """No grid, ever, from an inventory the check did not accept.

    Three endings and each says which it is: REFUSED names the entries the
    check named, NOTHING MEASURED prints those words with the reason, and
    CANNOT RUN says the check itself could not start. An empty grid would read
    as a project with no systems, which is the one thing this page must never
    say by accident.
    """
    if inv.code == 2:
        big, why = (NOTHING, "The inventory is missing, unreadable or empty, so "
                    "there is nothing to draw. The reason from %s is below."
                    % CHECK_TOOL)
    elif inv.code == 1:
        big, why = ("REFUSED", "%s refused this inventory and named the "
                    "entries below. No tile is drawn from a refused file: a "
                    "map drawn from an invalid inventory is a picture of a "
                    "lie." % CHECK_TOOL)
    else:
        big, why = ("the check could not run", "%s could not start, so nothing "
                    "was validated and nothing is drawn." % CHECK_TOOL)
    body = (head("the map cannot be drawn")
            + '\n<p class="big">%s</p>\n<p class="why">%s</p>' % (esc(big), esc(why))
            + '\n<p class="report">%s</p>' % esc(inv.report or NOTHING)
            + '\n<p class="report">source: %s. checkExit=%d</p>'
            % (esc(inv.source), inv.code)
            + "\n" + foot()
            + "\n" + about_sheet(inv, None, now, ["nothing measured: the "
                                                  "inventory was not accepted, "
                                                  "so no layout was computed"]))
    return PAGE % (css(), body)


def build(root, inv, now):
    """The whole page and the model behind it. Returns (page, model); model is
    None when the inventory was not accepted, and the page is a refusal."""
    if not inv.ok:
        return refusal_page(inv, now), None
    check = load_check()
    entries = inv.entries
    model = layout(check, entries)
    total = len(entries)
    index = 0
    for g in model["groups"]:
        g["total"] = total
        for t in g["tiles"]:
            t["index"] = index
            index += 1
    tally = check.tally(entries, "status", check.STATUSES)
    areas = check.tally(entries, "area", check.AREAS)
    height = layout_height(model)
    worst = worst_name(model)
    model.update({"entries": entries, "tally": tally, "areas": areas,
                  "height": height, "worst": worst, "total": total})
    blocks = "\n".join(area_block(check, g) for g in model["groups"] if g["tiles"])
    sheets = "\n".join(sheet(root, t["index"], t["entry"])
                       for g in model["groups"] for t in g["tiles"])
    detail = [
        "tiles=%d entries=%d" % (model["placed"], total),
        "columns=%d gridColumnPx=%.1f tilePx=%d gapPx=%d"
        % (COLUMNS, column_px(), TILE_PX, GAP_PX),
        "tileRows=%d %s" % (model["rows"],
                            " ".join("%s=%d" % (g["area"], g["rows"])
                                     for g in model["groups"])),
        "byArea: " + " ".join("%s=%d/%d" % (a, areas[a], total)
                              for a in check.AREAS),
        "byStatus: " + " ".join("%s=%d/%d" % (s, tally[s], total)
                                for s in check.STATUSES),
        "layoutHeightPx=%d/%d budget at %d wide" % (height, ONE_SCREEN_PX,
                                                    PHONE_WIDTH_PX),
        "worstName=%d/%d lines at span %d: %s"
        % (worst[1], LINES_PER_TILE, worst[2], worst[0]),
        "the height is arithmetic from the constants in %s and not a browser "
        "measurement; the wrap assumes an average advance of %.2f em."
        % (TOOL, AVG_ADVANCE_EM),
    ]
    body = "\n".join([
        head("%d systems, %d areas" % (total, sum(1 for g in model["groups"]
                                                  if g["tiles"]))),
        legend(tally, total),
        blocks,
        foot(),
        sheets,
        about_sheet(inv, model, now, detail),
    ])
    return PAGE % (css(), body), model


# ---------------------------------------------------------------------------
# THE FILE CHECKS. The container has no browser, so phone-first is checked on
# the things a FILE can be asked, and then somebody opens it. Each returns
# (name, ok, printed) and every one ships its denominator. Six of them are the
# sibling's and are IMPORTED from tools/glance.py at the foot of this section.
# Seven are this page's own: the tile count against the entry count, a sheet
# behind every tile, the five areas summing to the entries, the seventh field
# being behind the tap and nowhere else, the computed height against the
# one-screen budget, the name fit, and the legend being on the page.
# ---------------------------------------------------------------------------

TILE_MARKUP = re.compile(r'<a class="tile.*?</a>', re.S)


def check_tiles(page, model, inv):
    """tiles=N beside entries=N. They can only differ if the renderer dropped
    or invented one, and both are worth catching."""
    n = len(re.findall(r'data-tile="\d+"', page))
    if model is None:
        # A refused inventory was never read, so there is no entry count to
        # divide by: the count is the words "nothing measured" and the only
        # accepting number of tiles is none at all.
        shown = ("tiles=%s reason=%s-exit%d tilesDrawn=%d"
                 % (NOTHING.replace(" ", "-"), inv.word.replace(" ", "-"),
                    inv.code, n))
        return ("tiles", n == 0, shown)
    return ("tiles", n == len(model["entries"]),
            "tiles=%d/%d entries" % (n, len(model["entries"])))


def check_sheets(page, model, inv):
    """Every tile opens something. A tile whose sheet is missing is a tap that
    does nothing, which on a phone is indistinguishable from a broken page."""
    n = len(re.findall(r'data-sheet="\d+"', page))
    about = len(re.findall(r'data-sheet="about"', page))
    if model is None:
        return ("sheets", n == 0 and about == 1,
                "sheets=%s about=%d/1" % (NOTHING.replace(" ", "-"), about))
    return ("sheets", n == len(model["entries"]) and about == 1,
            "sheets=%d/%d entries about=%d/1" % (n, len(model["entries"]), about))


def check_areas(page, model, inv):
    """Five areas, each with its own count, and the counts summing to the
    entries. A group that silently dropped an entry sums short."""
    found = re.findall(r'data-area="([^"]+)"', page)
    if model is None:
        return ("areas", not found,
                "areas=%s (no grid is drawn)" % NOTHING.replace(" ", "-"))
    total = sum(model["areas"][a] for a in model["areas"])
    nonempty = [a for a in model["areas"] if model["areas"][a]]
    return ("areas", sorted(found) == sorted(nonempty)
            and total == len(model["entries"]),
            "areas=%d/%d nonEmpty summing=%d/%d entries"
            % (len(found), len(model["areas"]), total, len(model["entries"])))


def check_evidence_off_tiles(page, model, inv):
    """THE SEVENTH FIELD RULE, both halves in one line: no evidence reference
    inside any tile, every evidence reference inside the sheets. The
    denominator is the number of references examined, so a page with no
    evidence at all cannot pass this as a clean zero."""
    if model is None:
        # No tile exists on a refusal page, so no evidence can be on one. The
        # denominator here is tiles and not references: the inventory was never
        # accepted, so its references were never read.
        tiles = TILE_MARKUP.findall(page)
        return ("evidence", not tiles,
                "evidenceRefs=%s tilesExamined=%d (no grid is drawn)"
                % (NOTHING.replace(" ", "-"), len(tiles)))
    refs = [r for e in model["entries"] for r in (e.get("evidence") or [])]
    tiles = "".join(TILE_MARKUP.findall(page))
    on_tiles = [r for r in refs if r in tiles]
    behind = sum(1 for r in refs if ('class="ev">%s<' % html.escape(r, quote=True))
                 in page)
    return ("evidence", not on_tiles and behind == len(refs),
            "evidenceOnTiles=%d/%d refs behindTap=%d/%d%s"
            % (len(on_tiles), len(refs), behind, len(refs),
               "" if not on_tiles else " (" + on_tiles[0] + ")"))


def check_one_screen(page, model, inv):
    """The computed height against the stated budget. It is arithmetic from the
    constants the stylesheet is generated from, not a browser measurement, and
    the printed line says so."""
    if model is None:
        return ("oneScreen", True,
                "layoutHeightPx=%s (no grid is drawn)" % NOTHING.replace(" ", "-"))
    h = model["height"]
    return ("oneScreen", h <= ONE_SCREEN_PX,
            "layoutHeightPx=%d/%d budget at %dwide rows=%d computed-not-measured"
            % (h, ONE_SCREEN_PX, PHONE_WIDTH_PX, model["rows"]))


def check_name_fit(page, model, inv):
    """The worst name against the lines a tile has. A peak, and named as one:
    the median name fits in one line and would hide the only case that matters.
    """
    if model is None:
        return ("nameFit", True,
                "worstNameLines=%s (no grid is drawn)" % NOTHING.replace(" ", "-"))
    name, lines, span = model["worst"]
    return ("nameFit", lines <= LINES_PER_TILE,
            "worstNameLines=%d/%d span=%d/%d cplAtSpan1=%d name=%s"
            % (lines, LINES_PER_TILE, span, MAX_SPAN, chars_per_line(1),
               name.replace(" ", "_")))


def check_legend(page, model, inv):
    """Three status words, three swatches, on the page. A colour scheme the
    reader has to remember is one that gets misread on a phone in a hurry."""
    swatches = len(re.findall(r'class="sw ([a-z-]+)"', page))
    words = sum(1 for s in STATUS_COLOUR if '<b>%s</b>' % s in page)
    if model is None:
        return ("legend", swatches == 0 and words == 0,
                "legendKeys=%s (no grid is drawn)" % NOTHING.replace(" ", "-"))
    return ("legend", swatches == len(STATUS_COLOUR) == words,
            "legendKeys=%d/%d swatches=%d/%d" % (words, len(STATUS_COLOUR),
                                                 swatches, len(STATUS_COLOUR)))


def shared(fn):
    """One of the sibling's checks, taking this file's (page, model, inv)."""
    def wrapped(page, model, inv):
        return fn(page)
    wrapped.__name__ = fn.__name__
    return wrapped


check_viewport = shared(GLANCE.check_viewport)
check_width = shared(GLANCE.check_width)
check_external = shared(GLANCE.check_external)
check_weight = shared(GLANCE.check_weight)
check_formatting = shared(GLANCE.check_formatting)
check_secrets = shared(GLANCE.check_secrets)

# The map's own four first, then the six that are queue 096's bar for any page
# this studio puts on his phone.
CHECKS = (check_tiles, check_sheets, check_areas, check_evidence_off_tiles,
          check_one_screen, check_name_fit, check_legend, check_viewport,
          check_width, check_external, check_weight, check_formatting,
          check_secrets)


def run_checks(page, model=None, inv=None):
    return [f(page, model, inv) for f in CHECKS]


# ---------------------------------------------------------------------------
# SELFTEST, ACCEPTING CASE FIRST. The accepting side is the one that goes
# unrun, so it is first and it runs against the LIVE inventory, which is the
# only fixture that can go stale under us. Every rejecting fixture is
# synthetic, so doing the work this page asks for can never break the tool.
# ---------------------------------------------------------------------------

# A valid entry that the check accepts: the evidence path and token are real
# files in this repository, because check_evidence_ref resolves them against
# the repository and not against the fixture.
GOOD = {"name": "planted system", "area": "world", "status": "exists",
        "class": "cheap-to-author", "phase": "1", "blocker": "D1",
        "evidence": ["CLAUDE.md#canon.md"], "note": "a planted fixture."}
BAD_AREA = dict(GOOD, name="planted harbour system", area="harbour")


def plant(tmp, entries):
    p = Path(tmp) / "planted-inventory.json"
    p.write_text(json.dumps(entries), encoding="utf-8")
    return p


def selftest():
    import tempfile
    fails, ran = [], []

    def ok(name, cond, shown):
        ran.append(name)
        print("  %-4s %s | %s" % ("PASS" if cond else "FAIL", name, shown))
        if not cond:
            fails.append(name)

    check = load_check()
    now = datetime.datetime(2026, 9, 5, 12, 0, tzinfo=datetime.timezone.utc)
    print("map selftest: ACCEPTING CASE FIRST")

    print("\n1. ACCEPTING: the live inventory, through %s." % CHECK_TOOL)
    inv = read_inventory(check, ROOT / INVENTORY)
    ok("inventoryAccepted", inv.ok, "checkExit=%d word=%s entries=%s"
       % (inv.code, inv.word.replace(" ", "-"),
          len(inv.entries) if inv.entries else NOTHING.replace(" ", "-")))
    page, model = build(ROOT, inv, now)
    for name, cond, shown in run_checks(page, model, inv):
        ok(name, cond, shown)
    if model:
        ok("perArea", True, " ".join("%s=%dtiles/%drows" % (g["area"],
                                                            len(g["tiles"]),
                                                            g["rows"])
                                     for g in model["groups"]))
        # PRINTED, NOT ASSERTED. Whether 10 px type is legible at arm's length
        # is a judgement off glass and no string here can make it. This line
        # exists so the next reader knows what to look at before quoting the
        # checks above.
        ok("openIt", True, "OPEN-IT: layoutHeightPx=%d/%d is arithmetic, not a "
           "browser; the 27 tiles at %dpx type are the thing to judge"
           % (model["height"], ONE_SCREEN_PX, NAME_FONT_PX))

    print("\n2. ACCEPTING, PLANTED: a small valid inventory, so the accepting "
          "path is proven on a file this test wrote.")
    with tempfile.TemporaryDirectory() as tmp:
        inv2 = read_inventory(check, plant(tmp, [GOOD, dict(GOOD, name="second",
                                                            status="absent",
                                                            evidence=[],
                                                            blocker="none")]))
        page2, m2 = build(ROOT, inv2, now)
        ok("plantedAccepted", inv2.ok and m2 is not None and m2["total"] == 2,
           "checkExit=%d tiles=%d/2 heightPx=%s"
           % (inv2.code, m2["placed"] if m2 else 0,
              m2["height"] if m2 else NOTHING))
        ok("plantedNoFalseMissing", NOTHING not in page2.split("<dt>evidence")[0],
           "the map half of the page says nothing measured %d time(s)"
           % page2.split("<dt>evidence")[0].count(NOTHING))
        for name, cond, shown in run_checks(page2, m2, inv2):
            ok("planted." + name, cond, shown)

    print("\n3. REJECTING: an entry whose area is not one of the five.")
    with tempfile.TemporaryDirectory() as tmp:
        inv3 = read_inventory(check, plant(tmp, [GOOD, BAD_AREA]))
        page3, m3 = build(ROOT, inv3, now)
        named = "planted harbour system" in page3 and "harbour" in page3
        ok("badAreaRefused", inv3.code == 1 and m3 is None and named
           and 'data-tile=' not in page3,
           "checkExit=%d tiles=%d namesTheEntry=%s bigWord=%s"
           % (inv3.code, page3.count('data-tile='), named, "REFUSED"
              if "REFUSED" in page3 else "MISSING"))
        for name, cond, shown in run_checks(page3, m3, inv3):
            ok("refused." + name, cond, shown)

    print("\n4. REJECTING: an empty inventory, and a missing one.")
    with tempfile.TemporaryDirectory() as tmp:
        inv4 = read_inventory(check, plant(tmp, []))
        page4, m4 = build(ROOT, inv4, now)
        ok("emptySaysNothingMeasured",
           inv4.code == 2 and NOTHING in page4 and 'data-tile=' not in page4,
           "checkExit=%d nothingMeasured=%d occurrence(s) tiles=%d gridDrawn=%s"
           % (inv4.code, page4.count(NOTHING), page4.count('data-tile='),
              'class="grid"' in page4))
        ok("emptyGivesReason", "reason=" in inv4.report or "entries=0" in inv4.report,
           "report=%s" % inv4.report.replace("\n", " | ")[:140])
        inv5 = read_inventory(check, Path(tmp) / "does-not-exist.json")
        page5, m5 = build(ROOT, inv5, now)
        ok("missingFileSaysNothingMeasured",
           inv5.code == 2 and NOTHING in page5 and 'data-tile=' not in page5,
           "checkExit=%d nothingMeasured=%d occurrence(s)"
           % (inv5.code, page5.count(NOTHING)))
        for name, cond, shown in run_checks(page5, m5, inv5):
            ok("empty." + name, cond, shown)

    print("\n5. REJECTING, SYNTHETIC: the file checks on bytes that violate "
          "them, so no check here is a ratchet.")
    fake = {"entries": [{"name": "x", "evidence": ["ledger/Assets/Foo.cs#Bar"]}],
            "areas": {"world": 1}, "height": 9999, "rows": 99,
            "worst": ("a name", LINES_PER_TILE + 1, MAX_SPAN),
            "tally": {}, "groups": [], "placed": 1, "total": 1}
    name, cond, shown = check_evidence_off_tiles(
        '<a class="tile exists" data-tile="0" href="#s0">'
        '<span class="n">ledger/Assets/Foo.cs#Bar</span></a>', fake, None)
    ok("evidenceOnTileBites", not cond, shown)
    name, cond, shown = check_one_screen("", fake, None)
    ok("oneScreenGuardBites", not cond, shown)
    name, cond, shown = check_name_fit("", fake, None)
    ok("nameFitGuardBites", not cond, shown)
    name, cond, shown = check_tiles("", {"entries": [1, 2]}, None)
    ok("tileCountGuardBites", not cond, shown)
    name, cond, shown = check_sheets('<b data-sheet="0"></b>',
                                     {"entries": [1, 2]}, None)
    ok("sheetGuardBites", not cond, shown)
    name, cond, shown = check_areas("", fake, None)
    ok("areaGuardBites", not cond, shown)
    name, cond, shown = check_legend("", fake, None)
    ok("legendGuardBites", not cond, shown)
    name, cond, shown = check_width("<style>.x { min-width: 900px; }</style>",
                                    None, None)
    ok("widthGuardBites", not cond, shown)
    name, cond, shown = check_external(
        '<script src="https://cdn.example/x.js"></script><a href="a.html">',
        None, None)
    ok("externalGuardBites", not cond, shown)
    name, cond, shown = check_formatting("a — b <em>c</em>", None, None)
    ok("formattingGuardBites", not cond, shown)
    name, cond, shown = check_secrets("token 123456789:AAH" + "x" * 32, None, None)
    ok("secretGuardBites", not cond, shown)
    name, cond, shown = check_weight("x" * (PAGE_BYTE_CAP + 1), None, None)
    ok("weightGuardBites", not cond, shown)
    name, cond, shown = check_viewport("<head></head>", None, None)
    ok("viewportGuardBites", not cond, shown)

    print("\n6. REJECTING, SYNTHETIC: the wrap model on a name no tile can "
          "hold, and the span rule on one only two columns can.")
    span, lines = fit("supercalifragilistic" * 4)
    ok("longNameOverflows", len(lines) > LINES_PER_TILE or
       max(len(l) for l in lines) > chars_per_line(MAX_SPAN),
       "span=%d lines=%d/%d longestWord=%d cplAtSpan2=%d"
       % (span, len(lines), LINES_PER_TILE, max(len(l) for l in lines),
          chars_per_line(MAX_SPAN)))
    span1, _ = fit("HUD")
    ok("shortNameStaysOneColumn", span1 == 1, "span=%d/%d for 'HUD'"
       % (span1, MAX_SPAN))

    print("\nmap selftest: %d check(s) run, %d failed%s"
          % (len(ran), len(fails), (": " + ", ".join(fails)) if fails else ""))
    return 1 if fails else 0


def parse_now(s):
    t = s.strip().replace("Z", "+00:00")
    d = datetime.datetime.fromisoformat(t)
    if d.tzinfo is None:
        d = d.replace(tzinfo=datetime.timezone.utc)
    return d.astimezone(datetime.timezone.utc)


def main():
    ap = argparse.ArgumentParser(description="the map view, phone-first")
    ap.add_argument("--root", default=str(ROOT), help="tree to read")
    ap.add_argument("--file", default=None, help="inventory to render")
    ap.add_argument("--names", default=None, help="queue file holding the names")
    ap.add_argument("--out", default=None, help="where to write the page")
    ap.add_argument("--now", default=None, help="ISO clock, for the footer")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()
    if args.selftest:
        return selftest()
    root = Path(args.root).resolve()
    out = Path(args.out) if args.out else root / OUT_NAME
    now = parse_now(args.now) if args.now else datetime.datetime.now(
        datetime.timezone.utc)
    check = load_check()
    inv = read_inventory(check, args.file or (root / INVENTORY), args.names)
    page, model = build(root, inv, now)
    # THE REFUSAL IS WRITTEN TOO, and deliberately over the previous map: a
    # stale map that still looks current is worse than a page saying why there
    # is no map today. The exit code carries the failure to the caller.
    out.write_text(page, encoding="utf-8")
    checks = run_checks(page, model, inv)
    bad = [n for n, c, _ in checks if not c]
    print("map: wrote %s, inventory=%s %s"
          % (out, inv.word.replace(" ", "-"), " ".join(s for _, _, s in checks)))
    if model is None:
        print("map: %s" % (inv.report or NOTHING).replace("\n", "\nmap: "))
    else:
        print("map: byArea " + " ".join(
            "%s=%d/%d" % (g["area"], len(g["tiles"]), model["total"])
            for g in model["groups"]))
    return 1 if (bad or not inv.ok) else 0


if __name__ == "__main__":
    sys.exit(main())
