#!/usr/bin/env python3
"""PUBLISH THE GLANCE to a URL Jafar can open on his phone, and PROVE the page
that is served is the page we built.

    python3 tools/publish-glance.py --build --out-dir _site --commit <sha>
    python3 tools/publish-glance.py --check <url> --expect-commit <sha>
    python3 tools/publish-glance.py --selftest

WHY THIS EXISTS AND WHAT IT IS NOT. `tools/glance.py` (queue 096, another
owner) generates the page, and `tools/map.py` (queue 099) generates the second
page published beside it. This file does not generate anything and does not
read either page's sources. It does three things a generator must not be asked
to do: it STAMPS the built bytes so a served body can be identified, it SCANS
the bytes it is about to publish, and it REQUESTS the published URL and reports
what came back. Both generators are consumed here by subprocess, unmodified.
The site is `SITE_FILES` below, which is the one place its file count is
written down.

THE ONE DISTINCTION THIS FILE IS FOR (queue 097 acceptance, verbatim): "a
request that does not complete (proxy refusal, timeout) prints the words
'nothing measured' with the error, and is never reported as 404". A 404 means
the site is not there. A refused request means WE DID NOT FIND OUT. Conflating
them reports a proxy's opinion as GitHub's. `fetch()` below returns a `measured`
flag and every verdict path branches on it before it looks at a status code.

A THIRD CASE THE STATUS CODE CANNOT SEE. This repository's `main` root carries
an unrelated `index.html` from the repository's prior life ("WC26 Picks"). If
Pages serves that, the request returns 200 and text/html and is NOT our page.
So 200 is never sufficient: the body must carry OUR stamp, and the stamp must
name the commit we expect. `pageResult=NOT-PUBLISHED reason=no-stamp-in-body`
is that case, and it is why the check does not stop at the status line.

WHY THE STAMP IS INJECTED HERE RATHER THAN GENERATED, corrected after the
first claim was wrong. The generated page DOES carry a dated sentence: the
footer reads "Generated by tools/glance.py at <date> <time> UTC". An earlier
probe here reported no clock in the page; that probe required 70 characters of
context on both sides of a date on one line, and the footer has about 48 before
it, so the instrument under-reported and the conclusion drawn from it was
false. The footer date is read and PRINTED as `pageGeneratedAt`, which is the
acceptance clause's "dated sentence from the newest generated page".

The stamp still earns its line, for the thing the footer cannot do: the footer
carries no commit, so it cannot answer "is this the page THIS commit built".
Staleness is decided on commit equality, and only the stamp carries a commit.
Rather than edit another builder's file, the publish step adds exactly one HTML
comment after the doctype. Nothing visible changes; the published bytes differ
from the generator's output by that comment and nothing else, measured by diff
2026-09-05 and asserted by `--selftest`.

STALENESS IS DECIDED BY COMMIT EQUALITY, NOT BY A TIME BOUND. An exact
comparison needs no threshold and CLAUDE.md rule 2 forbids inventing one. Age
in minutes is PRINTED on every run (the acceptance asks for it, and a printed
series is what a future bound would be set from); it only gates when
`--max-age-min` is passed explicitly.
"""
import argparse
import datetime
import http.server
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import threading
import time
import urllib.error
import urllib.request
from pathlib import Path

TOOL = "tools/publish-glance.py"
ROOT = Path(__file__).resolve().parent.parent
GENERATOR = "tools/glance.py"
MAP_GENERATOR = "tools/map.py"
GALLERY_GENERATOR = "tools/gallery.py"
STAMP_OPEN = "<!--ledger-glance-stamp"
DOCTYPE = "<!DOCTYPE html>"

# THE SITE, NAMED ONCE, so the count in the build verdict and the count in the
# selftest cannot drift apart: both read len(SITE_FILES) rather than a literal.
# Each row is (generatorPath, publishedNames, exitCodeIsFatal).
#
# WHY THE MAP IS HERE. tools/map.py (queue 099) writes a second page that is
# published beside this one, and tools/glance.py now links forward to it. A
# link to a file nobody publishes is a 404 on his phone, so the two changes are
# one change: the publisher carries map.html or the link is a lie.
#
# WHY THE MAP'S EXIT CODE IS NOT FATAL AND THE GLANCE'S IS. tools/map.py exits
# 1 when the inventory is refused or a layout check bites, and it DELIBERATELY
# writes a page saying why over the previous map ("a stale map that still looks
# current is worse than a page saying why there is no map today", its main()).
# Publishing that refusal is the designed behaviour, and a bad JSON entry must
# not take the GLANCE off his phone: index.html is the site. A generator that
# wrote NO FILE is fatal for both, because the glance links to map.html.
# WHY THE GALLERY IS HERE, and why its exit code is not fatal either. Jafar
# ruled it on 2026-09-06 ("add a gallery page beside the glance") and the
# Producer's register now allows a link to exactly three destinations, of which
# it is one: a register that permits a link to a page nobody publishes is a 404
# on his phone with a rule behind it. tools/gallery.py exits 1 when a picture
# was dropped for want of a resizer and still writes the page saying how many,
# which is the map's rule for the map's reason: a page that says what it holds
# beats a stale one. A red gallery must never take index.html off his phone.
#
# WHY THE GALLERY ROW CARRIES TWO MORE FIELDS SINCE 2026-09-09. Jafar ruled
# the gallery shows every picture, "not two embedded files", and the town
# atlas belongs in it as a world page. So tools/gallery.py stopped embedding
# base64 and now writes the pictures as FILES plus a second page. That makes
# two things this publisher must do and used to be able to assume away:
#   `extraPages` is the second page the generator writes under its own flag,
#   published and stamped like any other page.
#   `assets` is the directory the generator writes the picture files into. It
#   is created INSIDE the publish directory, and the generator's manifest, not
#   this file's guesswork, is what names them. A src naming a file the
#   publisher does not copy is a broken image on his phone, which is the 404
#   this file's own comments already describe for map.html.
# Each row is (generatorPath, publishedNames, exitCodeIsFatal, extraPages,
# assetsDir), where extraPages is ((generatorFlag, publishedName), ...).
PAGES = (
    (GENERATOR, ("index.html", "glance.html"), True, (), None),
    (MAP_GENERATOR, ("map.html",), False, (), None),
    (GALLERY_GENERATOR, ("gallery.html",), False,
     (("--world-out", "world.html"),), "gallery-img"),
)
SITE_FILES = (tuple(n for _, names, _, _, _ in PAGES for n in names)
              + tuple(n for _, _, _, extra, _ in PAGES for _, n in extra)
              + (".nojekyll",))
# THE PICTURE FILES ARE NOT IN SITE_FILES, and that is deliberate: their names
# and their count are decided by how many pictures exist, so a fixed list would
# be a denominator that stopped growing. They come from the generator's
# manifest, are counted as their own number, and every one of them is checked
# against the pages that reference it.
ASSET_MANIFEST = "manifest.json"
IMAGE_SUFFIXES = (".jpg", ".jpeg", ".png", ".gif", ".webp")


def read_manifest(assets_dir):
    """(files, how) from the generator's own manifest.

    THE GENERATOR NAMES ITS FILES; THIS FILE DOES NOT GUESS THEM. A publisher
    that globbed the directory would carry whatever was lying in it, which is
    the "stale checkout's files ride out as this run's evidence" shape the CI
    rules already forbid for git add. A missing manifest is a measured absence
    with its own word, never an empty list that reads as "no pictures".
    """
    p = Path(assets_dir) / ASSET_MANIFEST
    if not p.is_file():
        return [], "absent-at-%s" % p.name
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except ValueError as e:
        return [], "unparseable/%s" % type(e).__name__
    files = data.get("files")
    if not isinstance(files, list):
        return [], "no-files-array"
    return [f for f in files if isinstance(f, dict) and f.get("name")], p.name

# THE CREDENTIAL SHAPES, NAMED SO A ZERO CAN SHIP ITS DENOMINATOR. Each entry
# is one pattern; the count of this list IS the denominator every scan prints.
# Deliberately PREFIXED shapes only. A generic "long alphanumeric run" pattern
# fires on the base64 data URI the glance embeds (about 95k of the 102k bytes),
# which would make the guard a ratchet that cannot tell a leak from a picture.
# The accepting fixture for these patterns is the live generated page, and
# `--selftest` runs them against it before it runs them against a planted leak.
SECRET_PATTERNS = [
    ("configLocal", re.compile(r"config\.local")),
    ("githubToken", re.compile(r"gh[pousr]_[A-Za-z0-9]{20,}")),
    ("githubPat", re.compile(r"github_pat_[A-Za-z0-9_]{20,}")),
    ("awsKeyId", re.compile(r"AKIA[0-9A-Z]{16}")),
    ("telegramToken", re.compile(r"[0-9]{8,10}:[A-Za-z0-9_-]{35}")),
    ("privateKey", re.compile(r"-----BEGIN[ A-Z]*PRIVATE KEY-----")),
    ("bearerHeader", re.compile(r"(?i)authorization:\s*bearer\s+\S+")),
]

# Markers that identify a refusal by the container's agent proxy rather than an
# answer from the host. Measured 2026-09-05: the proxy answers the GitHub Pages
# API with 403 and this body, and refuses github.io at CONNECT with
# "CONNECT tunnel failed, response 403". Neither is evidence about GitHub.
# Read ONLY against an HTTPError body. These must stay proxy-specific: the
# question here is "did the ORIGIN answer 403, or did the proxy answer for it",
# and a genuine origin 403 is a measurement that must not be downgraded to
# "nothing measured". A bare "forbidden" belongs nowhere near this list.
PROXY_MARKERS = (
    "not permitted through this proxy",
    "__agentproxy",
    "proxy authentication required",
)
# Read ONLY against a URLError reason, where the request already did not
# complete and no status exists. Nothing is downgraded by matching here; the
# only thing being chosen is the LABEL on an already-unmeasured result.
TUNNEL_MARKERS = (
    "connect tunnel failed",      # curl's wording
    "tunnel connection failed",   # urllib's wording for the same refusal
    "proxy",
    "forbidden",
)


def now_utc():
    return datetime.datetime.now(datetime.timezone.utc)


def iso(dt):
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


# ---------------------------------------------------------------- the scan

def scan(text, where):
    """Return (hits, examined). `hits` is a list of (patternName, sample).

    Ships its denominator: `examined` is the number of PATTERNS applied, which
    is what a zero here is a zero out of. The sample is truncated and the
    matched text is never printed in full, because a scanner that echoes the
    secret it found has published it into the log.
    """
    hits = []
    for name, rx in SECRET_PATTERNS:
        m = rx.search(text)
        if m:
            hits.append((name, where, len(m.group(0))))
    return hits, len(SECRET_PATTERNS)


def scan_verdict(hits, examined, files_scanned, bytes_scanned):
    line = ("secretHits=%d/%d-patterns filesScanned=%d bytesScanned=%d"
            % (len(hits), examined, files_scanned, bytes_scanned))
    if files_scanned == 0:
        # The KEY carries a hyphenated value because every reader splits on
        # whitespace; the WORDS are printed beside it because a never-ran
        # reading must say so in words, not in a token a human skims past.
        line = ("secretHits=nothing-measured filesScanned=0 "
                "reason=no-file-reached-the-scanner (nothing measured)")
    return line


# ---------------------------------------------------------------- the stamp

def make_stamp(commit, built_at):
    """One HTML comment, no spaces inside any value (instruments.md)."""
    return ("%s builtAt=%s builtAtEpoch=%d commit=%s tool=%s-->"
            % (STAMP_OPEN, iso(built_at), int(built_at.timestamp()),
               commit, TOOL))


# The generator's OWN dated sentence, read so the check quotes the page's clock
# and not only ours. Printed, never gated: this is another builder's wording and
# a gate on it would go red when they reword the footer, which is not a fault in
# the published page. The stamp is what gates.
#
# BOTH GENERATORS, because both write that sentence: measured in the built
# bytes on 2026-09-05, map.html's footer reads "Generated by tools/map.py at
# 2026-09-05 16:44 UTC from production/systems-inventory.json...". Matching the
# glance's name only printed pageGeneratedAt=nothing-measured against a date
# that was sitting in the body, which is this file's own recorded instrument
# fault (see the docstring above) a second time.
# THE GALLERY WRITES THE SAME SENTENCE IN AN HTML COMMENT rather than on the
# page, because Jafar ruled that page carries pictures and nothing else. This
# regex reads the served bytes, so it finds it either way; a reader sees only
# pictures. Verified against the generated bytes 2026-09-06.
GENERATED_RX = re.compile(
    r"Generated by tools/(?:glance|map|gallery)\.py at (\d{4}-\d{2}-\d{2}) "
    r"(\d{2}:\d{2}) UTC")

STAMP_RX = re.compile(
    re.escape(STAMP_OPEN) +
    r"\s+builtAt=(?P<iso>\S+)\s+builtAtEpoch=(?P<epoch>\d+)"
    r"\s+commit=(?P<commit>\S+)\s+tool=(?P<tool>\S+?)-->")


def read_stamp(body):
    m = STAMP_RX.search(body)
    if not m:
        return None
    return {"iso": m.group("iso"), "epoch": int(m.group("epoch")),
            "commit": m.group("commit"), "tool": m.group("tool")}


def inject_stamp(html_text, stamp):
    """Insert the stamp immediately after the doctype. Fail closed: a page
    whose shape we do not recognise is not silently published unstamped."""
    idx = html_text.find(DOCTYPE)
    if idx != 0:
        raise SystemExit(
            "publish-glance: FAIL generated page does not begin with %r "
            "(found at index %d). Refusing to publish an unstamped page, "
            "because the check cannot tell it from a stale one."
            % (DOCTYPE, idx))
    cut = len(DOCTYPE)
    return html_text[:cut] + "\n" + stamp + html_text[cut:]


# ---------------------------------------------------------------- the build

def refusal_reason(generator, code, exit_is_fatal, wrote_file):
    """"" to publish this generator's bytes, or the sentence to refuse with.

    PURE, so the selftest exercises both outcomes without planting a broken
    inventory (instruments.md: the arithmetic lives where the tests run). Two
    facts decide it and they are separate: whether a page exists at all, and
    whether a non-zero exit from THIS generator is allowed to be published.
    """
    if not wrote_file:
        return ("%s exited %d and wrote no page at all. Nothing published; "
                "nothing measured about the served page." % (generator, code))
    if code != 0 and exit_is_fatal:
        return ("%s exited %d and its page is the site root. Nothing "
                "published: a root nobody checked is worse than no deploy."
                % (generator, code))
    return ""


def site_files(out_dir, assets=()):
    """(present, missing, extra) by NAME, over SITE_FILES as the denominator.

    Missing is what makes the publish a lie (a linked page that 404s); extra
    is how a stale checkout's files ride out under this run's name. Both are
    counted here rather than described, and both halves are exercised by
    `--selftest`.

    `assets` is the picture files the generator declared in its manifest. They
    are expected too, but they are NOT part of SITE_FILES: that tuple is the
    fixed set of pages and a picture count belongs to the pictures. Passing
    them in keeps a hundred published frames out of the `extra` column, where
    they would read as a stale checkout's leftovers.
    """
    out_dir = Path(out_dir)
    on_disk = sorted(p.relative_to(out_dir).as_posix()
                     for p in out_dir.rglob("*") if p.is_file())
    expected = list(SITE_FILES) + list(assets)
    present = [n for n in SITE_FILES if n in on_disk]
    missing = [n for n in expected if n not in on_disk]
    extra = [n for n in on_disk if n not in expected]
    return present, missing, extra


IMG_SRC_RX = re.compile(r'<img[^>]*\ssrc="([^"]+)"')


def image_refs(out_dir):
    """THE SITE-WIDE READING: (referenced, found, missing, orphans, pages).

    THE PUBLISHED SET IS THE DENOMINATOR ON BOTH SIDES. `missing` is a src
    naming a file this publish does not carry, which is a broken picture on his
    phone; `orphans` is a published file no page references, which is weight
    nobody asked for and, on the day a page stops naming a picture, the only
    sign the page changed shape.

    NOT THE SAME CHECK AS tools/gallery.py's `imagesResolve`, and deliberately
    not shared with it: that one asks whether the page a generator just wrote
    agrees with the files it just wrote, before anything is published. This one
    asks the question only the publisher can ask, over every page in the
    directory that is about to be uploaded, including files no generator here
    claims. Data URIs are counted separately and never as a miss: the glance
    and the map embed their one frame on purpose.
    """
    out_dir = Path(out_dir)
    referenced, found, missing, data_uris, pages = [], 0, [], 0, 0
    for f in sorted(out_dir.rglob("*.html")):
        pages += 1
        text = f.read_text(encoding="utf-8", errors="replace")
        for src in IMG_SRC_RX.findall(text):
            if src.startswith("data:"):
                data_uris += 1
                continue
            referenced.append(src)
            if (f.parent / src).is_file():
                found += 1
            else:
                missing.append("%s->%s" % (f.name, src))
    named = {s.split("/")[-1] for s in referenced}
    orphans = []
    for f in sorted(out_dir.rglob("*")):
        if not f.is_file() or f.suffix.lower() not in (".jpg", ".jpeg", ".png",
                                                       ".gif", ".webp"):
            continue
        if f.name not in named:
            orphans.append(f.relative_to(out_dir).as_posix())
    return {"referenced": len(referenced), "found": found, "missing": missing,
            "orphans": orphans, "dataUris": data_uris, "pages": pages}


def run_generator(root, generator, out_path, extra_args=()):
    """(text, returncode, wrote_file). The generator is consumed by subprocess
    and never imported: this file does not generate anything."""
    cmd = [sys.executable, str(root / generator),
           "--root", str(root), "--out", str(out_path), *extra_args]
    p = subprocess.run(cmd, capture_output=True, text=True)
    wrote = out_path.exists()
    text = out_path.read_text(encoding="utf-8") if wrote else ""
    said = [l for l in (p.stdout or "").splitlines() if l.strip()]
    return text, p.returncode, wrote, p, said[-1] if said else ""


def build(root, out_dir, commit, generator_args=()):
    root = Path(root).resolve()
    out_dir = Path(out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    built_at = now_utc()
    stamp = make_stamp(commit, built_at)

    pre_hits, examined, lines, notes = [], len(SECRET_PATTERNS), [], []
    assets, asset_bytes = [], 0
    with tempfile.TemporaryDirectory() as td:
        for generator, names, exit_is_fatal, extra_pages, assets_dir in PAGES:
            raw = Path(td) / Path(names[0]).name
            # generator_args reach the FIRST generator only: they are the
            # glance's flags (--now and friends) and the map does not share
            # them. Nothing in this repository passes any today.
            extra = list(generator_args if generator == PAGES[0][0] else ())
            for flag, name in extra_pages:
                extra += [flag, str(Path(td) / name)]
            if assets_dir:
                # STRAIGHT INTO THE PUBLISH DIRECTORY. The pictures need no
                # stamp and copying them twice would only give the two copies a
                # chance to differ.
                extra += ["--assets-dir", str(out_dir / assets_dir),
                          "--url-prefix", assets_dir]
            text, code, wrote, proc, said = run_generator(root, generator, raw,
                                                          extra)
            reason = refusal_reason(generator, code, exit_is_fatal, wrote)
            if reason:
                sys.stdout.write(proc.stdout or "")
                sys.stderr.write(proc.stderr or "")
                raise SystemExit("publish-glance: FAIL " + reason)
            hits, examined = scan(text, generator)
            pre_hits.extend(hits)
            stamped = inject_stamp(text, stamp)
            # WRITE THE ARTIFACT, then scan the ARTIFACT (CLAUDE.md rule 4:
            # open the thing you are shipping, not the thing you meant to
            # ship). The scan below walks out_dir, so it reads these bytes.
            for name in names:
                (out_dir / name).write_text(stamped, encoding="utf-8")
            published = list(names)
            for _flag, name in extra_pages:
                src = Path(td) / name
                if not src.is_file():
                    raise SystemExit(
                        "publish-glance: FAIL %s was asked for %s and wrote "
                        "no such file. Nothing published: a page that is "
                        "linked and absent is a tap into a 404."
                        % (generator, name))
                body = src.read_text(encoding="utf-8")
                h2, examined = scan(body, generator + ":" + name)
                pre_hits.extend(h2)
                (out_dir / name).write_text(inject_stamp(body, stamp),
                                            encoding="utf-8")
                published.append(name)
            if assets_dir:
                got, why = read_manifest(out_dir / assets_dir)
                # THE MANIFEST ITSELF IS PUBLISHED AND EXPECTED. It is the
                # provenance of the picture set and it is what a later reader
                # opens to ask which file came from which frame; counted as
                # expected so it does not read as a stale checkout's leftover.
                assets += ["%s/%s" % (assets_dir, f["name"]) for f in got] \
                    + ["%s/%s" % (assets_dir, ASSET_MANIFEST)]
                asset_bytes += sum(int(f.get("bytes", 0)) for f in got)
                lines.append("  generator=%s assetsDir=%s manifest=%s "
                             "assetFiles=%d assetBytes=%d"
                             % (generator, assets_dir, why, len(got),
                                sum(int(f.get("bytes", 0)) for f in got)))
            lines.append("  generator=%s exit=%d generatorHits=%d/%d-patterns "
                         "pageBytes=%d stampBytes=%d publishedAs=%s"
                         % (generator, code, len(hits), examined,
                            len(stamped.encode("utf-8")),
                            len(stamped) - len(text), ",".join(published)))
            if code != 0:
                # Published on purpose, and never silently: this is the only
                # path on which a green publish carries a page that failed its
                # own checks, so it says so in words beside the exit code.
                notes.append("  NOTE %s exited %d and its page was published "
                             "anyway, because it writes a page saying why "
                             "rather than a stale one. It said: %s"
                             % (generator, code, said or "nothing on stdout"))
    (out_dir / ".nojekyll").write_text("", encoding="utf-8")

    # THE SCAN READS TEXT, AND SAYS WHAT IT SKIPPED. Reading five megabytes of
    # published JPEG through seven credential patterns finds nothing and costs
    # real time, so the picture files are skipped BY SUFFIX and counted: a
    # denominator that quietly grew to include binaries would make "0 hits over
    # 100 files" a bigger number about a smaller question.
    hits, files_scanned, bytes_scanned, skipped = [], 0, 0, 0
    for f in sorted(out_dir.rglob("*")):
        if not f.is_file():
            continue
        if f.suffix.lower() in IMAGE_SUFFIXES:
            skipped += 1
            continue
        blob = f.read_text(encoding="utf-8", errors="replace")
        h, examined = scan(blob, str(f.relative_to(out_dir)))
        hits.extend(h)
        files_scanned += 1
        bytes_scanned += len(blob.encode("utf-8"))

    present, missing, extra = site_files(out_dir, assets)
    refs = image_refs(out_dir)
    on_disk = [p for p in out_dir.rglob("*") if p.is_file()]
    total_bytes = sum(p.stat().st_size for p in on_disk)
    print("%s buildVerdict commit=%s builtAt=%s outDir=%s"
          % (TOOL, commit, iso(built_at), out_dir))
    for line in lines:
        print(line)
    for line in notes:
        print(line)
    print("  " + scan_verdict(hits, examined, files_scanned, bytes_scanned)
          + " binaryFilesSkipped=%d" % skipped)
    # WHOLE-RUN COUNTS, on their own line: how many of the named site files are
    # on disk, and how many files are there that this run did not name. The cap
    # on the extra names announces itself.
    shown = ",".join(extra[:5]) or "none"
    print("  siteFiles=%d/%d-expected missing=%s extraFiles=%d names=%s%s"
          % (len(present), len(SITE_FILES), ",".join(missing) or "none",
             len(extra), shown,
             " (+%d-more-not-shown)" % (len(extra) - 5) if len(extra) > 5 else ""))
    # THE PICTURE FILES AND THE REFERENCES INTO THEM. Two different ways for a
    # published page to be wrong and so two keys: a src with no file behind it
    # is a broken picture on his phone, a file no page names is weight nobody
    # asked for. The whole-run byte and file totals are here because a Pages
    # deploy has a real size and a real file-count cost, and neither was ever
    # printed while every picture was base64 inside one page.
    print("  assetFilesOnDisk=%d/%d-in-the-manifest publishedFiles=%d "
          "publishedBytes=%d imageRefsResolved=%d/%d-referenced "
          "imageRefsMissing=%s orphanImageFiles=%d dataUriImages=%d "
          "htmlPagesRead=%d"
          % (len([a for a in assets if (out_dir / a).is_file()]), len(assets),
             len(on_disk), total_bytes, refs["found"], refs["referenced"],
             ",".join(refs["missing"][:3]) or "none", len(refs["orphans"]),
             refs["dataUris"], refs["pages"]))
    for name, where, ln in hits:
        print("  LEAK pattern=%s file=%s matchLen=%d" % (name, where, ln))
    if hits or pre_hits:
        raise SystemExit(
            "publish-glance: FAIL a credential shape is present in the bytes "
            "about to be published. Nothing was deployed. A gitignore stops a "
            "commit and does not stop a render.")
    if missing:
        raise SystemExit(
            "publish-glance: FAIL %d of %d expected file(s) were not "
            "written: %s. Nothing published. The glance links to map.html and "
            "the gallery names its picture files, so a site short one file is "
            "a tap into a 404 on his phone."
            % (len(missing), len(SITE_FILES) + len(assets),
               ",".join(missing[:6])
               + (" (+%d-more-not-shown)" % (len(missing) - 6)
                  if len(missing) > 6 else "")))
    if refs["missing"]:
        raise SystemExit(
            "publish-glance: FAIL %d of %d image reference(s) name a file "
            "this publish does not carry: %s. Nothing published: a broken "
            "picture on his phone is indistinguishable from a page that "
            "failed to load."
            % (len(refs["missing"]), refs["referenced"],
               ",".join(refs["missing"][:6])
               + (" (+%d-more-not-shown)" % (len(refs["missing"]) - 6)
                  if len(refs["missing"]) > 6 else "")))
    print("  publishedAs=%s+%d-picture-file(s) stampedWith=%s..."
          % ("+".join(SITE_FILES), len(assets), stamp[:60]))
    return out_dir


# ---------------------------------------------------------------- the fetch

def fetch(url, timeout=30):
    """Return a dict. `measured` is False when the request DID NOT COMPLETE.

    Every caller must read `measured` before it reads `status`. A proxy that
    answers 403 on our behalf produced no evidence about the origin, and a
    refusal recorded as a status code is the instrument fault this project
    keeps catching.
    """
    req = urllib.request.Request(url, headers={"User-Agent": "ledger-publish-glance"})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            body = r.read().decode("utf-8", errors="replace")
            return {"measured": True, "status": r.status,
                    "ctype": r.headers.get("Content-Type", "") or "",
                    "body": body, "err": ""}
    except urllib.error.HTTPError as e:
        body = ""
        try:
            body = e.read().decode("utf-8", errors="replace")
        except Exception:
            pass
        low = (body + " " + str(e.headers or "")).lower()
        if e.code in (403, 407) and any(m in low for m in PROXY_MARKERS):
            return {"measured": False, "status": None, "ctype": "", "body": "",
                    "err": "proxy refused the request with HTTP %d (%s). This "
                           "is the container's proxy, not the origin."
                           % (e.code, body.strip()[:160] or "no body"),
                    "reason": "proxy-refusal"}
        return {"measured": True, "status": e.code,
                "ctype": e.headers.get("Content-Type", "") if e.headers else "",
                "body": body, "err": ""}
    except urllib.error.URLError as e:
        r = str(getattr(e, "reason", e))
        reason = "proxy-refusal" if any(m in r.lower() for m in TUNNEL_MARKERS) \
            else "request-did-not-complete"
        return {"measured": False, "status": None, "ctype": "", "body": "",
                "err": "request did not complete: %s" % r, "reason": reason}
    except Exception as e:  # socket timeouts, TLS, DNS
        return {"measured": False, "status": None, "ctype": "", "body": "",
                "err": "request did not complete: %s: %s"
                       % (type(e).__name__, e),
                "reason": "request-did-not-complete"}


def mime_of(ctype):
    return (ctype.split(";")[0] or "").strip().lower()


def norm(ctype):
    return re.sub(r"\s+", "", ctype).lower() or "none"


# ---------------------------------------------------------------- the check

def evaluate(res, expect_commit, max_age_min, now=None):
    """Pure. Returns (verdictLine, extraLines, exitCode). Kept free of I/O so
    the selftest exercises the same arithmetic the CI run prints
    (instruments.md: the maths lives where the tests run)."""
    now = now or now_utc()
    if not res["measured"]:
        return ("pageHttp=nothing-measured pageType=nothing-measured "
                "pageAgeMin=nothing-measured pageResult=NOTHING-MEASURED "
                "reason=%s" % res.get("reason", "request-did-not-complete"),
                ["nothing measured: the request did not complete, so this run "
                 "found out NOTHING about the page. This is not a 404.",
                 "error: " + res["err"]], 3)

    body = res["body"]
    status = res["status"]
    mime = mime_of(res["ctype"])
    nbytes = len(body.encode("utf-8"))
    stamp = read_stamp(body)
    hits, examined = scan(body, "served-body")

    age = "nothing-measured"
    if stamp:
        age = int(max(0, (now.timestamp() - stamp["epoch"]) // 60))

    head = ("pageHttp=%d pageType=%s pageAgeMin=%s" % (status, mime or "none", age))
    gm = GENERATED_RX.search(body)
    generated = ("%sT%sZ" % (gm.group(1), gm.group(2))) if gm else "nothing-measured"
    detail = ("pageTypeFull=%s pageBytes=%d pageGeneratedAt=%s pageStampCommit=%s "
              "expectCommit=%s %s" % (norm(res["ctype"]), nbytes, generated,
                                      stamp["commit"] if stamp else "none",
                                      expect_commit or "none",
                                      scan_verdict(hits, examined, 1, nbytes)))
    extra = [detail]

    # ORDER MATTERS. A leak outranks everything: it must not be reported green
    # even on a fresh page, and it must be named even on a stale one.
    if hits:
        for name, where, ln in hits:
            extra.append("LEAK pattern=%s where=%s matchLen=%d" % (name, where, ln))
        return (head + " pageResult=SECRET-LEAK", extra, 2)
    if status != 200:
        return (head + " pageResult=NOT-PUBLISHED reason=http-%d" % status,
                extra + ["the site answered, and it did not serve the page. "
                         "This IS a measurement: the origin replied."], 1)
    if mime != "text/html":
        return (head + " pageResult=NOT-PUBLISHED reason=wrong-content-type",
                extra + ["served as %s, which on a phone is source code, not a "
                         "page. A host that serves HTML as text/plain is a file "
                         "he cannot read by another name." % (mime or "none")], 1)
    if not stamp:
        return (head + " pageResult=NOT-PUBLISHED reason=no-stamp-in-body",
                extra + ["200 and text/html, but this is NOT our page: no "
                         "publish stamp. Something else is being served at "
                         "this URL."], 1)
    if expect_commit and stamp["commit"] != expect_commit:
        return (head + " pageResult=STALE reason=commit-mismatch",
                extra + ["published page was built from %s; the newest page is "
                         "%s. The site is up and it is OLD; this fails on age, "
                         "not on status." % (stamp["commit"], expect_commit)], 1)
    if max_age_min is not None and age != "nothing-measured" and age > max_age_min:
        return (head + " pageResult=STALE reason=age-over-%dmin" % max_age_min,
                extra + ["the stamp is %s minutes old against a bound of %d."
                         % (age, max_age_min)], 1)
    return (head + " pageResult=OK", extra, 0)


def check(url, expect_commit, max_age_min, retries, wait_sec, timeout=30):
    """Retries exist for the CDN cache, and EVERY WAIT ANNOUNCES ITSELF. The
    budget below is a budget, not a measured threshold: the attempt series it
    prints is what a future bound would be set from."""
    attempt, started = 0, time.time()
    while True:
        attempt += 1
        res = fetch(url, timeout=timeout)
        line, extra, code = evaluate(res, expect_commit, max_age_min)
        print("%s attempt=%d/%d elapsedSec=%d url=%s"
              % (TOOL, attempt, retries + 1, int(time.time() - started), url))
        print("  " + line)
        for e in extra:
            print("  " + e)
        # Retry only what a cache can fix. A leak, a wrong type or a refusal
        # will not improve by waiting, and looping on them hides them.
        retryable = code == 1 and ("STALE" in line or "no-stamp-in-body" in line
                                   or "http-404" in line)
        if code == 0 or attempt > retries or not retryable:
            if code != 0:
                print("  attemptsMade=%d/%d totalWaitSec=%d"
                      % (attempt, retries + 1, int(time.time() - started)))
            return code
        print("  retry=%d/%d waitSec=%d reason=%s (CDN may still be serving the "
              "previous deploy)" % (attempt, retries, wait_sec,
                                    line.split("pageResult=")[1].split()[0]))
        time.sleep(wait_sec)


# ---------------------------------------------------------------- selftest

# THE STUB GENERATOR THE SELFTEST PLANTS. It answers every "--...-out" flag it
# is given, and when it is given an assets directory it writes one real picture
# file, a manifest naming it and a page that references it, so the fixture
# exercises the whole path the gallery now uses rather than the one flag the
# first stub knew about.
STUB_GENERATOR = """import base64, json, pathlib, sys
argv = sys.argv
outs = [argv[i + 1] for i, a in enumerate(argv[:-1]) if a.endswith('-out')]
img = ''
assets = None
if '--assets-dir' in argv:
    assets = pathlib.Path(argv[argv.index('--assets-dir') + 1])
    prefix = argv[argv.index('--url-prefix') + 1] if '--url-prefix' in argv \\
        else assets.name
    assets.mkdir(parents=True, exist_ok=True)
    blob = base64.b64decode(
        'iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAIAAABLbSncAAAAFElEQVR4nGPUsIliwAaY'
        'sIoOWgkAmcoAzpfIFcsAAAAASUVORK5CYII=')
    (assets / 'stub-001.png').write_bytes(blob)
    (assets / 'manifest.json').write_text(json.dumps(
        {'files': [{'name': 'stub-001.png', 'bytes': len(blob),
                    'source': 'stub'}]}))
    img = '<img src="%s/stub-001.png">' % prefix
for o in outs:
    pathlib.Path(o).write_text(
        '<!DOCTYPE html><html><body>stub' + img + '</body></html>')
"""
# ... the same stub with its picture removed after the fact, which is the shape
# of a manifest naming a file the publish does not carry ...
STUB_DELETES_ITS_PICTURE = """
if assets is not None:
    (assets / 'stub-001.png').unlink()
"""
# ... and the same stub whose PAGE names a picture no manifest ever claimed,
# which is the other half: the file list can be perfect and the page can still
# point at nothing. Two faults, two fixtures, because the first refusal to fire
# hides the second.
STUB_GHOST_PICTURE = """
for o in outs:
    pathlib.Path(o).write_text(
        '<!DOCTYPE html><html><body>stub' + img +
        '<img src="gallery-img/ghost-nobody-published.png"></body></html>')
"""


class _Handler(http.server.BaseHTTPRequestHandler):
    ROUTES = {}

    def do_GET(self):
        route = self.ROUTES.get(self.path)
        if route is None:
            self.send_response(404)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.end_headers()
            self.wfile.write(b"<!DOCTYPE html><html><body>404</body></html>")
            return
        status, ctype, body = route
        raw = body.encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(raw)))
        self.end_headers()
        self.wfile.write(raw)

    def log_message(self, *a):
        pass


def _serve(routes):
    _Handler.ROUTES = routes
    srv = http.server.HTTPServer(("127.0.0.1", 0), _Handler)
    threading.Thread(target=srv.serve_forever, daemon=True).start()
    return srv, "http://127.0.0.1:%d" % srv.server_address[1]


def selftest():
    checks, failed = [], []

    def ok(name, cond, note):
        checks.append(name)
        print("  %s %s | %s" % ("PASS" if cond else "FAIL", name, note))
        if not cond:
            failed.append(name)

    print("%s selftest: ACCEPTING CASES FIRST" % TOOL)
    tmp = Path(tempfile.mkdtemp(prefix="publish-glance-"))
    try:
        # ACCEPTING 1: build against the LIVE repository. instruments.md: for a
        # tool that checks this project, the live codebase is the accepting
        # fixture, so doing the work the tool prompts can never break the tool.
        out = tmp / "site"
        build(ROOT, out, "aaaaaaaa")
        built = (out / "index.html").read_text(encoding="utf-8")
        built_assets = ["%s/%s" % (d, f["name"])
                        for _, _, _, _, d in PAGES if d
                        for f in read_manifest(out / d)[0]] \
            + ["%s/%s" % (d, ASSET_MANIFEST)
               for _, _, _, _, d in PAGES if d]
        present, missing, extra = site_files(out, built_assets)
        ok("buildProducesPage", not missing and len(present) == len(SITE_FILES),
           "wrote %s = %d/%d expected page(s) plus %d picture file(s), "
           "missing=%s extraFiles=%d"
           % ("+".join(present), len(present), len(SITE_FILES),
              len(built_assets), ",".join(missing) or "none", len(extra)))

        # ACCEPTING 1b: the MAP is its own stamped page and not a second copy
        # of the glance. Two files with one body would pass a file count and
        # publish the wrong page under the map's name.
        mapped = (out / "map.html").read_text(encoding="utf-8")
        ok("mapIsItsOwnStampedPage",
           read_stamp(mapped) is not None and mapped != built
           and "LEDGER map" in mapped,
           "mapBytes=%d glanceBytes=%d identical=%s mapStampCommit=%s"
           % (len(mapped.encode("utf-8")), len(built.encode("utf-8")),
              mapped == built,
              (read_stamp(mapped) or {}).get("commit", "none")))

        # ACCEPTING 1c: A MAP GENERATOR THAT EXITS NON-ZERO STILL PUBLISHES,
        # because it writes a page saying why. Planted with stub generators in
        # a synthetic tree, so this exercises THIS file's rule and not another
        # builder's tool. The four files must still be there and the NOTE must
        # be printed, which is the only way a red generator reaches a green
        # publish without saying so.
        # THE STUB WRITES EVERY PAGE IT IS ASKED FOR, and its picture files
        # and its manifest when it is given an assets directory: a stub that
        # only knew --out stopped covering the site the day a generator wrote
        # a second page, and the fixture would then pass while measuring less.
        stub_ok = STUB_GENERATOR
        soft = tmp / "softroot"
        (soft / "tools").mkdir(parents=True)
        # EVERY GENERATOR IN PAGES GETS A STUB, from PAGES itself.
        for gen, _, _, _, _ in PAGES:
            (soft / gen).write_text(stub_ok, encoding="utf-8")
        (soft / MAP_GENERATOR).write_text(stub_ok + "sys.exit(1)\n",
                                          encoding="utf-8")
        build(soft, tmp / "softsite", "aaaaaaaa")
        soft_assets = ["%s/%s" % (d, f["name"])
                       for _, _, _, _, d in PAGES if d
                       for f in read_manifest(tmp / "softsite" / d)[0]] \
            + ["%s/%s" % (d, ASSET_MANIFEST) for _, _, _, _, d in PAGES if d]
        p3, m3, x3 = site_files(tmp / "softsite", soft_assets)
        ok("redMapStillPublishes", not m3 and len(p3) == len(SITE_FILES),
           "siteFiles=%d/%d-expected missing=%s extraFiles=%d "
           "assetFiles=%d with %s exiting 1"
           % (len(p3), len(SITE_FILES), ",".join(m3) or "none", len(x3),
              len(soft_assets), MAP_GENERATOR))

        # ACCEPTING 1d: THE PICTURE FILES ARE PUBLISHED AND EVERY SRC RESOLVES.
        # Read off the built directory, both ways: a src with no file is a
        # broken picture on his phone and a file no page names is weight.
        live_assets = ["%s/%s" % (d, f["name"])
                       for _, _, _, _, d in PAGES if d
                       for f in read_manifest(out / d)[0]]
        live_refs = image_refs(out)
        ok("picturesArePublishedFiles",
           live_refs["referenced"] > 0
           and live_refs["found"] == live_refs["referenced"]
           and not live_refs["missing"]
           and all((out / a).is_file() for a in live_assets),
           "imageRefsResolved=%d/%d-referenced assetFiles=%d/%d-in-the-manifest "
           "orphans=%d dataUriImages=%d htmlPagesRead=%d"
           % (live_refs["found"], live_refs["referenced"],
              sum(1 for a in live_assets if (out / a).is_file()),
              len(live_assets), len(live_refs["orphans"]),
              live_refs["dataUris"], live_refs["pages"]))

        # REJECTING 0d: A PAGE THAT NAMES A PICTURE NOBODY PUBLISHED STOPS THE
        # PUBLISH. This is the fault the manifest exists to prevent, planted:
        # the stub writes the src and deletes the file behind it.
        broke = tmp / "brokenroot"
        (broke / "tools").mkdir(parents=True)
        for gen, _, _, _, _ in PAGES:
            (broke / gen).write_text(stub_ok, encoding="utf-8")
        (broke / GALLERY_GENERATOR).write_text(
            stub_ok + STUB_DELETES_ITS_PICTURE, encoding="utf-8")
        broke_said = ""
        try:
            build(broke, tmp / "brokensite", "aaaaaaaa")
        except SystemExit as e:
            broke_said = str(e)
        ok("refusesWhenAManifestFileIsMissing",
           "were not written" in broke_said
           and "gallery-img/stub-001.png" in broke_said,
           (broke_said.replace("\n", " ")[:150]
            or "NO REFUSAL: a manifest naming a file nobody published "
               "was shipped"))

        # REJECTING 0e: THE OTHER HALF. The file list can be perfect and the
        # page can still point at nothing, so a stub whose page names a picture
        # no manifest ever claimed must be refused by the reference check
        # rather than by the file count.
        ghost = tmp / "ghostroot"
        (ghost / "tools").mkdir(parents=True)
        for gen, _, _, _, _ in PAGES:
            (ghost / gen).write_text(stub_ok, encoding="utf-8")
        (ghost / GALLERY_GENERATOR).write_text(stub_ok + STUB_GHOST_PICTURE,
                                               encoding="utf-8")
        ghost_said = ""
        try:
            build(ghost, tmp / "ghostsite", "aaaaaaaa")
        except SystemExit as e:
            ghost_said = str(e)
        ok("refusesWhenAPageNamesAnUnpublishedPicture",
           "image reference" in ghost_said
           and "ghost-nobody-published.png" in ghost_said,
           (ghost_said.replace("\n", " ")[:150]
            or "NO REFUSAL: a page naming a file nobody published was "
               "shipped"))

        # REJECTING 0a: THE COUNT CAN GO WRONG. One file removed by hand from a
        # built site is named, so the count is not a ratchet.
        short = tmp / "short"
        shutil.copytree(out, short)
        (short / "map.html").unlink()
        p2, m2, x2 = site_files(short)
        ok("detectsMissingSiteFile",
           m2 == ["map.html"] and len(p2) == len(SITE_FILES) - 1,
           "siteFiles=%d/%d-expected missing=%s extraFiles=%d "
           "(map.html deleted by hand)"
           % (len(p2), len(SITE_FILES), ",".join(m2) or "none", len(x2)))

        # REJECTING 0b: a generator that writes NO page stops the publish, and
        # the refusal names which generator and which file is absent.
        hard = tmp / "hardroot"
        (hard / "tools").mkdir(parents=True)
        for gen, _, _, _, _ in PAGES:
            (hard / gen).write_text(stub_ok, encoding="utf-8")
        (hard / MAP_GENERATOR).write_text("import sys\nsys.exit(3)\n",
                                          encoding="utf-8")
        refused = ""
        try:
            build(hard, tmp / "nosite", "aaaaaaaa")
        except SystemExit as e:
            refused = str(e)
        ok("refusesWhenAPageIsMissing",
           "wrote no page" in refused and MAP_GENERATOR in refused
           and not (tmp / "nosite" / "map.html").exists(),
           (refused.replace("\n", " ")[:130]
            or "NO REFUSAL: the build returned with a page missing"))

        # REJECTING 0c: the rule itself, all four outcomes, on the pure
        # function the build calls. Fatal and non-fatal are different rows and
        # a file written is different from an exit code.
        table = [(GENERATOR, 1, True, True, True),      # root failed: refuse
                 (MAP_GENERATOR, 1, False, True, False),  # page written: ship
                 (MAP_GENERATOR, 1, False, False, True),  # no page: refuse
                 (GENERATOR, 0, True, True, False)]       # clean: ship
        got = [bool(refusal_reason(g, c, f, w)) for g, c, f, w, _ in table]
        ok("refusalRuleBothWays", got == [e for *_, e in table],
           "refuse=%s over %d planted (generator,exit,fatal,wroteFile) row(s)"
           % (",".join("Y" if v else "N" for v in got), len(table)))

        # ACCEPTING 2: the scan does not fire on the REAL page, data URI and
        # all. This is the case the guard must pass, and it is why the pattern
        # list is prefixed shapes only.
        hits, examined = scan(built, "built")
        ok("scanPassesRealPage", not hits,
           "hits=%d/%d-patterns over %d bytes of the live generated page "
           "(about 95k of it a base64 data URI)"
           % (len(hits), examined, len(built.encode("utf-8"))))

        # ACCEPTING 2b: the generator's own dated sentence is present and
        # readable. This is the reading that was wrongly reported absent.
        # THE DENOMINATOR IS THE SITE, NOT A HAND-TYPED PAIR. It read
        # "2/2 published page(s)" on a site of three, which is a denominator
        # smaller than the set examined: a clean reading over a list that
        # stopped growing. Derived from PAGES so it cannot fall behind again.
        # glance.html is index.html's twin (same bytes, two names), so the
        # first published name of each generator is the page to read.
        dated = []
        for name in [names[0] for _, names, _, _, _ in PAGES]:
            m = GENERATED_RX.search((out / name).read_text(encoding="utf-8"))
            dated.append("%s=%s" % (name, ("%sT%sZ" % (m.group(1), m.group(2)))
                                    if m else "nothing-measured"))
        ok("generatorDateIsReadable", "nothing-measured" not in " ".join(dated),
           "pageGeneratedAt read from %d/%d published page(s): %s"
           % (sum(1 for d in dated if "nothing-measured" not in d), len(dated),
              " ".join(dated)))
        # ... and the same reading on a body that carries no such sentence, so
        # a widened pattern cannot be an always-on green.
        ok("generatorDateCanBeAbsent",
           GENERATED_RX.search("<!DOCTYPE html><html><body>WC26 Picks</body>"
                               "</html>") is None,
           "pageGeneratedAt=nothing-measured on a foreign body, so the "
           "reading is not always-on")

        # ACCEPTING 3: the stamp round-trips and is the ONLY difference.
        st = read_stamp(built)
        stripped = STAMP_RX.sub("", built).replace(DOCTYPE + "\n", DOCTYPE, 1)
        ok("stampRoundTrips", st is not None and st["commit"] == "aaaaaaaa",
           "read back commit=%s builtAt=%s"
           % (st["commit"] if st else "none", st["iso"] if st else "none"))

        # ACCEPTING 4: the live page served over HTTP checks green.
        srv, base = _serve({
            "/": (200, "text/html; charset=utf-8", built),
            "/stale.html": (200, "text/html; charset=utf-8",
                            built.replace("commit=aaaaaaaa", "commit=old00000")),
            "/leak.html": (200, "text/html; charset=utf-8",
                           built.replace("</body>",
                                         "<p>ghp_" + "A" * 36 + "</p></body>")),
            "/plain.html": (200, "text/plain; charset=utf-8", built),
            "/notours.html": (200, "text/html; charset=utf-8",
                              "<!DOCTYPE html><html><body>WC26 Picks</body></html>"),
            "/origin403.html": (403, "text/html; charset=utf-8",
                                "<!DOCTYPE html><html><body>Forbidden</body></html>"),
        })
        try:
            code = check(base + "/", "aaaaaaaa", None, 0, 0)
            ok("acceptLivePage", code == 0, "exit=%d on a freshly built page" % code)

            # REJECTING 1: a URL that was never published.
            res = fetch(base + "/never-published.html")
            line, _, code = evaluate(res, "aaaaaaaa", None)
            ok("reject404", code == 1 and "pageHttp=404" in line
               and "NOT-PUBLISHED" in line, line)

            # REJECTING 2: a body one day old fails ON AGE, not on status.
            res = fetch(base + "/stale.html")
            line, _, code = evaluate(res, "aaaaaaaa", None)
            ok("rejectStaleNotStatus", code == 1 and "pageHttp=200" in line
               and "STALE" in line and "commit-mismatch" in line,
               line + " (200 and still red)")

            # REJECTING 2b: the age bound bites when one is given. Planted
            # condition, bound not loosened.
            res = fetch(base + "/")
            old = dict(res)
            old["body"] = old["body"].replace(
                "builtAtEpoch=%d" % read_stamp(old["body"])["epoch"],
                "builtAtEpoch=%d" % (int(now_utc().timestamp()) - 86400))
            line, _, code = evaluate(old, "aaaaaaaa", 60)
            ok("rejectAgeBound", code == 1 and "STALE" in line
               and "pageAgeMin=1440" in line, line)

            # REJECTING 3: a planted credential shape in the served body.
            res = fetch(base + "/leak.html")
            line, _, code = evaluate(res, "aaaaaaaa", None)
            ok("rejectPlantedCredential", code == 2 and "SECRET-LEAK" in line, line)

            # REJECTING 3b: a GENUINE 403 FROM THE ORIGIN IS A MEASUREMENT.
            # The refusal classifier must not downgrade it to "nothing
            # measured": the origin answered, and "the site refuses to serve
            # this" is a fact about the site. This is the case the split
            # between PROXY_MARKERS and TUNNEL_MARKERS exists to protect.
            res = fetch(base + "/origin403.html")
            line, _, code = evaluate(res, "aaaaaaaa", None)
            ok("origin403StaysMeasured", code == 1 and "pageHttp=403" in line
               and "NOTHING-MEASURED" not in line, line)

            # REJECTING 4: HTML served as text/plain is a file he cannot read.
            res = fetch(base + "/plain.html")
            line, _, code = evaluate(res, "aaaaaaaa", None)
            ok("rejectWrongContentType", code == 1
               and "wrong-content-type" in line, line)

            # REJECTING 5: 200 text/html that is SOMEONE ELSE'S page.
            res = fetch(base + "/notours.html")
            line, _, code = evaluate(res, "aaaaaaaa", None)
            ok("rejectNotOurPage", code == 1 and "no-stamp-in-body" in line
               and "pageHttp=200" in line, line)
        finally:
            srv.shutdown()

        # THE ACCEPTANCE CLAUSE'S OWN CASE: a request that does not complete
        # prints "nothing measured" and is NEVER reported as 404.
        res = fetch("http://127.0.0.1:1/", timeout=3)
        line, extra, code = evaluate(res, "aaaaaaaa", None)
        ok("refusalIsNotA404",
           code == 3 and "NOTHING-MEASURED" in line and "404" not in line
           and any("nothing measured" in e for e in extra),
           line + " | " + extra[0][:70])

        # And the same for a genuine proxy refusal shape.
        line2, extra2, code2 = evaluate(
            {"measured": False, "status": None, "ctype": "", "body": "",
             "err": "proxy refused the request with HTTP 403",
             "reason": "proxy-refusal"}, "aaaaaaaa", None)
        ok("proxyRefusalIsNotA404", code2 == 3 and "reason=proxy-refusal" in line2
           and "pageHttp=nothing-measured" in line2, line2)

        # A never-ran reading prints the words, not a zero.
        ok("neverRanSaysSo", "nothing measured" in scan_verdict([], 7, 0, 0),
           scan_verdict([], 7, 0, 0))
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    print("\n%s selftest: %d check(s) run, %d failed"
          % (TOOL, len(checks), len(failed)))
    return 1 if failed else 0


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--build", action="store_true")
    ap.add_argument("--check", metavar="URL")
    ap.add_argument("--selftest", action="store_true")
    ap.add_argument("--root", default=str(ROOT))
    ap.add_argument("--out-dir", default="_site")
    ap.add_argument("--commit", default="")
    ap.add_argument("--expect-commit", default="")
    ap.add_argument("--max-age-min", type=int, default=None)
    ap.add_argument("--retries", type=int, default=0)
    ap.add_argument("--wait-sec", type=int, default=15)
    a = ap.parse_args()

    if a.selftest:
        return selftest()
    if a.build:
        if not a.commit:
            raise SystemExit("publish-glance: --build needs --commit "
                             "(the stamp is what tells a fresh page from a "
                             "cached one)")
        build(a.root, a.out_dir, a.commit)
        return 0
    if a.check:
        return check(a.check, a.expect_commit, a.max_age_min,
                     a.retries, a.wait_sec)
    ap.print_help()
    return 2


if __name__ == "__main__":
    sys.exit(main())
